### ISSUE TITLE
Master Bug: Be Windows-friendly

### ISSUE THREAD

**Issue by rcombs** [libass/libass#106]
This is a master bug for tracking everything blocking libass from being easy to use on Windows in a native DShow pipeline.
- [x] Compile with MSVC; document relatively simple procedure
- [x] [Add Windows GDI or DirectWrite fontselect](https://github.com/libass/libass/issues/79)
- [ ] Provide a DirectShow filter
- [ ] Get said filter bundled with LAV Filters and/or CCCP

**Comment by feliwir** [comment]
I wanted to ask if there is any progress being made with this?

**Comment by wm4** [comment]
No. It should compile with MSVC, so that part should be fine. But we're missing a GDI backend and a dshow filter. @grigorig wanted to do something about the GDI backend, but apparently didn't have time for this.

**Comment by wm4** [comment]
Here are MSVC project files: https://github.com/tgoyne/aegisub/tree/master/build/libass

And apparently some minor hacks to make it compile?

**Comment by feliwir** [comment]
here are my msvc project files & a guide how to set it up: https://github.com/feliwir/libass-msvc

**Comment by grigorig** [comment]
The MSVC project has been cloned into the libass org. It is not perfect, but easy to use and it works.

**Comment by Armada651** [comment]
If I had time I'd definitely work on a directshow backend, but unfortunately I'm very busy.

But for anyone trying to implement a directshow filter, you can also support this protocol so that the players that support that interface will be able to overlay the subtitles at high resolution: http://madshi.net/SubRenderIntf.h

**Comment by TheOneric** [comment]
Is this issue still relevant?

 - We compile unproblematic¹ as is with MinGW producing native WIndows binaries. And for Microsoft's VSC, our code is compatible¹, but MSVC-project files are needed.
   Although our own MSVC project files are unmaintained and likely broken, [ShiftMediaProject](https://github.com/ShiftMediaProject/libass) provides MSVC project files which appear to even support dynamic library builds, and the Meson port by CoffeeFlux should also be able to produce MSVC files — though they are only usable for static libs due to an Meson-upstream issue.
 - We have a DirectWrite FontProvider (using GDI Interop)
 - There's an AviSynth(+)-Plugin for libass
 - MPC-HC has libass support now, though currently(?) buildtime-disabled by default
 - There are/were at least two DirectShow-Filters for libass [DirectASS](https://github.com/TypesettingTools/DirectASS) (which seems dead) and [ASSFilterMod](https://github.com/Blitzker/assfiltermod), which is inactive but has some semi-active forks, eg [this one](https://github.com/Masaiki/assfiltermod)
   There's also the [VSF-wrapper by jessec](https://github.com/jesec/xy-VSFilter/tree/cr-libass) to make libass a drop-in replacement for VSF-consumers, though activity ceased after initial completion.
 - CCCP seems inactive. Don't know how relevant getting a libass-DS filter into LAVF is, considering MPC-HC supports a libass backend and VLC, mpv et al work on WIndows *(without interacting with any DS-Filters)*.
 
 ---
 
 [1]: Except for our `readdir` use either having a chance to drop non-ASCII files *(MinGW's wrapper)* or needing an additional dependency *(MSVC)*. But this is already tracked in a separate issue.

**Comment by rcombs** [comment]
Yeah, this is obsolete; closing.
