### ISSUE TITLE
Blur-related regression

### ISSUE THREAD

**Issue by rcombs** [libass/libass#125]
http://puu.sh/aJ2Tz.zip
The build of Aegisub I have laying around (7932-master-58f35cd) renders this fine, but `master` and `pthreads` both run excruciatingly slowly. There are some large blurs; removing the largest ones is a slight improvement; removing all of them gets us back to fullspeed. Can't tell if this is all a cache failure, all blur being too slow, or a mixture.

**Comment by NoNetGuy** [comment]
I think I've also observed this problem. These two lines are displayed simultaneously. In the 480p, mp4 version of the episode I have, there is some slow down. In the 1080p mkv version of the same episode, the frame rate drops to about 1 frame every 3 seconds. These are the offending lines:


Dialogue: 0,0:08:46.21,0:08:48.92,TS,,0000,0000,0000,,{\q2\fnBethany Style Letters\fs48\b1\xshad3\yshad1\bord2\3c&HA73C43&\4c&HA73C43&\frz302.451\c&HA99A95&\blur1\alpha&H88&\move(182,650,-115,191,0,2733)}Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob
Dialogue: 0,0:08:46.21,0:08:48.92,TS,,0000,0000,0000,,{\q2\fnBethany Style Letters\fs48\b1\xshad3\yshad1\bord2\3c&HA73C43&\4c&HA73C43&\c&HA99A95&\blur1\alpha&H88&\frz59.869\move(1030,508,1401,-117,0,2733)}Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob  Sob   Sob   Sob   Sob   Sob   Sob  Sob   Sob   Sob  Sob   Sob   Sob

As I read it, there is some blur and the lines are both offset at different angles from each other as well as from the normal dialog on the screen.

**Comment by TheOneric** [comment]
The original sample link is dead. Testing the lines from NoNetGuy's comment, there was no issue on my Desktop, which can also be attributed to my current CPU being faster than my CPU in 2014.
Testing whatever libass version ships in F-Droid's VLC-build on a quad-core Cortex A9 1.5GHz with 1080p and 720p there are very noticeable frame drops. Though to be fair this CPU and the accompaning GPU were already comparatively weak when this issue was opened. *And I just noticed it also drops some frames on 720p without blur.*

Does #394 solve the frame drops on the original or other reasonable hardware?

**Comment by MrSmile** [comment]
> Does #394 solve the frame drops on the original or other reasonable hardware?

No, it's the algorithm simplification and not a performance increase PR. Especially on ARM, where we don't have corresponding assembly.

**Comment by TheOneric** [comment]
With the original sample being lost and the other example from comments doing fine with modern libass, there’s nothing actionable left in this issue.
