### ISSUE TITLE
\an4/5/6 collision stacks the wrong way.

### ISSUE THREAD

**Issue by torque** [libass/libass#143]
Pretty much what it says. I don't know why you'd want to have collision with \an5, but it seems like a simple enough thing it should probably be fixed.

[Script](https://gist.github.com/torque/9343c789813f90ce09be).

Photo evidence taken from xy-vsfilter shipped with Aegisub 3.2.1 and libass 26ccc19 on OS X.

libass:
![libass](https://cloud.githubusercontent.com/assets/949138/4943957/62ffa30a-65f9-11e4-9cfd-b9a154019bbb.png)

vsfilter:
![vsfilter](https://cloud.githubusercontent.com/assets/949138/4943960/66d557ea-65f9-11e4-8d68-00d90ae3b88d.png)

**Comment by klopsi** [comment]
Collisions: If the entry says "Reverse" then subtitles will be 
                 shifted upwards to make room for subsequent overlapping 
                 subtitles. This means the subtitles can nearly always be read 
                 top-down.

**Comment by astiob** [comment]
For reference, VSFilter doesn’t support the Collisions header either. Neither does VirtualDub’s subtitler. Aegisub has even removed support for editing the header because of this.

(Aegisub/Aegisub@cb9c48d6af5d1fac5dda19382e508dd782020f4b says VSFilter also _crashes_ on malformed header values, but I don’t think this is true for any version of VSFilter ever; and Aegisub’s issue tracker is down, so I can’t check where they got this from.)

Sorry for hijacking this issue. The Collisions header is out of the question for now, and this issue is only about the default stacking direction. (Funnily enough—as much as it doesn’t matter because it is so ancient—VirtualDub’s subtitler’s readme.txt suggests it agrees with libass in this situation rather than with VSFilter.)
