### ISSUE TITLE
Various widths not scaled with PlayResX

### ISSUE THREAD

**Issue by aphirst** [libass/libass#171]
```
<torque> uh that looks distinctly like border style 3 with non-100 fscx for anamorphic compensation
<aphirst> http://code.google.com/p/libass/wiki/IssuesAndDifferences
<aphirst> "BorderStyle 3 ("opaque box") does not behave like in VSFilter all the time. VSFilter's implementation is buggy and emulation of these bugs is hard. If possible, avoid using it."
```

**Sample file:** http://a.pomf.se/jgjpyg.mkv (approximately 7 seconds in)
**Rendering in MPC:** http://a.pomf.se/bmcwwd.jpg
**Rendering in MPV & libass:** http://a.pomf.se/hcljvr.jpg
As can clearly be seen, the opaque box between the video and a sign subtitle is the wrong size as compared to the "correct" rendering from MPC with xy-vsfilter.

**My system:**
- Arch Linux x86_64
- `libass 0.12.1`
- `mpv 0.8.3`
- `freetype2-infinality-ultimate 2.5.5`
- `fontconfig-infinality-ultimate 2.11.1`
- `harfbuzz 0.9.40`

**Comment by astiob** [comment]
To clarify: the sample in the original post does not actually have BorderStyle 3 but rather an explicit vector drawing.

However (as illustrated in https://github.com/libass/libass/pull/395#issuecomment-629869816), it turns out there are a whole bunch of widths that we scale as `frame_height / PlayResY` but should actually be scaled as `frame_width / PlayResX`:
* [explicit vector drawing coordinates](https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L893)
* [`\fsp`](https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L2916)
* [`\xbord`](https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L2918)
* [`\xshad`](https://github.com/Cyberbeing/xy-VSFilter/blob/xy_sub_filter_rc4/src/subtitles/RTS.cpp#L2920)

possibly more; whenever anyone starts work on fixing this, audit by searching RTS.cpp for `m_scalex`.

I’m not sure what torque was thinking of during that conversation on IRC, but I don’t see any differences in VSFilter’s and libass’s current handling of BorderStyle 3 in anamorphic video except this (non)scaling of border width itself if applicable. Maybe he was thinking of something else (like the double-scaling of BorderStyle 3, which we’ve long supported), or maybe it has been fixed in the meantime.
