### ISSUE TITLE
Sanitize color coding in SSA/ASS header

### ISSUE THREAD

**Issue by kamijoutouma** [libass/libass#178]
Refer to https://forum.videolan.org/viewtopic.php?f=18&t=126256&p=424788#p424788 for more information.

@grigorig @wm4 @astiob

**Comment by astiob** [comment]
It’s real!!

See #145, in particular my first comment. I personally see this as a low-priority known issue. Has it been happening a lot lately? If so, I might want to actually spend some time to fully fix this now.

**Comment by kamijoutouma** [comment]
Yes it has been happening a lot lately

And its affecting VLC AegiSub and Handbrake

**Comment by astiob** [comment]
I’ll try to fix it tomorrow.

**Comment by kamijoutouma** [comment]
Thank you
@astiob

**Comment by astiob** [comment]
Just to make myself clear:

**The subtitles that this affects are broken.**

This is **not** an official feature of the SSA format (nor ASS) that libass didn’t support; this is essentially a bug in VSFilter’s implementation of it. Unfortunately, some people and some files rely on VSFilter bugs, which is why we replicate them in libass.

However, we believe this specific bug is used very rarely. In fact, your sample (whatever it may be) is the first one we’ve ever seen as far as I’m aware. There are still some (many?) other VSFilter bugs and implementation details of a similar nature—they can be exploited but shouldn’t be, and they’re exploited by few or very few files in practice—that libass still doesn’t replicate. Each such issue, _including this one,_ is hardly critical on its own and does not warrant an immediate and urgent fix in libass and all media players using it as soon as a file that uses it is discovered.

libass will now support the colours in your SSA file (as soon as my patch is reviewed by other collaborators), but regardless of this, if possible, you should tell whoever authored the file to fix it. `0x` is not a valid colour prefix, and it only works by a fluke.

**Comment by kamijoutouma** [comment]
I understand and thank you.
