### ISSUE TITLE
Require HarfBuzz?

### ISSUE THREAD

**Issue by astiob** [libass/libass#199]
Lots of things break without HarfBuzz: Arabic (right? I think FriBidi had some sort of fallback thing but it isn’t good?), vertical Japanese, syllabic Korean and many other Asian scripts. (How do Indic scripts fare?) The kerning setting in libass also does nothing without HarfBuzz despite being exposed, and some fonts might rely on OpenType features for correct display even of European scripts.

HarfBuzz has long been very easy to build on all major platforms including Windows, Linux and OS X. HarfBuzz _does not require_ GLib, ICU, Cairo or any other external library. It optionally depends on Graphite2, and while it certainly doesn’t hurt, it isn’t required either (and Graphite2 itself is easy to build as long as you have CMake).

The only problem might be the circular dependency between HarfBuzz and FreeType, but it’s still optional on FreeType’s side and it’s not clear how much trouble it actually causes. And in the worst case, it’s easy to work around by building FreeType without HarfBuzz, then building HarfBuzz with FreeType and then rebuilding FreeType with HarfBuzz if so desired. (Note: HarfBuzz’s dependency on FreeType is usually optional, but _libass requires_ HarfBuzz to depend on FreeType.) (Note²: this means making HarfBuzz a hard dependency of libass would effectively make FreeType a hard dependency of HarfBuzz.) (Edit: when upgrading, the circular dependency actually doesn’t break any build; it just confuses HarfBuzz’s build system when it’s checking FreeType’s pkg-config file. Remove HarfBuzz from freetype2.pc, build HarfBuzz, add it back. Voilà.)

How about we make HarfBuzz a hard requirement to build libass?

If not, or as a transitional measure, how about we make HarfBuzz a “strongly recommended” dependency, so that `./configure` refuses to proceed without it unless you explicitly run it with `--disable-harfbuzz`?

**Comment by grigorig** [comment]
In general I think it's fine to require HarfBuzz as a hard dependency. Some further notes:

> Arabic (right? I think fribidi had some sort of fallback thing but it isn’t good?)

Correct. The fallback code in FriBiDi requires the font to have a full set of precomposed Arabic forms, and not all do.

> And in the worst case, it’s easy to work around by building FreeType without harfbuzz, then building harfbuzz with FreeType and then rebuilding FreeType with harfbuzz if so desired.

> The kerning setting in libass also does nothing without harfbuzz despite being exposed

If so, that is a bug. :) Kerning should also work without HarfBuzz. We could drop that code if we make HarfBuzz mandatory, though.

The HarfBuzz support in FreeType is only required for correct autohinting in case OpenType shaping is used, so it isn't really important to libass, because hinting shouldn't be used.

> (Note: harfbuzz’s dependency on FreeType is usually optional, but libass requires harfbuzz to depend on FreeType.)

libass already mostly implements the font functions of HarfBuzz. It shouldn't be hard to make libass independent of hb-ft, the FreeType support module of HarfBuzz. But do we gain anything from that, realistically?

**Comment by wm4** [comment]
A bit worried about forcing a big dependency like harfbuzz when it could be avoidable, on the other hand it'd be nice to get rid of the ifdeffery and rarely tested non-hb code paths.

**Comment by adah1972** [comment]
Trying to build libass on Mac and finding this recommended dependency on harfbuzz, which requires quite a lot other dependencies. It turns out cairo is required to build harfbuzz, in both MacPorts (directly) and Homebrew (due to gobject-introspection). So practically speaking, Cairo is required to make HarfBuzz work on OS X.

**Comment by rcombs** [comment]
That's a problem for the Homebrew guys. It should be pretty trivial for them to make those HB dependencies optional; you can send a PR yourself if you like.

**Comment by grigorig** [comment]
HarfBuzz doesn't really require anything particular. HarfBuzz *can* use glib, it *can* use Cairo and some other things, but all of these are optional and sometimes only needed for testing.
