### ISSUE TITLE
"kf" tag and filling RTL text

### ISSUE THREAD

**Issue by SafaAlfulaij** [libass/libass#221]
There is a problem with filling Arabic text in case of "kf" tag is used, where the filling starts from the left of each letter instead of right.

Sample:

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Droid Naskh Shift Alt,80,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,174

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,{\kf44}Te{\kf67}st {\kf44}Be{\kf45}st
Dialogue: 0,0:00:02.00,0:00:04.00,Default,,0,0,0,,{\kf36}ن{\kf55}ص {\kf36}أ{\kf36}و{\kf37}ل
```

Libass:
![dummy_003_64](https://cloud.githubusercontent.com/assets/3509617/14942717/3f2abf48-0fce-11e6-97dd-9e36c72038db.png)

VSFilter (Shaping is wrong):
![dummy_002_64](https://cloud.githubusercontent.com/assets/3509617/14942718/4709d5a0-0fce-11e6-933f-5c9a2a3d367c.png)

**Comment by astiob** [comment]
On second thought (after my comment in #295), as far as I can tell, VSFilter also fills left-to-right, but the fill appears contiguous due to the left-to-right ordering of the characters, whereas in libass you see how the fill jumps from the right end of one character to the left end of the character to the left of it because it orders the characters right-to-left. Is this right?

Could you explain what exactly you want here? libass to fill right-to-left? What is the significance of the VSFilter screenshot?

If you are are a subtitle author, I’m afraid you’ll want to ditch the `\kf` tag anyway because it breaks bidi and shaping in VSFilter, as you can tell from your own screenshot. The best alternatives I can suggest, just as in #293, is an animated rectangle `\clip` or duplicating the line frame-by-frame and setting a `\clip` on each (probably automated through a script).

**Comment by astiob** [comment]
I’m closing this because the report illustrates nothing about karaoke filling.

VSFilter fills the provided sample from left to right, just as libass does.

The only difference here is the bidirectional ordering of the text itself, which is another (very well-known) issue: libass reorders the whole line, but VSFilter isolates each block and flows the blocks left-to-right.
