### ISSUE TITLE
Arabic subtitle problem (typesetting)

### ISSUE THREAD

**Issue by Ragna0** [libass/libass#226]
This is the problem

when using VLC 
![sample 1](https://cloud.githubusercontent.com/assets/20019174/16173949/5ff2b756-35b9-11e6-8aff-0fddaeea8cad.jpg)

when using MPC
![sample 2](https://cloud.githubusercontent.com/assets/20019174/16173955/7279239c-35b9-11e6-8b73-bc899a54935b.jpg)

So the typesetting isn't showing as intended

script:
http://rgho.st/7LZ25sqdF

**Comment by SafaAlfulaij** [comment]
I can't see where is the problem. LibASS is showing it correctly (according to the script).
This is a problem in VSFilter, and I reported it 2 months ago. I think we should wait so VSFilter developers can figure out what to do. (Issue: https://trac.mpc-hc.org/ticket/5838)
It is really bad to open a bug in a software saying that you are doing the right thing but I want the wrong way because of another Y software has such a buggy behavior that Arab fansubbers worked around it and didn't care about LibASS and **just** waked up seeing that their subs aren't working probably on LibASS-based players.
Please stop crippling the source code just to keep compatibility. Those who want old behavior should get an old version. Things can be solved using scripts that modifies old subtitles (talking about bidi stuff here, which is easier than drawings). Another option is offering an option to switch between old and new behavior.

**Comment by realfinder** [comment]
libass is full with worked around that keep compatibility with the subtitles that made for vsfilter even for English sub
so stop trolling please

**Comment by realfinder** [comment]
the file host is down but this should be fixed in https://github.com/libass/libass/pull/441

IIRC I download this file and it has ass tags
