### ISSUE TITLE
Leak of bitmap data with kodi

### ISSUE THREAD

**Issue by popcornmix** [libass/libass#248]
I'm investigating this long standing issue with kodi:
http://trac.kodi.tv/ticket/15820

It occurs with kodi's default 0.12.1 and with master of this git repo.
I've added logging to the malloc/free calls:
http://paste.ubuntu.com/23433058/

and get (using master of this git repo):
http://paste.ubuntu.com/23433071/

The largest leak is from here (alloc_bitmap):
ass_bitmap.c: 138:malloc(57667)=0x52c0358 (3626698)

Nothing in libass frees this (the log includes stopping video playback and shutting down kodi).

Now, is there anything kodi is not doing that results in the data not being freed?

**Comment by astiob** [comment]
@popcornmix This won’t help with your issue, but it seems to me from your log that Kodi doesn’t call `ass_renderer_done` when shutting down, which should make libass free almost all of its memory (the rest is freed in `ass_library_done`). Of course, it doesn’t really matter, as all resources are going to be freed upon shutdown anyway.

@libass/developers I’ve looked through the caching code (and other code that uses it) and done a bit of testing. Everything seems correct. The only idea I have is that maybe the composite bitmap cache is smaller than the size limit, while the glyph bitmap cache is long overcrowded but unable to free its memory because it’s still referenced in composite cache keys. I’m not sure how this situation can occur, but if this is the case, perhaps we need a mechanism that would let the glyph bitmap cache know which composite bitmap cache entries are holding it up and purge them along with its own corresponding entries. Or we could just temporarily reduce the composite bitmap cache size limit to zero if the glyph bitmap cache exceeds its limit and is unable to free up enough memory on its own.

**Comment by MrSmile** [comment]
Composite bitmap size is almost never smaller than sum of sizes of its component bitmaps. And glyph bitmap cache is 2 times larger than composite. Due to that at least half of glyph bitmap cache is ready for deleting.

I think we should add API function for setting cache size. Bug link shows that memory consumption is only around 100M and current bitmap cache limit is 192M (and 1G before my cache PR) so that is not memory leak but process of cache filling.

**Comment by astiob** [comment]
> I think we should add API function for setting cache size.

We have one: `ass_set_cache_limits`.

> Bug link shows that memory consumption is only around 100M and current bitmap cache limit is 192M (and 1G before my cache PR) so that is not memory leak but process of cache filling.

No, one of the last comments in the linked bug report shows Kodi consuming a whopping 7 GB of memory! This is definitely a leak on our side.

**Comment by astiob** [comment]
Oh, unless Kodi creates a new ASS_Renderer every time it starts playing a file and never ever calls `ass_renderer_done`. The test that had 7 GB was playing the same file on repeat, so if Kodi does this, then bitmap memory is allocated anew every time and never released. @popcornmix

**Comment by popcornmix** [comment]
@astiob Kodi should be calling ass_renderer_done
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp#L100

However logging that call isn't triggering. Let me investigate the reference counting of the class.

**Comment by popcornmix** [comment]
See: https://github.com/xbmc/xbmc/pull/10873

Lets just wait for a bit more testing, but I think libass may be in the clear.
Thanks for the missing ``ass_renderer_done`` observation - that helped to narrow down what was going wrong.

**Comment by astiob** [comment]
No worries, and thanks for the report anyway!

The original Kodi bug report also complains about memory use growing by amounts such as 100 MB or 60 MB. I realize this is a problem on systems with little RAM. This is most likely the result of libass caching various bitmaps to avoid rerendering them when they are reused.

The caches are limited in size, but the size limits are absolute amounts in bytes, independent of the total available RAM. The default cache size limit is currently about 192 MB. Evidently this is too high for some systems, creating the appearance of a memory leak and eventually an out-of-memory situation. The cache size limit can be changed by the application by calling `ass_set_cache_limits(ass_renderer, 0, cache_limit_in_mebibytes)`, available at least since libass 0.9.7, commit 3fd039c16184d5864c8a3be561c8b547b52ddf83, although it seems this only changes one of two currently relevant limits (which accounts for 128 MB out of the default 192 MB)—something we need to address.

**Comment by popcornmix** [comment]
Yes. 192M is high, but plausible for a 1G Pi2/Pi3.
On a 512M Pi1 which will have 128M dedicated to GPU it is probably too much.
On an original 256M Pi1...

So currently with kodi, you sometimes get a stutter when a new subtitle font is used. I guess reducing the cache size means that may not just occur at start of file, but could occur later (if font styles change).
Do you have a feel for what a minimum usable cache size is (assuming simple subs)?

**Comment by popcornmix** [comment]
Fix has been merged into kodi.
My malloc wrapper now reports 0 bytes allocated by libass when playback is stopped.

Adding the ability to set the composite bitmap cache size at runtime would be useful for Kodi on limited memory Pi style devices would still be useful.

But thanks for the help.

**Comment by astiob** [comment]
Just to let you know, as soon as #249 lands in libass master, `ass_set_cache_limits` will (once again) set the total bitmap cache size rather than only part of it like it does now. So then if you do, say, `ass_set_cache_limits(ass_renderer, 0, 50);`, libass shouldn’t use much more than 50 MB of memory in total (although it can also depend on the fonts used in the subtitles).

> Do you have a feel for what a minimum usable cache size is (assuming simple subs)?

If I got my maths right, then for simple subs, 21 MB (or 14 MB before #249) should be enough to hold all bitmaps of all English letters, digits and typical punctuation in a single font at a size typical for 1280×720 video. Even less than that if the CPU is an x86 and SSE2 (but not AVX) routines are used. And probably even less than that is actually needed for smooth playback.

On the other hand, if the script has any kind of pretty sign translations, they will most likely be unable to reuse the same cached data. If there’s not many of them and/or they’re not complicated, a small cache may still be fine, but of course, it would be great to increase the cache size when possible. I don’t know how hard this is, but perhaps Kodi (or eventually, maybe even libass itself) could detect the amount of available memory on the system and set the cache size proportional to that.

**Comment by astiob** [comment]
For reference, #249 has landed in master and is going into the 0.13.5 release that will be made in a few minutes. `ass_set_cache_limits` will now set the total bitmap cache size.
