### ISSUE TITLE
invalid memory read in blend_single()

### ISSUE THREAD

**Issue by hannob** [libass/libass#254]
The attached file (zip'ed due to github file type restrictions) will segfault libass due to a read access to some unallocated memory. This was found with american fuzzy lop.

This can be tested with the "test" tool in libass' test directory. (e.g. ./test x libass-invalid-read-blend_single.ass 1).

Here's a stack trace from address sanitizer:
```
==21209==ERROR: AddressSanitizer: SEGV on unknown address 0x7fdc3b826c00 (pc 0x0000005041b9 bp 0x7ffc82167a90 sp 0x7ffc82167940 T0)
==21209==The signal is caused by a READ memory access.
    #0 0x5041b8 in blend_single /mnt/ram/libass-0.13.6/test/test.c:149:40
    #1 0x5041b8 in blend /mnt/ram/libass-0.13.6/test/test.c:162
    #2 0x5041b8 in main /mnt/ram/libass-0.13.6/test/test.c:217
    #3 0x7fdc3f5dc78f in __libc_start_main (/lib64/libc.so.6+0x2078f)
    #4 0x41bbe8 in _start (/r/libass/test+0x41bbe8)
```
[libass-invalid-read-blend_single.zip](https://github.com/libass/libass/files/697592/libass-invalid-read-blend_single.zip)

**Comment by astiob** [comment]
Thank you for the report!

@wm4 The problem is that BorderStyle=4 is not clipped against the screen. In this sample, MarginV is so high that the text has a negative y coordinate, the BorderStyle=4 ASS_Image inherits a negative `dst_y`, and the image consumer (e. g. our test program or `vf_sub`) crashes or corrupts its memory when it attempts to blend the ASS_Image onto the video. The ASS_Image itself is fine (probably), but the blending code attempts to access `video[dst_y * stride + dst_x]` and lands in uncharted territory.

We can probably just do the clipping while generating the BorderStyle=4 box (in `add_background`). Right?

**Comment by wm4** [comment]
Yeah, all ASS_Images should be clipped against the screen.

**Comment by wm4** [comment]
Here's an attempt at fixing it. I wasn't able to use your sample file (it seems useless?), so I used http://sprunge.us/IXMh

**Comment by astiob** [comment]
Weird; the sample worked for me (although I tested it in my own utility rather than our `test`). Perhaps you weren’t lucky and the invalid memory access failed to actually break anything for you.

The only significant difference from your file is that it uses a normal font size with a high MarginV (and default/bottom alignment) rather than a huge font size. But any method of moving the text beyond the edge of the screen should work equally well.

**Comment by wm4** [comment]
I actually cheated and tried to open it with mpv - but libavformat's ASS demuxer fails on the given sample.
