### ISSUE TITLE
Invalid FreeType API usage

### ISSUE THREAD

**Issue by wm4** [libass/libass#274]
Someone linked me this: http://lists.nongnu.org/archive/html/freetype/2017-04/msg00034.html

**Comment by rcombs** [comment]
Unfortunately, the user didn't provide enough information to reproduce the script the problem was happening with, so we can't tell what's _supposed_ to happen in this case. Without that, I don't think this is actionable; we'd just be making a wild guess (and I don't have any reason to believe that guess would be any better than whatever freetype does, with the exception of the brief period when it crashed). So I'm closing this out for now.
