### ISSUE TITLE
Request to make overlapping subtitles appear at bottom and scroll subs.

### ISSUE THREAD

**Issue by klopsi** [libass/libass#280]
When watching a youtube, subtitles scroll from bottom to top.
Downloaded youtube subtitles overlap in time.
libass places subtitles alternating lines, in the case of a 2x overlap, or  seemingly random lines in the case of more overlap.

REQUEST: Scroll subtitles from bottom to top, with each newest sub appearing at bottom - like youtube does, and terminals do.

Thank you very much.

**Comment by astiob** [comment]
Just to be clear, in particular with respect to SSA’s Collisions header, this would have to be a new libass-only feature rather than an existing feature of the ASS format that libass currently doesn’t support. Please keep in mind that libass is primarily an ASS renderer, although it does already have some additional features.

The Collisions header seems like what you want at first, but I suspect that it is only actually supposed to work that way when multiple lines have the exact same beginning time, rather than when a line appears after a previous line is already on screen. At least currently (in all ASS renderers), **once a line appears on screen, it stays in place** and never moves, regardless of other lines appearing or disappearing (unless the line is explicitly animated). I tried to check what the header actually does in other renderers but found that it isn’t supported by any. I may fire up SSA itself at some point to try to find out, but I don’t promise.

You can get a feel for this by setting your subtitles to appear on the top of the screen rather than the bottom. That way, they’re automatically ordered top-to-bottom. But as soon as you get a line that overlaps in time with two other lines, you’ll see how this isn’t perfect. Imagine you have three lines:

* 0:00–0:09 Line 1
* 0:05–0:15 Line 2
* 0:11–0:20 Line 3

With subtitles on the bottom, you will see the following on screen:

```
            │   Line 2   │   Line 2   │   Line 2   │
   Line 1   │   Line 1   │            │   Line 3   │   Line 3
────────────┼────────────┼────────────┼────────────┼────────────
    0:03    │    0:07    │    0:10    │    0:13    │    0:17
```

With subtitles on the top:

```
    0:03    │    0:07    │    0:10    │    0:13    │    0:17
────────────┼────────────┼────────────┼────────────┼────────────
   Line 1   │   Line 1   │            │   Line 3   │   Line 3
            │   Line 2   │   Line 2   │   Line 2   │
```

In either case, you see the lines in incorrect order at some point in time. And if you open the file and immediately seek (jump) to 0:10, you’ll get different results! Because the renderer will not have seen Line 1 at all, it will position Line 2 at the edge of the screen, as nothing will be blocking it.

If you want moving subtitles or even simply a consistent ordering that is not affected by seeking, you need to specify the appropriate override tags in the ASS file. It probably wouldn’t be very hard for someone who knows programming and a bit of ASS to write a script that can process a tagless ASS file and add those tags automatically.

Of course, the same functionality could theoretically be provided by libass itself. It could recalculate the layout of nonpositioned events for every frame, which I guess would be enough for ensuring lines show up in the right order without animations? Animations are harder though. For that, libass would have to look ahead to see if any (and how many) other nonpositioned lines are going to appear soon and synthesize an appropriate animated move. I’m not sure this is even always _possible_ for subtitles embedded in a container such as MKV, or even for external subtitle files in some players (which use their own ASS demuxers).

**Comment by klopsi** [comment]
Thank you for the explanation!   I'll have to parse the downloaded youtube captions to eliminate overlays in the meantime.

Sad, since it seems so logical to have the caption behavior as youtube does it. 

Thank you again for your kind reply.
