### ISSUE TITLE
"kf" tag and Vertical text

### ISSUE THREAD

**Issue by huqitu** [libass/libass#293]
There is a problem with filling vertical text(fr270) in case of "kf" tag is used, where the filling starts from the left to right of each letter instead of top to down.
![1](https://user-images.githubusercontent.com/485086/33301561-4b5f744c-d431-11e7-8e3b-345d71d282ac.png)
![out_20171128113820](https://user-images.githubusercontent.com/485086/33301567-52c38de0-d431-11e7-82e9-5e179d66b9e7.JPG)

**Comment by astiob** [comment]
Thank you for your report. However, `\kf` always works like this: compare to the [rendering in other software](https://chortos.selfip.net/~astiob/screens/karaoke-transformed/).

If we were to change this in libass (which is not necessarily easy), we would break all of the existing scripts that rely on this behaviour and break compatibility with other renderers (unless they followed suit and made the same change at the same time).

If you really want to achieve a vertical fill effect, I can advise two things:
1. Have two copies of the `Dialogue` line, each in its own colour, and use something like `\clip(0,10,1280,10)\t(\clip(0,10,1280,710))` on the first line and `\clip(0,10,1280,710)\t(\clip(0,710,1280,710))` on the second. Make sure that the coordinates and the line start/end times are set such that the resulting clip coordinates during the animation are integers, otherwise the one pixel on the border between the two colours may be noticeably discoloured. This is not always possible (especially not if the fill should be slow—slower than a pixel per frame), and if it isn’t, you may want to either accept the discoloured pixel or use my second suggestion.
2. Use a tool (e. g. an Aegisub plugin) to generate the same effect by splitting the line into many and explicitly setting clip coordinates on each. I don’t know if such an Aegisub plugin already exists, but it should be relatively easy to do this (even if only as an external program rather than a plugin) for someone with basic programming skills.

**Comment by huqitu** [comment]
thank you for you help. but the vertical style scripts like mongolian( writing style is top-down left-right , have a look at this site:http://www.mgyxw.net/) really need top-down rendering effects. so if you can tell me how to modify the code to get top-down  rendering effects than I will edit the code it by myself and make a version of libass( may be called Vertical edition of libvass?).

**Comment by huqitu** [comment]
[https://chortos.selfip.net/~astiob/screens/karaoke-transformed/](url) these effects are looks perfect, but in libass not follow these effect when \fr270 or \fr90. In libass the effects looks like change no regular.

**Comment by astiob** [comment]
The page shows how things look in libass, among other things. We know that the current libass behaviour (where it says “libass 0.10.2-47-gfa3b6fa and older, 0.12.1-6-gb63d893 and newer”) is strange and wrong, and we do hope to fix it. However, none of the pictures show top-down filling, which you want.

In fact, `\kf` with any transforms (rotations/shears, `\frx\fry\frz\fax\fay`) at all is inherently unintuitive and in most cases undesired, as you can clearly see in the 7th image: `\kf` measures text before transforms and uses those same coordinates even after transforms, when they no longer match what’s visible on screen. We may eventually decide to change this by adopting the same behaviour as VSFilterMod and MPC-HC (see “MPC‑HC 1.7.3.4 and newer”), which use the final transformed coordinates for `\kf`, if we can determine that this wouldn’t break (too many) existing subtitle files. However, even then all `\kf` filling is still purely horizontal.

If you want vertical filling, you need to use other animated features of ASS (`\t`) or provide a separate subtitle line for each frame, like I suggested earlier. More complicated karaoke effects do this anyway. English-language anime fansubbers sometimes include vertically-written Japanese song lyrics with karaoke effects, so you might be able to find an existing karaoke effect script for Aegisub that looks good to you and works with vertical text.

You are, of course, free to fork libass and try to make it render `\kf` vertically, because libass is free software. But this would only harm your viewers, because they would have to install your libass fork to view your files and install another renderer to view anyone else’s files. At the moment, it is also not easy to make this change in libass—especially when the current handling of `\kf` is broken, as you saw yourself. If changing this was easy, we would quickly fix this bug :-) We will try to make the karaoke effect code easier to understand in the future.

It is a much better idea to write your subtitles so they can play in any standard ASS renderer, by avoiding `\kf` entirely and either using `\t` or providing a separate subtitle line for each frame.

**Comment by huqitu** [comment]
Yes, I have tried your suggested earlier, but I can't get lines coordinate for clip when it's rotated, any suggestion?

**Comment by astiob** [comment]
I’m closing this, as the reported issue (\kf in vertical writing) is not supported by ASS.

I’m afraid help with finding the correct coordinates to use in an ASS script is out of scope for the libass issue tracker. This can be done manually in Aegisub or a media player, and I assume Aegisub scripts exist to automate this. Further assistance would be best sought with fansubbers.
