### ISSUE TITLE
\shad baseline does not rotate relative to \frz, causing incorrect movement with \t

### ISSUE THREAD

**Issue by begna112** [libass/libass#300]
To make describing this issue easier, a definition:
baseline
The imaginary line on which the majority of the characters in a typeface rest.

When rotating a line with \frz, VSFilter rotates the baseline. Libass appears to do this on first inspection, but it fails to do so when it involves \shad. 

For example, this line uses \shad0.01\frz298.9\t(\xshad-800). 

VSFilter maintains the relative position of the subtitles and "moves" them along the rotated baseline. 
![aegisub64_2018-03-10_13-36-25](https://user-images.githubusercontent.com/10567958/37246278-3f8e17b4-246c-11e8-9e38-1d2f2af7a69e.png)

While Libass ignores the rotated baseline and moves it along the x axis. 
![aegisub64_2018-03-10_13-36-55](https://user-images.githubusercontent.com/10567958/37246290-5e532194-246c-11e8-8fcd-aa038a310519.png)

When used without \frz, this problem is invisible, when used with it, it becomes glaringly obvious. 

I'm including a video clip, a font and two sets of example lines (one at \frz0, the other at \frz298.9). 
[Blend S - 07 [For Libass GIthub].zip](https://github.com/libass/libass/files/1799748/Blend.S.-.07.For.Libass.GIthub.zip)

This may be related to the different rendering of shadow rotation between libass and vsfilter (https://github.com/libass/libass/issues/141). However, I think it should still be corrected. Shadows are incredibly useful because they can be blurred all the way through and transformed with acceleration where \move cannot. It's not irregular for me to use something along the lines of \bord2\shad0.01\1a&HFE&\3a&HFE&\blur3 so that the entire character blurs rather than just the border area or \shad0.01\1a&HFE&\3a&HFE&\t(23,984,0.7,\xshad-40\yshad13) to move a line with acceleration. If this rotation issue is not fixed, it becomes more difficult to take advantage of these useful features of shadows.

**Comment by astiob** [comment]
Thanks for reporting!

I do think this is related to #141. It appears that in my last comment there I actually explained that VSFilter rotates shadows like this and it seems sensible but failed to explicitly point out that libass doesn’t, although it’s implied. It’s good to know that this is actually important to someone. I’ll try to fix this, but I’d prefer to do it after we merge #285, which I need to finish reviewing first.

In fact, I’d say this is a _part_ of #141. If we rephrase #141, we could say that when a line has a shadow and a rotation,

1. VSFilter and libass rotate the shadow differently, and
2. VSFilter and libass rotate the main glyphs + border differently.

This issue, then, is about just the first part. Of course, the second part also affects you, but you don’t notice it because your glyphs and borders are almost transparent.

**Comment by begna112** [comment]
I tried to read through #285 and I'm not really able to keep up up with the discussion there. Any updates on that and this / #141 getting approved and fixed? This is a major blocker to adopting libass over xy-vs/xy-subfilter for advanced typesetting.

**Comment by begna112** [comment]
Now that #285 is merged, any chance we'll see movement on this and #141 ?
