### ISSUE TITLE
ASS subtitle without [Script Info] section is not supported

### ISSUE THREAD

**Issue by ArieShout** [libass/libass#325]
I have ASS subtitles downloaded from various internet sites that do not have `[Script Info]` section completely (the first line is `[V4+ Styles]`). When I open this subtitle with [IINA](https://github.com/iina/iina) that depends on libass for ASS subtitle processing, it just said the subtitle is not supported. The following are related issues reported in the downstream players that fail in this case:

* mpv: https://github.com/mpv-player/mpv/issues/2846
* IINA: https://github.com/iina/iina/issues/2124

The temporary workaround for me is to add `[Script Info]` to the first line of the subtitle, and libass accepts it even without any actual section data.

As I understand, the ASS specification states that IF an ASS subtitle contains `[Script Info]` line, it has to be the first line without any leading white space. It's completely fine that the `[Script Info]` section is completely omitted, in which case we just use some plain default values for the info.

**Comment by ArieShout** [comment]
Hi @astiob , thanks for checking this. I wanted to confirm if it's an libass issue before submitting the issue, but didn't find a trivial way to do that. Sorry about the noise.

As this is not a libass issue I'm closing it.
Thanks,

**Comment by wm4** [comment]
It's true that mpv stopped using libass for parsing .ass files, and uses libavformat (simply because that was simpler than having a separate libass "demuxer", which would need a complicated way to transfer the subtitle data from demuxer layer to subtitle renderer). It's indeed a problem with ffmpeg's probe function, but the demuxer itself parses files without headers (whether it does so correctly, no idea). Unfortunately, mpv has no decent way of forcing the ffmpeg ass subtitle demuxer. You could use ``--demuxer-lavf-format=ass``, but that will force the demuxer for the video file too. Works if the video file is mkv though (because then libavformat is never attempted for the video file, and the internal mkv demuxer has higher priority).
