### ISSUE TITLE
Slow fontselect when thousands of fonts are installed (ms-windows)

### ISSUE THREAD

**Issue by zc62** [libass/libass#334]
Several related issues in mpv:
https://github.com/mpv-player/mpv/issues/2998
https://github.com/mpv-player/mpv/issues/6447
https://github.com/mpv-player/mpv/issues/6486

libass is built without fontconfig, so it is using directwrite (#79). Turns out it costs a few seconds even when the subtitle (or mpv's OSD) is requesting only a few kinds of fonts, if a huge amount of fonts are installed. XyVSFilter probably does not have this behavior (did not really test it).

**Comment by Apache553** [comment]
The `scan_fonts` function of DirectWrite font provider will take much time when plenty of fonts installed. As a result of tracing API calls, the whole system font collection would be traversed about 3 times. Each traversal takes about 5 seconds with the API Monitor attached(slowing down the program being monitored) and 874 font families installed in my computer. I believe this function is the cause of the traversal. As far as I know, the xySubFilter uses CreateFont* to get font when the subtitle referred a font hasn't been loaded yet. Maybe we can just load those fonts by their names from system when they are required instead of scanning fonts. I have made some [modifications](https://github.com/Apache553/libass/commit/c141ff1e2bdeaf07d4f2224327c5642af7cee7c7) to the code to implement this and compiled and linked to mpv 0.33.0 release, traced again and found the mpv started faster than before and no longer did the traversal. The rendered subtitle looked correct, at least on my computer.

**Comment by zc62** [comment]
Great! Could you make it a PR? @Apache553

**Comment by ValZapod** [comment]
Regression? https://github.com/mpv-player/mpv/issues/8802#issuecomment-830799010

**Comment by Apache553** [comment]
> Regression? [mpv-player/mpv#8802 (comment)](https://github.com/mpv-player/mpv/issues/8802#issuecomment-830799010)

I made a [pull request](https://github.com/libass/libass/pull/503) to fix this but it haven't been merged yet.
