### ISSUE TITLE
feature request: extend .ASS to support text-decoration (underline) color & style

### ISSUE THREAD

**Issue by daT4v1s** [libass/libass#335]
allow for [ability](https://github.com/Aegisub/Aegisub/issues/115#issuecomment-470940369_) to set separate fill [color](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-color) (maybe also[primary|secondary])
for text-underlines and ~~overstrikes~~

**Comment by daT4v1s** [comment]
currently only
`{\u0}` `{\u1}` underline toggle
`{\s0}` `{\s1}` overstrike toggle

if unified color for both → a bit constrained
if not and from previous syntax, it seems:

`{\uc&FFFFFF}` for color and `{\ua&00}` opacity
`{\sc&FFFFFF}` `{\sa&00}`

also possibilty of underline [styles](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style) `solid | double | dotted | dashed | wavy`
`{\u1}` `{\u2}` …

[overline](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line) also
`{\OvLn1}`

**Comment by TheOneric** [comment]
Generally we only very rarely add ASS-extensions incompatible with other renderers, because … well, they are incompatible.

In this case, as it would be used in general text styling the incompatibility is especially likely to surface.
If you really want to have something like this, you might want to create an Aegisub/Bubblesub/… [script](http://docs.aegisub.org/3.2/Automation/Lua/Miscellaneous_APIs/#aegisubtextextents) to create additional vector drawings as strikethrough/underline in the colour and style you prefer.
