### ISSUE TITLE
Consider supporting Emoji drawings？

### ISSUE THREAD

**Issue by krislyy** [libass/libass#340]
As title says, the project doesn't support emoji drawing.  Do you have plans to support emoji? or is it an easy way for me to support it in my own forked project?  Hope for your replies. Thanks a lot.

**Comment by wangqr** [comment]
On windows, both libass and xy-VSFilter can render emojis (🌤🌂🎜👤👥👀😕) properly. Can you provide more details (e.g. screenshots) to show the problem?

**Comment by rcombs** [comment]
I'm going to assume this is referring to fonts containing RGBA images. Those can't be supported currently because the libass API doesn't support returning RGBA bitmaps. We might readdress this once we have an API for that, though even then it'd require us to provide bitmap scaling. In the interim, everything is fine if you use an outline font, as with any other code point.
