### ISSUE TITLE
Subtitles without spaces do not break to a new line when overfull

### ISSUE THREAD

**Issue by svenper** [libass/libass#360]
by way of mpv-player/mpv#7158 :

> ### Expected behavior
> 
> Subtitle lines without spaces (Chinese, Japanese, etc.) wrap automatically when too long.
> ### Actual behavior
> 
> Such lines extend outside the window, with characters cropped.

See e.g. at 43:00 in [sub.ass](https://github.com/mpv-player/mpv/files/3855514/sub.txt) with a large font size:

```text
Dialogue: 0,0:43:00.01,0:43:06.16,Default,,0,0,0,,任何一个有远大抱负的男人都不会因为区区一个女人
```

(Many lines in the subtitles do indeed have spaces between short phrases, which is an exeption to the rule in East Asian scripts.)

**Comment by siikamiika** [comment]
Found this function while investigating this myself:
https://github.com/libass/libass/blob/6a670b485536e0398b3fc414fc4317a7b65b5622/libass/ass_render.c#L1588

I'd implement line breaking so that first priority would be for spaces as listed [here](http://jkorpela.fi/chars/spaces.html), and if the line would still be too long I would break before any CJK character that goes above `max_text_width`.

However, I see the problem that the function loops the text char by char instead of unicode characters. I'm not sure if it can be assumed to be UTF-8.

**Comment by wm4** [comment]
It's definitely UTF-8, except when it's not. The latter could happen if an .ass file contains invalid UTF-8 sequences, but then libass doesn't need to render anything sane. But it shouldn't crash or so.
Due to the properties of UTF-8, looping by char is not a problem. If you need to skip codepoints that consist of multiple bytes, then I guess the current code structure is going to be very annoying.

**Comment by wm4** [comment]
PS: if you haven't seen it yet, ``ass_utf8_get_char`` should be useful to compute the length of UTF-8 sequences (although there are faster methods if you don't need the codepoint itself).
