### ISSUE TITLE
inaccurate rendering of shadow and border

### ISSUE THREAD

**Issue by themysciraa** [libass/libass#369]
Hi,

There is a problem where the shadow and border rendering differ from color to color. Please see the example between the blue outline text and red outline text that has the same exact styling but their border/shadow came out differently. The blue outline is closer to one edge, but the red one is centralized. Even toggling the 'scale shadow and border' option doesn't fix anything.

![My Video-151-0003](https://user-images.githubusercontent.com/49617424/73158697-f8af7600-4127-11ea-9a10-a50c40488534.png)

![My Video-151-0004](https://user-images.githubusercontent.com/49617424/73158720-0664fb80-4128-11ea-8a04-a98f3d9df930.png)

**Comment by astiob** [comment]
_Note: it’s much easier to compare images when you have one image of one thing and a separate image that shows the other thing and is otherwise identical: then you can open them in two different windows/tabs and quickly switch between them. I don’t see the difference in your screenshots, but I do indeed see it when I crop out the red line, crop out the blue line, put them in separate windows and switch between them. The red outline is indeed slightly closer to the left compared to the blue outline (when the letters’ position is held fixed)._

If your lines differ only in colour, libass currently always generates identical bitmaps that differ only in colour. This is just how it works: the colour is just a parameter that’s copied verbatim from the input into the output, and libass’s internal rendering pipeline knows nothing about it (except where colour _changes_ occur, but they don’t occur in your example; as well as a few edge cases related to the alpha component, but this doesn’t seem relevant to your example either). I’ll be very surprised if the difference you’re seeing is in fact caused by libass.

Have you checked that the colour seems to matter if you have only one line and merely change its colour? While not very likely, I could plausibly see that the shadow shifts slightly due to the position of the two lines being different, rather than the colour.

What video player are you using? What resolution? What is the video format you’re overlaying the subtitles on? Make sure you’re playing at 100% video resolution, try a 4:4:4 YUV or RGB video, or try a different player or a different rendering mode to see if it’s the player’s fault. It’s a bit hard to imagine how red and blue could be shifted out of sync, but maybe it’s caused by a quirky upsampling algorithm trying to restore 4:2:0 chroma or to upscale the image to your playback resolution.

**Comment by themysciraa** [comment]
Hi, thanks for the reply.
Whether it's a soft-sub in the video player or even after I burn it in with ffmpeg using 'subtitles filter' / 'ass filter' they all produce the same result.
https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo

here are the examples from before but I change it to the same color so they can be compared.

![My Video-151-0002](https://user-images.githubusercontent.com/49617424/73175856-76867800-414e-11ea-9def-91ab2341b7ca.png)
![My Video-151-0001](https://user-images.githubusercontent.com/49617424/73175865-7b4b2c00-414e-11ea-8d08-c3e552d18dcb.png)

**Comment by themysciraa** [comment]
sorry to add on, i tried changing it to some other colors but it seems like only red produces the problem.

please compare the red with the following examples:

RED
![My Video-151-0006](https://user-images.githubusercontent.com/49617424/73176379-9ff3d380-414f-11ea-8803-8d6f1bb3f8cf.png)

BLUE
![My Video-151-0001](https://user-images.githubusercontent.com/49617424/73176408-b9951b00-414f-11ea-8c2e-caec6c6fa299.png)

GREEN
![My Video-151-0008](https://user-images.githubusercontent.com/49617424/73176438-c7e33700-414f-11ea-8dc5-ac1c7f82f1d3.png)

PURPLE
![My Video-151-0007](https://user-images.githubusercontent.com/49617424/73176454-cfa2db80-414f-11ea-83db-cc627d4fc583.png)

**Comment by rcombs** [comment]
This is inherent to 4:2:0 subsampling, and will happen regardless of what you use to produce the image (try with the lavfi drawtext filter, for instance). Use RGB or 4:4:4 YUV if you want to avoid subsampling artifacts, or render at a higher resolution. Not a bug.

**Comment by astiob** [comment]
> This is inherent to 4:2:0 subsampling, and will happen regardless of what you use to produce the image

Is it though? I agree this is most likely not _our_ bug (the OP hasn’t provided details on the video), but I don’t see how 4:2:0 should result in red in particular shifting away from other colours. Seems like a sloppy upsampler to me.

**Comment by astiob** [comment]
@themysciraa You still haven’t told us the details of your video or your video player, but try, for example, playing your video with softsubs in the mpv player with default settings. Or, once again, find a video without chroma subsampling (“4:4:4” or “Hi444PP” or “RGB”) and try the same softsubs on that. Or tell FFmpeg to convert the video to `yuv444p` or `rgb24` before applying subtitles. You should see that the positioning of the subtitles is always the same.

**Comment by themysciraa** [comment]
>What video player are you using? What resolution relative to the video? What is the video format you’re overlaying the subtitles on?

My video is a portrait 1080x1920 mp4, and I'm playing the .ass softsub on IINA player on mac os. VLC displays the same.


>try, for example, playing your video with softsubs in the mpv player with default settings. 

Downloaded mpv player to try but it's still displaying the same problem.


>Or tell FFmpeg to convert the video to yuv444p or rgb24 before applying subtitles. You should see that the positioning of the subtitles is always the same.

This is after converting to **yuv444p** and after burning in the subtitle with ffmpeg:
![My Video-151 yu444p BLUE-0001](https://user-images.githubusercontent.com/49617424/73189222-63cc6d00-4167-11ea-8bb4-1c1f33e2d0ce.png)
![My Video-151 yu444p RED-0001](https://user-images.githubusercontent.com/49617424/73189239-675ff400-4167-11ea-879f-40aa83d67f75.png)

This is after converting to **rgb24** and after burning in the subtitle with ffmpeg:
![My Video-151 rgb24 BLUE-0009](https://user-images.githubusercontent.com/49617424/73189330-90808480-4167-11ea-8c88-6a8e058e345f.png)
![My Video-151 rgb24 RED-0001](https://user-images.githubusercontent.com/49617424/73189337-937b7500-4167-11ea-83b8-3615ea13b41c.png)

I really have no idea what's causing this discrepancy with red hue text only

**Comment by astiob** [comment]
Your yuv444p images, and your rgb24 images, are in fact identical except for the colour.

Are you looking at these images on an LCD monitor with blue-green-red subpixel order?

**Comment by astiob** [comment]
In fact, so are your original images. I should’ve looked more closely.

This is not a bug. Not ours, not FFmpeg’s, not IINA’s. This isn’t a problem with 4:2:0. This is simply how LCD subpixels work.

**Comment by astiob** [comment]
(I wrote blue-green-red earlier, but it should’ve been red-green-blue.)

You can see this by opening your images in an image viewer (or even in Microsoft Paint) and zooming in very closely. You’ll see the images appear identical, except the red one still appears to be shifted very, very slightly. And regardless of how much you zoom in, and how huge the individual pixels are, the red one always seems to be shifted very, very slightly. That’s because it is, in fact, always shifted by 1/3 of your real screen pixel (not the zoomed-in image pixel).

You can also check your display’s subpixel order on http://www.lagom.nl/lcd-test/subpixel.php (assuming it’s a simple three-subpixel display).

**Comment by themysciraa** [comment]
>This is simply how LCD subpixels work

LCD subpixel is all very foreign to me, but is there anything I can do on my side so that I can see the exact representation of the .ass subtitles styling?

>You can also check your display’s subpixel order on http://www.lagom.nl/lcd-test/subpixel.php (assuming it’s a simple three-subpixel display).

I think mine is RGB and V-RGB

**Comment by astiob** [comment]
This isn’t a software issue: if you don’t like seeing the ⅓ pixel shift on clear red/yellow/cyan/blue colours, your only option is to change your display. You can reduce the effect by using a higher-density display, an LCD with a quirky subpixel layout or a CRT display, but the only option that truly has no subpixels is probably a high-end projector (I’m not a specialist though).

**Comment by themysciraa** [comment]
Alright, I understand now. Sorry for the trouble and thank you for patiently taking the time out to explain everything in great length. I really appreciate it. Cheers
