### ISSUE TITLE
Bidi bracket matching is VSFilter-incompatibile

### ISSUE THREAD

**Issue by OmrSi** [libass/libass#374]
I opened this issue in the MPV repo and was told to ask here if anyone knows why this happens.

Using MPV, The line should show up like this:
![image](https://user-images.githubusercontent.com/20923700/75904414-d8bc5200-5e4b-11ea-8bea-9703d2da6b19.png)

But the line shows up like this:
![image](https://user-images.githubusercontent.com/20923700/75904444-e4a81400-5e4b-11ea-8f42-453d5c84967b.png)

Here is a test file:
[Test.zip](https://github.com/mpv-player/mpv/files/4288644/Test.zip)

Can anyone help me identify the problem?
Thank you.

**Comment by wm4** [comment]
Someone determined a likely cause: https://github.com/mpv-player/mpv/issues/7507#issuecomment-595380614

CC @astiob @khaledhosny

**Comment by astiob** [comment]
The new ordering is the same that I get when I copy the text from your SRT file to other programs with base left-to-right direction:

![Firefox 73](https://user-images.githubusercontent.com/515193/76027784-ea7c2300-5f39-11ea-92e3-8b4a223198aa.png)

![macOS 10.13.6 Terminal 2.8.3](https://user-images.githubusercontent.com/515193/76026379-501ae000-5f37-11ea-89bf-4262be637cca.png)

With base right-to-left direction, the _text_ is ordered as in your “old” screenshot, but the order of punctuation marks is flipped as well:

![macOS 10.13.6 TextEdit 1.13 (autodetected base direction)](https://user-images.githubusercontent.com/515193/76026386-527d3a00-5f37-11ea-8fb5-2386784b7596.png)

![Firefox 73 (explicit right-to-left base direction)](https://user-images.githubusercontent.com/515193/76027762-df28f780-5f39-11ea-8046-7ac1d0193a5d.png)

**All signs point to the new behaviour being correct for the source text.**

(Incidentally, my Word for Mac 2019 (16.29.1) screws this up even after explicitly setting right-to-left direction, possibly due to a lack of some Middle East–specific modules:
![Microsoft Word for Mac 16.29.1 (2019)](https://user-images.githubusercontent.com/515193/76027472-5742ed80-5f39-11ea-9817-2a4c0fba0c73.png)
I tried to switch the text’s language to Arabic to see if it would help, but it just ignores me and keeps whatever European language it happened to detect based on things like my keyboard layout.)

**Comment by astiob** [comment]
As for the base text direction, unfortunately the default has to be left-to-right in libass for compatibility with the DirectVobSub/VSFilter family of subtitle renderers. But you should be able to override it in mpv, I think:

```
--sub-ass-force-style=Encoding=-1
```

If we get that new “make this text look right” flag from #372, we may use it to default to autodetected base direction to improve the rendering in cases like this when we’re actually getting SRT-disguised-as-ASS as input rather than true ASS.

**Comment by OmrSi** [comment]
That's strange.
Any text editor on windows shows the text this way, and that is correct because I wrote it that way and just reversed the punctuation marks so it shows up correctly on the video player.
Notepad, Notepad++, VLC, and MPC all show it this way.
![image](https://user-images.githubusercontent.com/20923700/76028557-83f80480-5f3b-11ea-8a62-8d88c4738527.png)
![image](https://user-images.githubusercontent.com/20923700/76028566-8bb7a900-5f3b-11ea-8a39-e06d434adffb.png)

The original line is:
```
"(الظاهرية)، (جنوب الخليل)،
السلطة الفلسطينية"
```

If you use a Unicode control character to set it, you'll have:
```
‫"(الظاهرية)، (جنوب الخليل)،
‫السلطة الفلسطينية"
```
And it should show up the same way when you reverse the punctuation marks.
It used to, but now it's not.

For example, this it RTL `(مارثا) ماذا؟` and this is reversed to work in LTR `مارثا) ماذا؟)`.
This is how the one written in RTL used to show up:
![image](https://user-images.githubusercontent.com/20923700/76029388-07662580-5f3d-11ea-85b7-5b479bf9b09b.png)

Which is correct, because it's not reversed and that's the order I wrote it in.

This is how it shows up now:
![image](https://user-images.githubusercontent.com/20923700/76029410-10ef8d80-5f3d-11ea-92c5-e267de65c6a6.png)

But they both show up correctly after reversing:
![image](https://user-images.githubusercontent.com/20923700/76029459-31b7e300-5f3d-11ea-9adb-7bd0dd83377e.png)

 
I'm using "mpv-1.dll" inside a translation program, I don't think I can override it.

So, as an Arabic user, I think the old behavior was correct.

**Comment by astiob** [comment]
I’m not a specialist, but it seems that your Windows programs are not matching the parentheses as prescribed by the Unicode bidirectional text algorithm since version 6.3, which is now _6.5 years old._ (In retrospect, this should have been obvious when it was mentioned that the behaviour changed with the libass commit that enabled this in libass.)

Look at what you just posted:
![A screenshot of your last comment showing the Firefox rendering of the text that follows the Unicode 6.3+ bidirectional algorithm with bracket matching.](https://user-images.githubusercontent.com/515193/76037112-a9dad480-5f4e-11ea-8867-ded441eb8ac4.png)
I don’t know which Web browser you’re using, but I’m willing to bet it looks like this in any modern browser.

This isn’t something we decide, something you decide or something any arbitrary person decides. Unicode is a major standard—_the_ standard for text processing. It’s only right to adhere to it to ensure interoperability with other programs and user expectations. It is indeed unfortunate that this case seems to have been changed incompatibly in Unicode 6.3, but seeing it now, it absolutely makes sense and improves the algorithm for the future: you have two words/phrases in parentheses, and all of this is embedded into a left-to-right context, so you get the two parenthesized clauses in the same order in which they appear in the file (الظاهرية comes first in your file and جنوب الخليل comes second), and within each pair of parentheses the text is right-to-left.

Like I mentioned, fundamentally this is caused by the base direction being left-to-right. This is the same reason you had to change your punctuation marks.

**But since you’re the script author, there’s a workaround:** add an explicit Unicode RTL override character to the beginning of your line. If I’m not mistaken, your text should then render correctly, right-to-left from start to finish, in both libass and VSFilter.

**Comment by OmrSi** [comment]
Okay, if that's how it is, that's how it is.
Thank you.

**Comment by astiob** [comment]
I’d like to add that it’s safer to add an explicit embedding character and write the text in proper logical order, than to move around the punctuation marks just to make the text look right (at least in SRT). Like I mentioned above, we may later consider enabling base direction autodetection for formats other than ASS, which would cause your punctuation to display in the wrong order. And SRT probably has renderers other than libass and VSFilter, and they may well apply autodetection already. By including an explicit embedding character, you can rely on the text flowing in the desired direction in all renderers, and you can type in (or paste in) the text naturally without having to think about where you need to swap punctuation marks.

Just don’t include any rich text formatting in the middle of your right-to-left lines, because, unfortunately, VSFilter doesn’t handle that correctly at all. libass and VSFilter currently handle that completely differently, and while libass may in the future move towards emulating VSFilter for this case, VSFilter’s behaviour won’t ever change. If you’re writing ASS, it’s fine to make the entire line bold, for example, but if you try to make the first half regular and the second half bold, things will break. If you should ever really want to do that, you’ll need to reorder your text manually and make generous use of Unicode bidirectional control characters: what you want to achieve is that each half is an individual right-to-left embed and there’s a left-to-right mark between them (or equivalent) such that the second embed is laid out to the right of the first one.

**Comment by OmrSi** [comment]
It is, but some translators still use ANSI and that's why you can't use a Unicode character.
I know they should use UTF, but some servers with old versions cause issues when merging a file with UTF encoding, or that's at least what they tell me.

And we don't use tags inside the text for that reason, you'd have to reverse the order of the words.
MPV shows them in the correct order but other players don't.
For example, here it is with libmpv:
![image](https://user-images.githubusercontent.com/20923700/76040984-a3058f00-5f59-11ea-9eb5-f84c6d7a8e5f.png)

MPC:
![image](https://user-images.githubusercontent.com/20923700/76041087-e65ffd80-5f59-11ea-8471-9de920b32f37.png)


And the merging always shows up like it is on MPC, so we have to order the text for it to show up correctly on MPC.

**Comment by astiob** [comment]
Yep, that’s what I was referring to. If you can get your files to use Unicode, you can work around that with some bidi control character magic as I mentioned. Your goal is to use bidi controls to make libass (and other programs) order the text the same way it’s ordered in VSFilter (MPC). It will still require the reordering, but the text should then look the same in all players and you should be able to use tags.

Being unable to use Unicode sounds strange, to be honest. Maybe you can try and see what happens? UTF-8 is often _the only_ supported encoding nowadays, and I think this is even true for ASS in some cases, but I can’t name them off the top of my head.

If you’re using the Windows-1256 code page, you can add character 0xFE, the right-to-left mark, to the beginning _and_ end of your line. I’m not sure if this will _always_ be enough, but it is enough to force your ‏،(الظاهرية)، (جنوب الخليل)"‏ line to render purely right-to-left.

**Comment by OmrSi** [comment]
Yeah, it's already available in the program, and I use it for files that I want to merge myself.
![image](https://user-images.githubusercontent.com/20923700/76042271-f62d1100-5f5c-11ea-8f36-be59e49918e2.png)

But I can't use it on files I upload in Subscene.
The issue was only in previewing the subtitle inside SE which used libmpv.

I did not know about 0xFE, though. I'm gonna have to check it out.

**Comment by OmrSi** [comment]
BTW, the "Reverse RTL start\end" shown above is the one most used among Arab translators.
They even write it reversed themselves when translating sometimes.

**Comment by OmrSi** [comment]
I don't know why they say UTF doesn't work properly.
I would love to just use it, ANSI is too old.

**Comment by astiob** [comment]
Also, if you’re going to convert the sample that started this discussion to ASS, you can force the new/correct ordering in VSFilter/MPC by inserting an effectively meaningless ASS override tag between the two parenthesized words/phrases. For example, `{\2a&H1}` to change the karaoke alpha but not actually use any karaoke.

**Comment by OmrSi** [comment]
I don't want to force the new ordering, as it is not right in my language.
I want it to show up on video as it shows up in the test box on windows which is the correct form and it already shows up like that on MPC.
And it's obvious that it's correct because it shows up that way when using a Unicode control character.
libmpv using a Unicode control char:
![image](https://user-images.githubusercontent.com/20923700/76099322-96be1800-5fd3-11ea-8493-990d08f3a9d0.png)

MPC using normal reverse:
![image](https://user-images.githubusercontent.com/20923700/76099402-b9503100-5fd3-11ea-8e02-24c4e38a677e.png)

Even if the new way is correct in principle, it is not correct for my language and the order I want.

**Comment by OmrSi** [comment]
More to the point, shouldn't it also show these two reversed if it doesn't treat the text as one part?
![image](https://user-images.githubusercontent.com/20923700/76099948-94a88900-5fd4-11ea-9c2e-2459242fee0d.png)

Also, I'm already using the latest version of Windows 10, so I guess we'll see if this changes in the future.

**Comment by astiob** [comment]
We’ve been through that already. **All ASS text is left-to-right by default.** This _is_ the correct behaviour _for left-to-right text._ You can test this in any other modern program that doesn’t rely on Windows’ built-in text rendering. (Even in _Edge,_ which is now based on Chromium.) You are already applying a workaround to make it look better, so clearly the behaviour _is not right_ for your language, and that’s absolutely true—what you really want is for the entire line to be right-to-left, but for very unfortunate historical reasons ASS doesn’t let you do that. _Neither_ behaviour is right for your language.

I’m offering you a workaround. It’s your choice to reject it, but this is a chance to get your file to display the same way in both VSFilter and new-libass-with-new-fribidi.

I’ve already offered another workaround, which I still think is better: force right-to-left ordering through bidirectional control characters (whether Unicode or Windows-1256). It allows you to write natural Arabic without worrying about reordering and cross-platform compatibility. You should totally try to submit Unicode to that website and use Unicode bidi controls if it works or that Windows-1256 FE right-to-left mark if it doesn’t.

But if for any reason you should be unable to use the workaround with control characters, I’m now merely providing another suggestion that is _worse,_ yes, but equally effective: embrace the left-to-right order since you can’t do anything about it, but force VSFilter to use the ordering consistent with the _new_ Unicode bidi algorithm (ironically, by using the very quirks that prevent you from having pure right-to-left text in ASS in the first place).

If you keep your current text with only the outermost punctuation marks swapped, I fully expect that your file _will_ break in some new version of Windows when Uniscribe finally switches to the Unicode 6.3+ bidi algorithm. In fact, if you run VSFilter in Wine, you should already see it break because Wine has been using Unicode 6.3+ bidi for years, judging by some Wine release notes that I see on the Web. Force it to be the new order now, and your file will be future-proof _and_ compatible with (new) libass. Better yet, force it to use right-to-left order, and your file will work correctly in _all_ renderers, new and old.

> More to the point, shouldn't it also show these two reversed if it doesn't treat the text as one part?

There are no parentheses/brackets here. The entire line is a single right-to-left piece. It is still embedded in a left-to-right context, but you don’t notice this because you have identical quotation marks on both ends.

I tried to explain above why the Unicode 6.3 algorithm makes more sense, but maybe it will be clearer with pictures:

![Unicode 6.2 rendering](https://user-images.githubusercontent.com/515193/76102127-32518780-5fd8-11ea-8db8-c069ce441637.png)
Unicode 6.2 lays out the line left-to-right because that’s what ASS tells it to do. It then sees some Arabic text, selects all of the Arabic plus all intermediate punctuation and flips the order of that part. So, it thinks you have an English (for example) paragraph mentioning, in parentheses, the Arabic text “الظاهرية)، (جنوب الخليل”. That’s what you’re calling “right”.

![Unicode 6.3 rendering](https://user-images.githubusercontent.com/515193/76102133-34b3e180-5fd8-11ea-8712-14f4576a6548.png)
Unicode 6.3 lays out the line left-to-right because that’s what ASS tells it to do. It then sees two pairs of parentheses and figures that you have an English (for example) paragraph mentioning two things, each in parentheses. Then it notices that each of these two things is written in Arabic, so it flips each of them to be right-to-left.

**Comment by astiob** [comment]
Oh, better yet, rather than an ASS override tag, you can insert a left-to-right mark in the middle of the line, which will make old libass (and new libass with old fribidi) display it similarly as well. But if you can use direction marks, then you may as well use right-to-left marks to force the whole line to be right-to-left.

**Comment by astiob** [comment]
@libass/developers We do have to consider, though, whether we want to keep the old behaviour intentionally for VSFilter compatibility. I don’t think it makes sense for SRT, OSD UI or other not-really-ASS sources. But for ASS… we might have to. Here we have one person noticing the difference and reporting it to us. There are probably many more who will stay silent, and existing scripts probably already rely on this. 😩 Of course, we’re already VSFilter-incompatible for right-to-left text with override tags, but IIRC the consensus was that we should actually “fix” that when we realized it’s actually possible and not terribly costly.

**Comment by astiob** [comment]
For more insight on why the Unicode bidi algorithm was changed and the new one is better, consider examples such as [this](https://github.com/microsoft/vscode/issues/78867).

**Comment by wm4** [comment]
mpv and ffmpeg are probably the only things that render SRT via libass. mpv sets ASS_Style.Encoding=-1, which I think should fix the initial direction? But for some reason it doesn't do that for SRT. ffmpeg leaves Encoding at 0 too.

I'm very much interested in this, but I don't understand it, and I'm mentally too disconnected from it to get into it now.

**Comment by astiob** [comment]
Yes, I think Encoding=-1 should fix the initial direction. Or well, it enables autodetection, which hopefully is strong enough to fix it. Of course, the actual success will depend on the content of the line; I’d assume FriBiDi does something like “find the first strongly-directional character in the line and assume that’s the line’s base direction”. So an Arabic line that mentions an English word and accidentally happens to start with it might get misdetected… but I’m not sure.

If it set that for other things but not for SRT, that’s kinda odd. Could it again be for compatibility with Windows players that use VSFilter to render SRT?

I recall a discussion on IRC about which Encoding to use for something in FFmpeg… I don’t recall what we decided.

Keeping the new bidi algorithm when Encoding is -1 is probably a good idea. Keeping it regardless of Encoding when we receive a flag that the ASS is not real ASS, too.

But should we explicitly disable it for real ASS with real VSFilter-compatible Encoding, to get ordering similar to VSFilter’s?

**Comment by rcombs** [comment]
Yeah, I'd say that the same thing applies here as with any other VSFilter incompatibility for real ASS: any difference that could reasonably be relied upon by existing scripts is our bug, and we should fix it. If we want to add a new flag for "opt-in to the new libass-only Unicode-compliant bidi behavior", that's fine, but existing scripts built for VSFilter should continue to render as intended.

**Comment by astiob** [comment]
Keeping in mind that we currently fail to match VSFilter’s bidi when any nonvacuous override tags are involved regardless of this change, and that we don’t _yet_ have that delicious “not-really-ASS” flag, shall we disable the new Unicode bidi right away or delay it indefinitely until someone steps up to implement VSFilter-compatible override tag bidi, or just until we get the not-ASS flag?

**Comment by realfinder** [comment]
yes, override tags incompatibility with VSFilter since years with no fix https://github.com/libass/libass/issues/71#issuecomment-62388166

is it because libass render glyph by glyph not a "chunk of text" together? as it here https://code.google.com/archive/p/libass/issues/114 and https://github.com/libass/libass/issues/148

**Comment by realfinder** [comment]
![Untitled](https://user-images.githubusercontent.com/2512153/77393549-5077ff80-6dae-11ea-9f2a-d8e1f7a2c0ea.png)
here with windows notepad (left to right)
![image](https://user-images.githubusercontent.com/2512153/77393651-87e6ac00-6dae-11ea-8c71-921164fbb941.png)
and here right to left

**Comment by astiob** [comment]
I’m re-testing this in connection with #441, and I’m baffled because VSFilter actually gives me this:

![At the left end of the first line, I see a right-parenthesis, instead of a left-parenthesis.](https://user-images.githubusercontent.com/515193/110251849-39b0c580-7f8b-11eb-9568-e540f086e553.png)

Any idea what I’m doing wrong and/or why it’s behaving like this?

**Comment by OmrSi** [comment]
@astiob This is actually a known issue, at least for Arabic subtitlers, we usually replace `،(` with `،)` before publishing the file.
I think the Arabic comma has some weird effect on the parenthesis.

By the way, I never did thank you for fixing the original issue, so thank you. :)

**Comment by realfinder** [comment]
for me it's
![image](https://user-images.githubusercontent.com/2512153/110252629-5b17ae80-7f97-11eb-898a-9a8ca0250a38.png)

**Comment by OmrSi** [comment]
@realfinder It seems to happen after I replace `،(` with `،)` which means that MPV is correct in showing it this way because it is reversed. But MPC shows it correctly even when reversed.

This is replaced: [Test_Replaced.txt](https://github.com/libass/libass/files/6097867/Test_Replaced.txt)
MPC:
![image](https://user-images.githubusercontent.com/20923700/110253550-a16b0e80-7f93-11eb-985d-df647c8d6666.png)

MPV:
![image](https://user-images.githubusercontent.com/20923700/110253561-b182ee00-7f93-11eb-9c82-ec782d4ebcbd.png)

This is not replaced:  [Test_Replaced.txt](https://github.com/libass/libass/files/6097874/Test_Replaced.txt)
MPC:
![image](https://user-images.githubusercontent.com/20923700/110253574-be9fdd00-7f93-11eb-805c-ede2d708d39f.png)

MPV:
![image](https://user-images.githubusercontent.com/20923700/110253578-c8294500-7f93-11eb-9878-8aff49890ce9.png)

**Comment by astiob** [comment]
The two files you uploaded seem to be the same. Mistake?

**Comment by astiob** [comment]
@realfinder Could you post the whole MKV, or at least the whole subtitle file together with the font? Or if you’re just using the SRT from the original report at the start of this thread, what font are you using? Also: what version of Windows are you on?

**Comment by realfinder** [comment]
> 
> 
> @realfinder Could you post the whole MKV, or at least the whole subtitle file together with the font? Or if you’re just using the SRT from the original report at the start of this thread, what font are you using? Also: what version of Windows are you on?
I am just use avs with
```
ColorbarsHD()
converttoyv12
textsub("Test.srt")
```
with this https://github.com/mpv-player/mpv/files/4288644/Test.zip
tested in winxp and also win server 2019 and win10 20H2

**Comment by OmrSi** [comment]
@astiob Yes, sorry. Fixed now.

**Comment by astiob** [comment]
I get this on Win10:

![arabic-win10-arial](https://user-images.githubusercontent.com/515193/110255201-260d5b00-7f9b-11eb-829a-9f318b1bd5e9.png)

and this on Win7:

![arabic-win7-arial-204](https://user-images.githubusercontent.com/515193/110255208-2d346900-7f9b-11eb-870d-f7bc59f595f0.png)

(Changing the Encoding to DEFAULT (1) has no effect.)

> tested in winxp and also win server 2019 and win10 20H2

It doesn’t surprise me that 2019 behaves the same as 10, but XP?…

I’ve just tried changing my Win7 regional settings to Arabic to check if that has an effect, but it made no difference. Although I didn’t reboot.

**Comment by realfinder** [comment]
yes, in win7 it's
![image](https://user-images.githubusercontent.com/2512153/110256705-6248b780-7fab-11eb-8c4a-7563c07e368f.png)
