### ISSUE TITLE
Fractional font sizes possibly handled differently from vsfilter

### ISSUE THREAD

**Issue by petzku** [libass/libass#420]
In short, vsfilter (at least on MPC-HC) seems to just truncate the fractional part from font sizes, while libass doesn't.

The following ASS snippet demonstrates this. The white rectangle is scaled to exactly enclose the text with `\fs24.5` in Aegisub.
```
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an5\bord0\shad0\blur0\fscx1134\fscy99\p1\pos(624,662.422)}m 0 0 l 100 0 100 100 0 100
Dialogue: 1,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\fs24.5\bord2\shad0\fnArial\pos(624,709.312)}"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\an5\bord0\shad0\blur0\fscx1134\fscy99\p1\pos(624,554.422)}m 0 0 l 100 0 100 100 0 100
Dialogue: 1,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\fs24\bord2\shad0\fnArial\pos(624,601.312)}"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
```

vsfilter (mpc-hc v1.9.6 stable from https://github.com/clsid2/mpc-hc/releases): 
![image](https://user-images.githubusercontent.com/5639335/88724667-944f8c80-d133-11ea-855f-86369871f62a.png)

libass (mpv v0.32.0-201-ge7bab0025f):
![image](https://user-images.githubusercontent.com/5639335/88724858-dd074580-d133-11ea-885c-2938e75255f0.png)

Interestingly, in both Aegisub v3.2.2 and r8992-master-d9bd7de, the vsfilter renderer produces the same output as mpv.

**Comment by astiob** [comment]
MPC-HC doesn’t read float \fs and truncates the value, as you saw. xy-VSFilter reads the full fractional value since Cyberbeing/xy-VSFilter@404301a33f40978526382e69777d9e6a864edd65 (July 2012) (as you also saw in Aegisub). libass does this because
* this intuitively makes sense, and renderers have steadily shifted towards supporting fractional values in all kinds of override tags (FWIW, even Threaded VSFilter supported fractional \fs);
* libass has done this since 66bfd7d69de30db9ad56e3b9ca92c967d22ab13b (May 2007);
* xy-VSFilter has historically been dominant and does this (while MPC-HC is the only renderer that doesn’t do this and has historically been avoided by fansubbers due to other rendering issues that it used to have), so it seems more likely that a file uses fractional \fs intentionally and appears badly in MPC-HC than it is that a file uses fractional \fs by accident and appears correctly only in MPC-HC. (The fact that libass has supported this since 2007 further helps this point, as even the very rare subtitles made for libass want fractional \fs.)

It seems to make little sense to revert libass’s support for fractional \fs at this point. Rather, MPC-HC should add support for it.
