### ISSUE TITLE
Improve score-based font selection and faux-bold behavior

### ISSUE THREAD

**Issue by rcombs** [libass/libass#437]
- We should match the score system described here: https://github.com/libass/libass/pull/362#issuecomment-705885810
- An additional caveat: if fsSelection bit 5 is set, faux-bold will never occur, and the font will not receive the 120-weight-point-equivalent score bonus for it
- Whether or not a font is italic (for the purposes of both faux-italic and scoring) is determined entirely by fsSelection bit 0 (ITALIC), whereas freetype also uses bit 9 (OBLIQUE)

Today someone ran into a font (Bona Nova) which has its regular variant at weight=300 and its bold at weight=400, with regular having fSelection=REGULAR and bold having fSelection=BOLD. This means that at \b400 the bold variant is selected, but at \b700 the _regular_ variant is selected, as the 120-point simulated-bold bonus pushes it closer to the requested weight than 400…
<img width="444" alt="image" src="https://user-images.githubusercontent.com/819638/96464191-26c07300-11ed-11eb-8849-4e52cf32dc70.png">
except that it doesn't seem to actually get faux-bolded in the output???? I'm not sure why that is. It seems like the glyph metrics are affected, but not the actual shapes:
<img width="322" alt="image" src="https://user-images.githubusercontent.com/819638/96464419-6a1ae180-11ed-11eb-9b2e-2cc4d2899782.png">
…which probably means our emboldener is handling at least some cases wrong, since afaik we never touch metrics. I'm not completely sure what's going on here. Seems like Windows's emboldener either adjusts metrics or adjusts glyph forms, but not both??? This part needs further investigation.

Simpler VSFilter demo of the matching behavior; \b600 matches the Regular variant with faux-bold (400+120=520, which is a closer match for 600 than 700 is).
<img width="391" alt="image" src="https://user-images.githubusercontent.com/819638/96464257-3770e900-11ed-11eb-987e-5a61e736f5b4.png">

For a font family that contains a weight=700 variant with fsSelection=BOLD, `\b900` gives the same result as `\b700` (vs in libass, where `\b900` results in faux-bolding the bold). This is likely a regression in ac75f67697845efc1b0a15693c96dcc9e0f71518; we need to check _both_ conditions.

**Comment by astiob** [comment]
Probably related is #305, where Fansub Block doesn’t seem to get faux-bolded, much like Bona Nova in your sample. No idea whether its metrics change though.

**Comment by astiob** [comment]
> This is likely a regression in [ac75f67](https://github.com/libass/libass/commit/ac75f67697845efc1b0a15693c96dcc9e0f71518); we need to check _both_ conditions.

Should we sneak a fix for this in 0.15.0?

**Comment by astiob** [comment]
> …which probably means our emboldener is handling at least some cases wrong, since afaik we never touch metrics. I'm not completely sure what's going on here. Seems like Windows's emboldener either adjusts metrics or adjusts glyph forms, but not both??? This part needs further investigation.

Another weird case I’ve just stumbled upon: `{\b600}Verdana`, which gets Regular + faux bold as per the OP, somehow gets slightly _narrower_ metrics than Regular itself:

<img width="640" alt="A screenshot shows \b600 being slightly narrower than \b400, which in turn is much narrower than \b700." src="https://github.com/libass/libass/assets/515193/d455a763-45b7-450c-ab9f-e7c48ab2aad1">

**Comment by astiob** [comment]
As for a possible decision source for shapes vs metrics, could it be related to TrueType vs CFF? Is the emboldening implemented in GDI’s core or in each font format driver separately?

**Comment by rcombs** [comment]
It's separate for each format driver. The TrueType driver seems to do some very screwy stuff around bitmap-level emboldening; some of it might be conditional on the presence of an HDMX table. A lot of it expects to be emboldening by exactly 1 pixel, which is probably near-imperceptible at the kind of resolutions we're using here; what do you see if you layer a single glyph from Veranda on top of its emboldened version in a different color?

**Comment by astiob** [comment]
> what do you see if you layer a single glyph from Verdana on top of its emboldened version in a different color?

<img width="640" alt="" src="https://github.com/libass/libass/assets/515193/b0e14e8b-10cd-4e7f-97ee-908dc796db29">

The centre of the emboldened glyph seems to be offset to the right compared to the centre of the regular glyph: there’s a narrow black band on the left and a wide white band on the right. The shape seems thicker along both axes, but vertically it’s a mixed bag: the bottom edge of the glyph seems aligned, but the top part of `I` seems to be thicker _towards the centre._

**Comment by rcombs** [comment]
What about with multiple sizes, and how does fscx/y play into this? If my understanding is correct, the offsets should be by the same number of pixels regardless of size, but I have no idea what fsc will do to it.

**Comment by astiob** [comment]
Curiously enough, this doesn’t happen to Verdana Pro (in its TrueType form), which gets thicker shapes and keeps its metrics unchanged.

And when I try an OTF variant of Verdana Pro, it just gets spaced out and the shapes don’t seem any different. So I do think that part is driver/format-related. (But Fansub Block in #305 is a TTF.)

> What about with multiple sizes, and how does fscx/y play into this?

After trying fsc 25, 50, 100, 200, 400 while keeping the apparent size constant, the only difference I’m seeing is in what seems to be vertical hinting. The exact boundaries of the white zone in the screenshot above move slightly up and down, but the amount seems unchanged, and the horizontal extents stay unchanged and don’t even move, including the small black bar on the left. So it doesn’t seem to be a fixed number of GDI pixels.

**Comment by astiob** [comment]
> the horizontal extents stay unchanged and don’t even move

OK, some of them do move _slightly,_ and e. g. the “600” seems to shift just a bit to the right. But the amounts/areas stay the same.

**Comment by moi15moi** [comment]
Here is currently a pseudo-code of the algorithm rcombs found (currently, it is what #678 implemented)
```py
get_similarity_score(font_face: FontFace, requested: AssStyle) -> int:
	score = 0

	if requested.italic and not font_face.is_italic:
		score += 1
	elif not requested.italic and font_face.is_italic:
		score += 4

	weight_compare = font_face.weight
	if requested.weight > font_face.weight + 150 and not font_face.is_glyph_emboldened
		weight_compare += 120

	score += (73 * abs(weight_compare - requested.weight)) // 256

	return score
```

If the font has a microsoft cmap, then
| Property            | Font table               |
|---------------------|--------------------------|
| weight              | os2->usweightclass       |
| is_glyph_emboldened | os2->fsSelection (bit 5) |
| is_italic           | os2->fsSelection (bit 0) |

If the font doens't have microsoft cmap, but has a roman macintosh cmap, then
| Property            | Font table                                                    |
|---------------------|---------------------------------------------------------------|
| weight              | head->macStyle (bit 0). If set, then weight = 800, if not 400 |
| is_glyph_emboldened | head->macStyle (bit 0)                                        |
| is_italic           | head->macStyle (bit 1)                                        |


**But, I did some test and I think I found another condition.**

### Test 1
**requested_font**
italic = false
weight = 400

available_font_1 (Alivia.otf)
italic = false
weight = 400
opentype
score = 0 (I used the previous algorithm to calculate this)

available_font_2 (AliviaRegular_Weight31961.ttf)
italic = false
weight = 31961
truetype
score = 8999 (I used the previous algorithm to calculate this)

**Result**
Always display available_font_2 regardless of the order of installation, but based on the score, it should have been available_font_1.
This means that we don't have the right score for one or even both available font.


### Test 2
**requested_font**
italic = false
weight = 400

available_font_1 (Alivia.otf)
italic = false
weight = 400
opentype
score = 0 (I used the previous algorithm to calculate this)

available_font_2 (AliviaRegular_Weight31962.ttf)
italic = false
weight = 31962
truetype
score = 9000 (I used the algorithm of rcomb to calculate this)

**Result**
When I install available_font_1, then available_font_2, it shows available_font_1.
But when I install available_font_2, then available_font_1, it shows available_font_2.
My conclusion is that the fonts have the same score because with some other test, I realised when the font have the same score, GDI will show the first one it has been installed.

### Conclusion
If we add a 9000 to the score when the font has opentype outline, then it explain why on the Test 1 it show available_font_2 and for the Test 2, it shows different font depending on the installation order.

Here are the font file: [Truetype VS Opentype.zip](https://github.com/libass/libass/files/14158686/Truetype.VS.Opentype.1.zip)

**Comment by astiob** [comment]
Thanks for putting this up here. But I believe we concluded the reason was different when we previously discussed this elsewhere:

[Old Microsoft docs](https://learn.microsoft.com/en-us/previous-versions/ms969909%28v=msdn.10%29?redirectedfrom=MSDN) say a penalty of 9000 (matching your tests) is applied if:

> Requested a family, but the candidate's family is different.

You’ve mentioned that the fonts in your tests do, in fact, have different families:

> But, they don't have the same `LOGFONT.lfPitchAndFamily` when we enumerate the font with `EnumFontFamiliesExW`!
>
> For the truetype one, there are: `VARIABLE_PITCH | FF_DONTCARE`
> And for the opentype one, is it: `VARIABLE_PITCH | FF_MODERN`

VSFilter requests family `FF_DONTCARE`, but in its infinite wisdom, GDI apparently replaces it by a specific default family when it computes the penalty instead of completely ignoring it. Specifically, it seems to replace a requested `FF_DONTCARE` by `FF_SWISS` when comparing to fonts whose registered family isn’t itself `FF_DONTCARE`. So in your case, the TrueType font has `FF_DONTCARE`, so it matches exactly, but the CFF font has `FF_MODERN`, so the requested family is turned into `FF_SWISS` and a mismatch results.

Each font’s `lfPitchAndFamily` is provided by the respective font driver. The TrueType driver infers it from PANOSE fields in the OS/2 table, and the logic might even vary depending on the selected charset. The CFF driver is Adobe’s and (to my knowledge) doesn’t have anywhere near as much information available on it, but we’ve known it to behave differently in various situations, from font name extraction to faux bold generation. It just seems this is yet another one of those situations, which explains why your two fonts get different family values.

> To me, it makes sense that GDI prefers truetype font over opentype font because [VSFilter](https://sourceforge.net/p/guliverkli2/code/HEAD/tree/src/subtitles/RTS.cpp#l46) uses [OUT_TT_PRECIS](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-logfontw) and the microsoft doc says: Instructs the font mapper to choose a TrueType font when the system contains multiple fonts with the same name.

This macro name and documentation likely predate OpenType by several years, so I think it’s probably simply a misnomer and OpenType fonts are actually included in the “TrueType” concept as used here. I assume that this macro distinguishes SFNT/OpenType/TrueType (pick your name) fonts from PostScript (Type 1) fonts. Note how the table only mentions “TrueType fonts” and “PostScript fonts”. OpenType is an extension of TrueType, after all. The note below the table also sounds like it gives an exhaustive list of options: device fonts, raster fonts, Type 1 fonts or `OUT_TT_PRECIS`.

That said, I haven’t been able to find a quick confirmation that `OUT_TT_PRECIS` even does _anything at all._

Well, all of this can presumably be verified experimentally by taking a CFF OpenType font, checking its `lfPitchAndFamily`, converting it to TrueType and doctoring its PANOSE table to produce the same `lfPitchAndFamily` (or even finding an independent TrueType font that already has the desired `lfPitchAndFamily` and doctoring its name table instead). Then, we’d just check whether the font choice is stable or both fonts can be selected depending on installation order, and if it is in fact stable, reconfirm the exact penalty by adjusting the weight of the selected font.

**Comment by moi15moi** [comment]
> The TrueType driver infers it from PANOSE fields in the OS/2 table, and the logic might even vary depending on the selected charset.

Thank for pointing that out!
I tried to find how GDI set lfPitchAndFamily of the LOGFONT for **truetype** outline font.
Here are my conclusion
```
# The charset doesn't impact this logic, BUT I don't have many font with different charset, so I haven't been able to test all of them.
# I haven't found any font with DEFAULT_PITCH
if post->isFixedPitch:
	pitch = FIXED_PITCH
else:
	pitch = VARIABLE_PITCH


if os2->panose->bFamilyType == 4:
	family = FF_DECORATIVE
else if os2->panose->bFamilyType == 3:
	family = FF_SCRIPT
else if os2->panose->bProportion == 9:
	family = FF_MODERN
else if os2->panose->bSerifStyle in [2, 10]:
	family = FF_ROMAN
else if os2->panose->bSerifStyle in [11, 15]:
	family = FF_SWISS
else:
	family = FF_DONTCARE
```

``Alivia.otf`` (I shared it in my previous message) and [this new font](https://github.com/libass/libass/files/14159461/Truetype.zip) seems to have the same score since GDI always display the first one that have been installed.

So, in brief, GDI clearly use the family from the panose in the score matching.
