### ISSUE TITLE
\fscx0 or \fscy0 with \bord should affect layout but have no border

### ISSUE THREAD

**Issue by MatiasMovie** [libass/libass#443]
Karaoke not working well in this sub, on xysubfilter working well
https://cdn.discordapp.com/attachments/729859556536221699/770786260717011025/wqrw.ass

**Comment by astiob** [comment]
Wow, that’s a pretty libass-hostile script.

First, it contains \fscx0 and \fscy0, which break rendering in libass as per #185.

Second, within those \fscx0 and \fscy0 (one at a time) lie vector drawings with nonzero \bord, which VSFilter doesn’t draw a border for as they have no pixels (due to the \fscx0 or \fscy0). So in addition to @MrSmile’s fix for #123 that will drop 2-point contours, we also need to avoid stroking anything with \fscx0 or \fscy0.
