### ISSUE TITLE
Rename ass_directwrite_add_provider

### ISSUE THREAD

**Issue by rcombs** [libass/libass#464]
Apparently Aegisub has been hijacking this internal symbol for some time: https://github.com/Aegisub/Aegisub/commit/e5a6abd21595bb098f0de06f5cdaab75ede3edff#diff-3fc0b36a8fa80dec571e79d4eaa54b6cb2e9380cdb9eb309a45d84ed0ba5e9e9R105

This makes it pretty difficult to tell what's going on when users report font issues. I'd suggest renaming the symbol so users get the behavior we actually have control over, and implement functionality that people actually want out of this ourselves. Going by the commit message, the main thing here is disabling glyph fallback, which is already discussed in #78.

**Comment by astiob** [comment]
I’m not sure I follow: how will renaming the symbol help?

As I mentioned in another issue, I believe the Aegisub commit’s main goal is to have a GDI font provider, and therefore support Windows XP without Fontconfig, while the “desirability” of disabling font fallback is just a justification for failing to implement it. (Difficulties with GDI font fallback may or may not have been a reason why we didn’t make a GDI font provider in libass to begin with.) I say this for two reasons:

1. The commit’s title focuses on GDI, not on disabling fallback.
2. If all that was desired was lack of fallback, a whole new font provider technology would not have needed to be used.

But, of course, only @tgoyne knows for sure.

**Comment by rcombs** [comment]
They inject the GDI provider (and override the DirectWrite one) by reimplementing `ass_directwrite_add_provider` within the main executable.

**Comment by astiob** [comment]
Sure, but… what will we achieve by renaming it? Break their build for a few moments? 🤷‍♂️

**Comment by rcombs** [comment]
Their build should be fine with it renamed, just, the override symbol would never get called, and thus wouldn't do anything, so we'd have libass behaving in a supportable way in aegisub on windows again.

**Comment by tgoyne** [comment]
IIRC I had two main goals for the GDI fontmatcher: XP support (which is super obsolete in 2020), and to be doing something as similar to VSFilter as possible. I had the vague hope that bundling the fonts picked by GDI would result in the correct fonts being used everywhere because non-VSFilter renderers would have the ability to prioritize bundled fonts over system fonts and hopefully viewers would not have any installed fonts which were better matches according to GDI than the bundled fonts.

Disabling font fallback was mostly a nice bonus and an excuse to implement less.

**Comment by astiob** [comment]
If you want Aegisub and Kainote to stop using a custom font provider, why not ask them nicely and/or submit PRs?

If they want to keep using a custom font provider, what’s stopping them from renaming their overriding symbol?

And yes, it will break the build, at least for Aegisub, as its libass subproject does not compile `ass_directwrite.c` (otherwise it would clash with the custom function) but defines `CONFIG_DIRECTWRITE`. And if they were to undefine `CONFIG_DIRECTWRITE`, Aegisub libass would stop loading fonts entirely except those embedded in the ASS (if Aegisub passes them through), as no other system font provider is enabled (as the commit preceding the GDI one disables Fontconfig, which makes sense). Or if they were to add `ass_directwrite.c` but fail to notice that their GDI provider is no longer used, they’d have the GDI code simply bitrotting, and I don’t know why we’d want to promote bitrot. And if they were to drop their GDI provider, well, why don’t we just ask for that to begin with?

Not to mention Aegisub’s (although not Kainote’s) libass is pinned to outdated versions (and wouldn’t automatically pick up this change) in the branches that have the GDI provider, or doesn’t actually use the GDI provider at all in the Meson branches.

(@CoffeeFlux I believe `src/libass_gdi_fontselect.cpp` is unused in your Meson build of Aegisub. If that’s intentional—and if you don’t support Windows XP, I guess we hope it’s intentional—then it can be removed.)

Alternatively, if someone were to compile an independent libass.dll (if Aegisub/Kainote load libass dynamically at all) and drop it in, surely it doesn’t matter what symbols Aegisub overrides in the first place, as the `ass_directwrite_add_provider` in the independent libass.dll would have our code.

**Comment by rcombs** [comment]
> I had the vague hope that bundling the fonts picked by GDI would result in the correct fonts being used everywhere

This seems nice in theory, but I'm not sure if we've ever had any particular reason to believe that GDI and libass-dwrite would give different results, since our dwrite code works by reading in the entire font list at startup (as dwrite doesn't seem to provide a way to search for a font by name). So the actual upshot of the GDI code is mainly that fonts become available as soon as they're installed (as it lazy-searches), rather than the list being frozen at startup. This is nice, but if we want that functionality we should add it to libass (I don't think there's anything especially C++-specific about what Aegisub does?).

> And yes, it will break the build, at least for Aegisub, as its libass subproject does not compile `ass_directwrite.c`

Ahh, didn't realize this. In that case, yeah, this wouldn't be super useful.

> Alternatively, if someone were to compile an independent libass.dll (if Aegisub/Kainote load libass dynamically at all) and drop it in, surely it wouldn’t matter what symbols Aegisub overrides in the first place, as the `ass_directwrite_add_provider` in the independent libass.dll would have our code.

I'm not sure if Windows works differently here, but on every POSIX-platform libc I've worked with, symbols in the main executable override symbols in shared libs, even those within the _same_ shared lib, unless you explicitly build with those symbols hidden or with the lookup order overridden by e.g. `-Bsymbolic`. That's what I'd assumed was going on here.

What I was hoping this would do was allow people making aegisub builds to get the standard libass behavior without needing to make changes to the code itself; I normally build Aegisub using an externally-built upstream libass.dylib on macOS and didn't realize it was common to build using something custom and internal on Windows. Some people build with newer versions, but I'm not sure if they're doing a normal libass build and linking Aegisub against it like I do, or if they're using the internal build. All this ends up making it even more difficult to figure out what code is actually running when people report issues and I'm not sure what the actual solution to that looks like.

Anyway, there's definitely some stuff worth discussing in here but it sounds like the top-line bit of this GHI is pretty pointless, so I'll close it out.

**Comment by astiob** [comment]
Thanks!

> I had the vague hope that bundling the fonts picked by GDI would result in the correct fonts being used

So in effect, I understand you were trying to make this flow:

1. during subtitle authoring, libass picks fonts from the system fonts

emulate this flow:

1. use Aegisub’s Font Collector to find fonts
2. embed them into an MKV
3. play that MKV with libass and have it pick the fonts from the MKV’s attachments

while the Font Collector uses GDI to emulate VSFilter.

That makes sense and is something worth thinking about, even if the method of overriding the font provider was a bit barbaric 😅

**Comment by CoffeeFlux** [comment]
I believe that is intentional, yes. I have no interest in supporting XP or 32-bit builds, but haven't actually had a chance to clean up the source tree. Thanks for the heads-up though, I'll sort it out eventually.

The Aegisub font finder and collector in general need some love—in addition to weird bugs they have some serious performance problems on certain scripts. It's one of the higher-priority things to fix up in my mind once I get the builds and installer generation fully functional.

The old Windows build system relied on an MSVC solution and IIRC had other quirks to it, beyond just being pinned to a specific old version of libass.

> if Aegisub/Kainote load libass dynamically at all

I believe only VSFilter, Avisynth, and sometimes the VC++ runtime are linked dynamically. Everything else has been linked statically on Windows for a while, including libass (though I think FFMS2 used to be dynamic?).

**Comment by astiob** [comment]
> I'm not sure if we've ever had any particular reason to believe that GDI and libass-dwrite would give different results, since our dwrite code works by reading in the entire font list at startup (as dwrite doesn't seem to provide a way to search for a font by name). So the actual upshot of the GDI code is mainly that fonts become available as soon as they're installed (as it lazy-searches), rather than the list being frozen at startup.

Right; I suppose the room for differences may be smaller than it seems at first glance. The key thing to remember is that **the font provider only gives us fonts, but we always make the final choice on our own.** But theoretically, I suppose the following might be possible:
* GDI and DirectWrite might give different names/traits when querying the same font.
* GDI’s font match/search might _not_ give us a font that we instead prefer when we search the full list we get from DirectWrite.
* Of course, we’ve seen an actual instance of GDI finding a font that we miss in DirectWrite’s list—and indeed the names being different—due to GDI’s 31-character limit on font names. But suppose we fix this in our own search code.
* Fallback might be different, but Aegisub doesn’t implement fallback for GDI, so this point is moot.

On the other hand, Aegisub’s GDI font provider always returns `false` for `check_postscript`, which actually breaks CFF font lookup by PostScript/full name and ironically reduces compatibility (GDI matches the PostScript name but not the full name, while this font provider does the opposite), although with some luck this should result in libass failing to find the font entirely, rather than finding a wrong one.
