### ISSUE TITLE
ASM and C output differ slightly

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#475]
As we found out in [#449](https://github.com/libass/libass/pull/449#issuecomment-748946531), there's a slight difference in our ASM and non-ASM image output and we don't know why.
To test eg run a non-ASM build against [this set of compare tests](https://github.com/TheOneric/libass-regression-tests-tmp), whose sample images were produced with ASM enabled.

**Comment by rcombs** [comment]
Is this what I fixed in 9238ce7621b7be868ab355199bfa2e837f7917e1 on the checkasm branch?
(Checkasm is meant to help address exactly this kind of issue)

**Comment by astiob** [comment]
> Is this what I fixed in 9238ce7 on the checkasm branch?

Haaaang on, that just sounded a click in my brain.

Is that (which you said was mysteriously fixed by adding extra padding in https://github.com/libass/libass/commit/9238ce7621b7be868ab355199bfa2e837f7917e1) just the lack of https://github.com/libass/libass/commit/f23b9ed64bd4ccf249c686616dd3f51a69d285dc ever having been ported over to the assembler implementation? I mentioned it a few times on IRC before and after that commit was merged to master ~~back in 2015~~, hoping that @rcombs might handle the assembler work, but—no offence intended—judging by `git log libass/x86/be_blur.asm`, it never ended up happening.

**Comment by TheOneric** [comment]
> Is this what I fixed in 9238ce7 on the checkasm branch? 

For the above mentioned tests, applying 9238ce7 doesn't make a difference.

**Comment by rcombs** [comment]
Uhhhhhh, quite possibly, yeah. Sounds like I should take another look over that.

**Comment by rcombs** [comment]
If 6eb12c2f38bfd64cf88bb76d9713fd5d26e0959e helps, then it was the be_blur issue. (Yes, that was in fact due to f23b9ed not being ported over; I've now done that). Otherwise, it's something in the rasterizer, which would be easiest to tease out by writing checkasm tests for those routines as well.

**Comment by TheOneric** [comment]
For this sample-set, there's no difference between master, master + 6eb12c2 and current checkasm/head.
