### ISSUE TITLE
Wrong ScaledBorderAndShadow default for event format lines using “Actor” not “Name”

### ISSUE THREAD

**Issue by Masaiki** [libass/libass#516]
https://github.com/libass/libass/commit/b3339152db5b80991966911fe2efc8a6174b0071 default SBAS to 'yes' with custom format lines and changes the default/fallback ASS Event format to use 'Name' instead of 'Actor'.
While this commit didn't consider that some old subtitles use 'Actor' not 'Name' and set ScaledBorderAndShadow to 1, which is in compatible with VSFilter.

**Comment by TheOneric** [comment]
> some old subtitles use 'Actor' not 'Name'

Huh? Could you point to how such files were created? Because, the ""spec"" uses `Name` and Aegisub also used `Name` since the very beginning¹, see [here](https://github.com/wangqr/Aegisub/blame/fe43cb641d0365217cd56cc0d776945056fab139/core/ass_file.cpp#L252), [here](https://github.com/wangqr/Aegisub/blame/fe43cb641d0365217cd56cc0d776945056fab139/core/ass_file.cpp#L399) and [there](https://github.com/wangqr/Aegisub/blame/7250b89cbd294eee8bbc0a07c98f464faa5697c6/aegisub/src/ass_entry.cpp#L74). *(While the format lines are now all nicely contained in `src/subtitle_format_{ass,ssa}.cpp`, they were duplicated and shuffeled around a lot prior to this)*

Aegisub does use `Actor` in the *GUI* but afaict it *never* used `Actor` in *files*.

**Comment by Masaiki** [comment]
> > some old subtitles use 'Actor' not 'Name'
> 
> Huh? Could you point to how such files were created? Because, the ""spec"" uses `Name` and Aegisub also used `Name` since the very beginning¹, see [here](https://github.com/wangqr/Aegisub/blame/fe43cb641d0365217cd56cc0d776945056fab139/core/ass_file.cpp#L252), [here](https://github.com/wangqr/Aegisub/blame/fe43cb641d0365217cd56cc0d776945056fab139/core/ass_file.cpp#L399) and [there](https://github.com/wangqr/Aegisub/blame/7250b89cbd294eee8bbc0a07c98f464faa5697c6/aegisub/src/ass_entry.cpp#L74). _(While the format lines are now all nicely contained in `src/subtitle_format_{ass,ssa}.cpp`, they were duplicated and shuffeled around a lot prior to this)_
> 
> Aegisub does use `Actor` in the _GUI_ but afaict it _never_ used `Actor` in _files_.



> > some old subtitles use 'Actor' not 'Name'
> 
> Huh? Could you point to how such files were created? Because, the ""spec"" uses `Name` and Aegisub also used `Name` since the very beginning¹, see [here](https://github.com/wangqr/Aegisub/blame/fe43cb641d0365217cd56cc0d776945056fab139/core/ass_file.cpp#L252), [here](https://github.com/wangqr/Aegisub/blame/fe43cb641d0365217cd56cc0d776945056fab139/core/ass_file.cpp#L399) and [there](https://github.com/wangqr/Aegisub/blame/7250b89cbd294eee8bbc0a07c98f464faa5697c6/aegisub/src/ass_entry.cpp#L74). _(While the format lines are now all nicely contained in `src/subtitle_format_{ass,ssa}.cpp`, they were duplicated and shuffeled around a lot prior to this)_
> 
> Aegisub does use `Actor` in the _GUI_ but afaict it _never_ used `Actor` in _files_.

as i know, subtitles generated by popsub use actor instead of name.

**Comment by TheOneric** [comment]
> as i know, subtitles generated by popsub use actor instead of name.

well, if PopSub is still developed, the first thing to do would be to update it to use the correct token name.
The best information about it I could find was [this](https://baike.baidu.com/item/popsub), which doesn't seem to contain any links to its source, which surely must have been made available somehwhere, since it's using VSF *(or I'm not finding the links on the page with machine translation applied)*

How widely is/was PopSub used? Treating `Name` and `Actor` as equivalent in custom format would require some changes, but isn't impossible. However, even then we will never be able to not break any files relying on either SBAS default. We know for a fact old ffmpeg/libav files and files with (intentional) custom Format lines *(which currently are only supported by libass)* are relying on libass' old SBAS=yes default. But I'm sure there also exist files with standard Format lines which relied on SBAS=yes and VSF-targeted files with in various, non-predictable ways garbeled format lines. So there will always exists some (hopefully few) files, which will needed to be either edited or fixed at run-time with style overrides (eg mpv's `--sub-ass-force-style`).

**Comment by Masaiki** [comment]
> > as i know, subtitles generated by popsub use actor instead of name.
> 
> well, if PopSub is still developed, the first thing to do would be to update it to use the correct token name.
> The best information about it I could find was [this](https://baike.baidu.com/item/popsub), which doesn't seem to contain any links to its source, which surely must have been made available somehwhere, since it's using VSF _(or I'm not finding the links on the page with machine translation applied)_
> 
> How widely is/was PopSub used? Treating `Name` and `Actor` as equivalent in custom format would require some changes, but isn't impossible. However, even then we will never be able to not break any files relying on either SBAS default. We know for a fact old ffmpeg/libav files and files with (intentional) custom Format lines _(which currently are only supported by libass)_ are relying on libass' old SBAS=yes default. But I'm sure there also exist files with standard Format lines which relied on SBAS=yes and VSF-targeted files with in various, non-predictable ways garbeled format lines. So there will always exists some (hopefully few) files, which will needed to be either edited or fixed at run-time with style overrides (eg mpv's `--sub-ass-force-style`).

Popsub used to be very popular, but now few people use it.
So you think it's a better choice to process before libass parsing?

**Comment by Masaiki** [comment]
i saw the VSFilter also use 'Actor' instead of 'Name' (https://github.com/pinterf/xy-VSFilter/blob/665757ca2ffac6c2cb0b90f8664ad34d6845992e/src/subtitles/STS.cpp#L3442), and so did libass before https://github.com/libass/libass/commit/b3339152db5b80991966911fe2efc8a6174b0071 .
so i think maybe 'Actor' is used wider than we ever expected.

**Comment by TheOneric** [comment]
> So you think it's a better choice to process before libass parsing?

Depends on how widespread this is, I just wanted to make sure everyone is clear about this being a “best effort” assignment without a perfect solution *(so **sometimes** it will make more sense to not handle something like this in libass)*.

> i saw the VSFilter also use 'Actor' instead of 'Name' (https://github.com/pinterf/xy-VSFilter/blob/665757ca2ffac6c2cb0b90f8664ad34d6845992e/src/subtitles/STS.cpp#L3442)

Welp, I guess VSF emitting `Actor` on sub conversion is a clear reason to do something about it. I just checked and it already was this way in Guliverkli(1).
Guess in this case, it would be best to treat `Actor` and `Name` as equivalent also in parsing, not just Format line comparison. *(This is actually a bit more lenient than necessary, since VSF only emits `Actor` for ASS, not SSA, but it simplifies code and given that this filed doesn't affect rendering anyway this should be harmless)*

> and so did libass before b333915 .

While the fallback line used `Actor`, libass *never* actually parsed `Actor`, only `Name`. Also, unlike MPC, libass doesn't write files. In theory, it would be possible for an API-user to reconstruct and save a file from libass' `ASS_Track`-struct, but that seems unlikely, given that libass doesn't do any subformat-conversion *(not counting text-encoding)*. Therefore I think libass old fallback is irrelevant to determine `Actor`-use in files.


---

On a related note, it seems clsid2 is interested in also parsing Format lines in MPC-HC: https://github.com/clsid2/mpc-hc/commit/c05a8bec4d87d2f4f6e8e2ca7993e202afb796e2
I think it would be good to contact clsid2 when that happens and try to harmonise our behaviour on custom format lines *(currently only the SBAS default)* to not make this any worse *(ofc, ideally libass would have defaulted to SBAS=no from the beginning)*. For this to be feasible, I suppose we will need to lock in to a way to detect custom format lines and the effects they cause.

**Comment by astiob** [comment]
We specifically detect FFmpeg files and set ScaledBorderAndShadow for them. Isn’t that enough? Why do we also set ScaledBorderAndShadow for odd format lines?

**Comment by TheOneric** [comment]
> We specifically detect FFmpeg files and set ScaledBorderAndShadow for them.

Not quite. We only detect FFmpeg/libav files **with an FFmpeg signature line**. This signature was only added 4 years after initial ASS support (2010) in FFmpeg, and **never** in libav (which continued to get releases until 2018 and stuck around in Gentoo until mid-2020).
At the same time *(commit-time wise, in git history it's a few commits before)* the signature was added, FFmpeg also switched to standard format lines, prior it used custom ones *(which also changed over time)*.

> Why do we also set ScaledBorderAndShadow for odd format lines?

Two reasons: First, we also want to match older FFmpeg- and libav-generated files, not only post-signature FFmpeg files¹. Second, all existing files with custom format lines were authored for libass, which until very recently defaulted to SBAS=yes. Meaning, all existing files with custom format lines, provided the format line was intended to be such, expect SBAS to default to yes. Also, at the time this was implemented it seemed like no one but libass will ever support custom format lines anyway.

---

[1]: An earlier version of the "change ScaledBorderAndShadow default" patchset, tried to closely match only, but all versions of FFmpeg and libav files, and no other files. This however complicated the detection and since we know all "custom format line"-files were authored with the old SBAS default, it was decided to instead keep the old default for FFmpeg **and** all custom format lines. *(iirc)*

**Comment by astiob** [comment]
> This signature was only added 4 years after initial ASS support (2010) in FFmpeg, and **never** in libav

Right, that explains it, thanks for reminding me.

> all existing files with custom format lines, provided the format line was intended to be such, expect SBAS to default to yes

Yes, but we do/did know existing files also have custom format lines and _don’t_ intend them to be used :-)

Welp. Time for another grep through that subtitle database?
