### ISSUE TITLE
Wrongly selecting italic typeface for certain weights on macOS

### ISSUE THREAD

**Issue by deus0ww** [libass/libass#525]
In mpv, certain weight results in libass wrongly selecting an italic typeface. This started happening after the recent fontselect/coretext changes (bfffc82c88b55071901f7d00ebe3e66168cd5a6d and 6fc9855dac44699242ded580040838da032c3a9d)

Info:
 - mpv: git head
 - libass: git head
 - OS: macOS 10.14.6 and 11.4

mpv log:
[   5.536][v][osd/libass] fontselect: (Helvetica Neue, 400, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue
[   5.536][v][osd/libass] fontselect: (Helvetica Neue, 700, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-Bold
[   5.537][v][osd/libass] fontselect: (Helvetica Neue, 300, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-Light
[   5.538][v][osd/libass] fontselect: (Helvetica Neue, 375, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue
[   5.538][v][osd/libass] fontselect: (Helvetica Neue, 481, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-MediumItalic
[   5.539][v][osd/libass] fontselect: (Helvetica Neue, 401, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue
[   5.539][v][osd/libass] fontselect: (Helvetica Neue, 425, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue
[   5.539][v][osd/libass] fontselect: (Helvetica Neue, 459, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-MediumItalic
[   5.541][v][osd/libass] fontselect: (Helvetica Neue, 527, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-MediumItalic
[   5.542][v][osd/libass] fontselect: (Helvetica Neue, 495, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-MediumItalic
[   5.543][v][osd/libass] fontselect: (Helvetica Neue, 564, 0) -> /System/Library/Fonts/HelveticaNeue.ttc, -1, HelveticaNeue-MediumItalic

**Comment by astiob** [comment]
Turns out this isn’t actually our fault: Helvetica Neue is bugged. HelveticaNeue-MediumItalic declares that it’s _not_ an italic font but in fact a _regular_ style. It does this in both its OS/2 table (used by Windows) and its `head` table (presumably used by macOS).

It only worked previously due to sheer luck: we can’t distinguish between them as they have identical weight and italics flag, so we pick whichever we see first. Previously, we saw HelveticaNeue-Medium before MediumItalic, so we selected that. At the same time, if you actually were to request italics at the same weights, it would fail to find the real MediumItalic font. Commit bfffc82c88b55071901f7d00ebe3e66168cd5a6d changed the order in which we receive Helvetica variants from the system, so now we see MediumItalic before we see Medium, so now it’s the other way round.

I’m not sure what we can do here.

Fontconfig and DirectWrite have heuristics to extract weight and slant from font name. We could do the same, but it’s not pretty and it is actually incompatible with VSFilter. (Actually: this right here is good reason for me to drop the `IDWriteFontFace3` commit from #523.) Perhaps a decent compromise would be to apply name heuristics to system-provided fonts but not to attached fonts?

**Comment by rcombs** [comment]
I've confirmed this is the case on at least 11.4 (20F71) and filed an issue with Apple about this; if anyone else wants to dupe it, ref FB9294504.

**Comment by deus0ww** [comment]
This is the info from the Font Book app:

PostScript name	HelveticaNeue-Medium
Full name	Helvetica Neue Medium
Family	Helvetica Neue
Style	Medium

PostScript name	HelveticaNeue-MediumItalic
Full name	Helvetica Neue Medium Italic
Family	Helvetica Neue
Style	Medium Italic

The Font Book app can correctly detect the style. How does it do that and can't Libass do the same?

(I'm asking because I'm completely ignorant of how all this works...)

**Comment by rcombs** [comment]
That's just the string "Medium Italic" from the name table; it doesn't reflect any machine-readable flags.

**Comment by astiob** [comment]
> I've confirmed this is the case on at least 11.4 (20F71) and filed an issue with Apple about this; if anyone else wants to dupe it, ref FB9294504.

Thanks! For reference, I see the problem on 10.13.6 (17G14042), so it’s been like this for a while.

I’m not sure I’m eligible to report it via the macOS app, and the website doesn’t quite seem to work for me in Firefox, but I’ll try.

> The Font Book app can correctly detect the style. How does it do that and can't Libass do the same?

What you’re seeing there, what you quoted, is just the names: the names are all right. But names are arbitrary text and don’t even have to be English. For software to recognize whether a font is italic or not, the font has a machine-readable declaration of its style—and for the font _named_ “Helvetica Neue Medium Italic”, that machine-readable style says “regular; not italic”. Indeed, there are _several_ machine-readable styles, but every single one of them says “not italic”.

Core Text somehow figures out that this font has `NSCTFontSlantTrait = "0.06666667014360428"` (same as HelveticaNeue-Italic), and TextEdit shows “italics on” when this font is selected. But I’ve inspected all of the tables that I’ve managed to find (sans PANOSE, I guess): `head`, `hhea`, `post`, `fond`, `os2`, `PCLT`. None of the italic flags are set, and all of the slant measures are zero. The only thing left is guessing italics from the name, like Fontconfig and DirectWrite do it.
