### ISSUE TITLE
Building ASM on OpenBSD: error on -fPIC, despite -prefer-non-pic

### ISSUE THREAD

**Issue by brad0** [libass/libass#539]
I have had the ASM disabled in the OpenBSD port for quite awhile as I couldn't get it to build. I tried again with 0.15.1, but it is still not building Ok.

I am looking around with libtool trying to figure out where the -fPIC -DPIC was added. It's the -fPIC that is causing the error.

```
/usr/local/bin/libtool  --tag=CC --mode=compile nasm -DARCH_X86_64=1 -f elf64 -Dprivate_prefix=ass -I./ -o x86/rasterizer.lo x86/rasterizer.asm -prefer-non-pic
libtool: compile:  nasm -DARCH_X86_64=1 -f elf64 -Dprivate_prefix=ass -I./ x86/rasterizer.asm  -fPIC -DPIC -o x86/.libs/rasterizer.o
nasm: fatal: unrecognised output format `PIC' - use -hf for a list
Type nasm -h for help.
```

**Comment by brad0** [comment]
> Ohh, seems like --with-pic alone isn't suffiecient. Unfortunately I currently can't test anything myself. From your log it seems like it only affects the ASM-parts and only the static library

That is what it looks like to me as well.

> (at least GNU libtool creates the shared library before the static one, don't know about OpenBSD's libtool)

It is the same for OpenBSD's libtool. Our libtool tries to copy GNU libtool behavior as much as possible.

**Comment by brad0** [comment]
> Can you try to initialise the assemblerflags to `ASFLAGS="-DPIC=1 "` on configure?

That did the trick.

```
/usr/local/bin/libtool  --tag=CC --mode=compile ../ltnasm.sh nasm -DPIC=1  -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ -o x86/rasterizer.lo x86/rasterizer.asm
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/rasterizer.asm  -fPIC -DPIC -o x86/.libs/rasterizer.o
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/rasterizer.asm -o x86/rasterizer.o >/dev/null 2>&1
/usr/local/bin/libtool  --tag=CC --mode=compile ../ltnasm.sh nasm -DPIC=1  -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ -o x86/blend_bitmaps.lo x86/blend_bitmaps.asm
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blend_bitmaps.asm  -fPIC -DPIC -o x86/.libs/blend_bitmaps.o
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blend_bitmaps.asm -o x86/blend_bitmaps.o >/dev/null 2>&1
/usr/local/bin/libtool  --tag=CC --mode=compile ../ltnasm.sh nasm -DPIC=1  -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ -o x86/be_blur.lo x86/be_blur.asm
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/be_blur.asm  -fPIC -DPIC -o x86/.libs/be_blur.o
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/be_blur.asm -o x86/be_blur.o >/dev/null 2>&1
/usr/local/bin/libtool  --tag=CC --mode=compile ../ltnasm.sh nasm -DPIC=1  -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ -o x86/blur.lo x86/blur.asm
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blur.asm  -fPIC -DPIC -o x86/.libs/blur.o
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blur.asm -o x86/blur.o >/dev/null 2>&1
/usr/local/bin/libtool  --tag=CC --mode=compile ../ltnasm.sh nasm -DPIC=1  -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ -o x86/cpuid.lo x86/cpuid.asm
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/cpuid.asm  -fPIC -DPIC -o x86/.libs/cpuid.o
libtool: compile:  ../ltnasm.sh nasm -DPIC=1 -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/cpuid.asm -o x86/cpuid.o >/dev/null 2>&1
```

and now it builds in full. All of the regression tests pass.

**Comment by TheOneric** [comment]
Re: `--with-pic`: On Debian, Alpine and NetBSD setting this flag does indeed cause `-fPIC -DPIC` to be passed to ltnasm.sh for both static and dynamic lib objects.
Since `ASFLAGS="-DPIC=1"` does also work, I'm not sure if you want to investigate further @brad0, but **if** you do:
It would be interesting to see what happens on OpenBSD if you force usage of GNU libtool during configure and the build, or use the more explicit `--with-pic=yes`. Just in case this is a deviation from GNU libtool rather than an (unexpected but) intended platform quirk. *(Accepted values are `yes`, `no` and `both`; if no `--with(out)-pic(=VAL)` is specified it defaults to `both`, and in absence of an explicit value `--with-…` is normally supposed to default to `yes` and `--without-…` to `no`)*

**Comment by brad0** [comment]
I would like to.

I tried with both GNU libtool as I had before and it made no difference nor did using --with-pic=yes with GNU libtool.

Anyway, this is a good step forward. But I'd still like to look into the libtool behavior in addition to your pending patch.

**Comment by TheOneric** [comment]
Just to make sure, you are testing with the (second version of the) patch from this thread of the patch from the PR, right? And you were using GNU libtool for all of the configuration and compilataion?

I setup a VM with i386 OpenBSD 6.9 and tested GNU libtool with `--with-pic=yes`; all assembly objects got the PIC-flags and compilation and the regression tests passed without an error:

```
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blur.asm  -fPIC -DPIC -o x86/.libs/blur.o
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/be_blur.asm  -fPIC -DPIC -o x86/.libs/be_blur.o
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blend_bitmaps.asm  -fPIC -DPIC -o x86/.libs/blend_bitmaps.o
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/rasterizer.asm  -fPIC -DPIC -o x86/.libs/rasterizer.o
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/cpuid.asm  -fPIC -DPIC -o x86/.libs/cpuid.o

libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blur.asm  -fPIC -DPIC -o x86/blur.o >/dev/null 2>&1
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/be_blur.asm  -fPIC -DPIC -o x86/be_blur.o >/dev/null 2>&1
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/blend_bitmaps.asm  -fPIC -DPIC -o x86/blend_bitmaps.o >/dev/null 2>&1
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/cpuid.asm  -fPIC -DPIC -o x86/cpuid.o >/dev/null 2>&1
libtool: compile:  ../tools/ltnasm.sh nasm -DARCH_X86_64=0 -f elf32 -Dprivate_prefix=ass -I./ x86/rasterizer.asm  -fPIC -DPIC -o x86/rasterizer.o >/dev/null 2>&1
```

The full transcript, installed ports and commands run is attached: [539_script.zip](https://github.com/libass/libass/files/7101356/539_script.zip), I hope this provides enough info to be useful. For some reason *(perhaps it doesn't like the default VM-configuration?)* this VM was ~50× slower than any other of my VMs, taking a bit more than an hour just to configure and compile libass.

**Comment by brad0** [comment]
I updated the patch to what is pending from the PR and the only differences I see are some comment tweaking and removing a commented out echo command.

```
 Index: ltnasm.sh
 --- ltnasm.sh.orig
 +++ ltnasm.sh
-@@ -0,0 +1,29 @@
+@@ -0,0 +1,28 @@
 +#!/bin/sh
 +
 +# Translate libtool supplied C-compiler options for NASM.
 +# libtool treats NASM like the C compiler, and may supply -f_ options
 +# which are interpreted as the output file format by NASM, causing errors.
-+# Notably libtool will set -DPIC -fPIC and -fno-common; we want to keep
-+# -DPIC but remove everything else.
++# Notably libtool will set -DPIC -fPIC and -fno-common;
++# we want to use -DPIC by translating it to -DPIC=1, but remove everything else
 +#
-+# Filtering the options as done here in this plain POSIX shell script would
-+# mess up if there were any spaces in the arguments, but this will never happen
-+# since our filenames or options do not contain spaces and source paths are
-+# also not allowed to contain spaces.
++# Theoretically the way the filtering is done here in a plain POSIX shell script,
++# does mess up if there were spaces in any argument. However this will never happen
++# since neither our filenames nor options do not contain spaces and source paths
++# are not allowed to contain spaces by configure.
 +
 +cmd=""
 +while [ "$#" -gt 0 ] ; do
@@ -43,5 +43,4 @@ Index: ltnasm.sh
 +    shift
 +done
 +
-+#echo "$cmd"
 +exec $cmd
```

Yes, the way our ports tree uses libtool it doesn't replace the autoconf bits that are generated. It just overrides the libtool used after the configuration stage (configure script is executed).

That is so strange. What hypervisor are you using? I am using VMware 15.5 at the moment on a nothing special Windows system and it's not fast but nowhere near that slow. I can't say as I have heard of any major performance issues on KVM or Hyper-V.

Thanks. I still want to look into this and try to figure out where things are going wrong.

**Comment by TheOneric** [comment]
> the only differences I see are some comment tweaking and removing a commented out echo command.

Yup, either of those version should be fine, just not the very first version which isn't replacing `-DPIC ` with `-DPIC=1 `.


>  it doesn't replace the autoconf bits that are generated. It just overrides the libtool used after the configuration stage (configure script is executed).

Yeah, but I compiled from git, so there were no pregenerated files. If you're using the generated files from the last release, those were generated with automake 1.16.1 instead of 1.16.3 and autoconf 2.69 not 2.71; possibly there was a related bugfix since then? Here's a tarball from master with the ltnasm-patch applied generated with autoconf 2.71 and automake 1.16.4 *(additionally zipped so that GitHub allows me to attach it)*: [libass-0.15.1.tar.xz.zip](https://github.com/libass/libass/files/7102116/libass-0.15.1.tar.xz.zip)


> What hypervisor are you using?

KVM via libvirt, specifically on an AMD CPU and managed via virt-manager with all of virt-manager's default settigns except for VNC instead of SPICE for display to not get duplicated or dropped keys while typing in the VM; I tried siwtching the virtual graphics to VGA instead of QXL but that didn't help either. I didn't have problems with any other guest system yet. The guest got 4GB of RAM and I tried both 4 and 6 cores, which didn't make any noticeable difference.

**Comment by brad0** [comment]
> If you're using the generated files from the last release, those were generated with automake 1.16.1 instead of 1.16.3 and autoconf 2.69 not 2.71; possibly there was a related bugfix since then? Here's a tarball from master with the ltnasm-patch applied generated with autoconf 2.71 and automake 1.16.4 _(additionally zipped so that GitHub allows me to attach it)_: [libass-0.15.1.tar.xz.zip](https://github.com/libass/libass/files/7102116/libass-0.15.1.tar.xz.zip)

That is a possibility. I will see if I can try that out and see if it makes any difference at all.

> > What hypervisor are you using?
> 
> KVM via libvirt, specifically on an AMD CPU and managed via virt-manager with all of virt-manager's default settigns except for VNC instead of SPICE for display to not get duplicated or dropped keys while typing in the VM; I tried siwtching the virtual graphics to VGA instead of QXL but that didn't help either. I didn't have problems with any other guest system yet. The guest got 4GB of RAM and I tried both 4 and 6 cores, which didn't make any noticeable difference.

Ya, that is pretty strange, but I can't comment any further.

**Comment by TheOneric** [comment]
I tested the above tarball without autoreconf and with  GNU libtool on i386 OpenBSD and `--with-pic=yes` and it worked as expected; here's the log: [539_script_tarball.zip](https://github.com/libass/libass/files/7117587/539_script_tarball.zip). Due to the long test time I didn't test with previous tarballs, OpenBSD's libtool or plain `--with-pic`.
At least from this single test it seems like the `--with-pic(=yes)` issue is indeed an issue not a surprise-feature and likely related to either older versions of autoconf/automake, OpenBSD's libtool, or the combination of both; but ideally this would be verified by brad0.
