### ISSUE TITLE
Investigate behavior on font names longer than 31 characters

### ISSUE THREAD

**Issue by rcombs** [libass/libass#547]
Note: for the purposes of this issue, I'm using "character" to mean "UTF-16 code unit", which is all sorts of screwy, but it's useful shorthand.

GDI truncates font names at 31 characters due to the 32-character buffer in the `LOGFONTW` structure. We currently don't emulate this behavior at all.

We should be able to match this behavior without _too_ much trouble for font sources where we ingest the full font list (DirectWrite in at least some cases?, fontconfig, muxed/memory fonts, font dir). This would likely be impossible to handle with our current CoreText provider; it may be worth looking into switching that to also ingesting the full list (this might be cheaper if we just pull in names… though I'm not sure exactly what's possible there; worth looking into).

Here's an example file with >31-character names: [W3.TTC.zip](https://github.com/libass/libass/files/7148802/W3.TTC.zip)

**Comment by rcombs** [comment]
@TheOneric points out that this is really a dupe of #459. Closing.

**Comment by astiob** [comment]
Just to clear up a few things:

> DirectWrite in at least some cases?

It never loads full lists any more, but in the GDI path we go through the actual truncation in GDI, so search works like in VSFilter and truncates all names, and the names we get out of it are also truncated (or so I think—this last part should be re-verified).

> it may be worth looking into switching [the Core Text provider] to also ingesting the full list

For reference, the old b0776d353f8c3396165effd21e113c4f225daa0d showed 0.4 s for ingesting the full list vs 0.08 s for lazy-loading, which we do now (on a “typical” font collection—typesetters and other hoarders might have it worse).

> This would likely be impossible to handle with our current CoreText provider

And likely the UWP paths in the DirectWrite provider, which similarly lazy-load by asking DirectWrite itself to find fonts with matching names. Going back to ingesting the full list is likely not an option because we’ve _just_ made the switch in the other direction due to it being slow (#477).
