### ISSUE TITLE
mpv release v0.34.0 showing subtitle style wrong

### ISSUE THREAD

**Issue by erickyun** [libass/libass#571]
mpv stable v0.33.0 and stable v0.34.0 .ass subtitle style are different? v0.34.0 showing subtitle style wrong.

[shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/release/) stable v0.33.0 subtitle:
![mpv-shot0001](https://user-images.githubusercontent.com/71968711/141349215-33335a6c-4a42-49de-ad21-58c15180dd59.jpg)

[shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/release/) stable v0.34.0 subtitle:
![mpv-shot0002](https://user-images.githubusercontent.com/71968711/141349697-6298d581-f147-4ad6-b2ea-310d1d24e2ba.jpg)

v0.33.0 subtitle style is right but v0.34.0 subtitle style is wrong it looks like the mpv android.

**Comment by TheOneric** [comment]
Thanks for your report, please provide the following additional information:

**Compare to VSFilter**
Before reporting an issue, If possible, check what your file looks like in a video player that uses VSFilter to render subtitles (for example, MPC-HC). If it looks the same, even if it still feels wrong, this is probably intentional and not an issue with libass.

**System used?**
If VSFilter and libass screenshots were taken on different systems, give info for both
OS:  *(\*Linux, MacOS, Windows, …)*
CPU: *(32 or 64Bit AMD/Intel x86, ARM, POWER, …)*

**Show the ASS code**
If possible, show an excerpt of the ASS script that looks wrong. Include the relevant Dialogue and Style lines. The excerpt should basically be a fully functional ASS file in itself. If you can’t make an excerpt, we can work with a full ASS file if you tell us the time at which the problem occurs.

If you see the problem with a particular video file that contains subtitles, try to upload a short cut from the video file that we can play to see the problem. You can use tools such as MKVToolNix to make a smaller cut from a large file.

**Include the font**
If a particular font is needed to see the wrong rendering, upload it as a file if you have permission to do so. If it is a free font available on the Web, you can instead give a link to it.

**Log**
If you have logs regarding the issue please include them. Eg for [mpv](https://github.com/mpv-player/mpv), you can obtain a log by adding `--log-file=output.txt` when playing the affected file. Ofc you'll need to actually play the affected part of the video fully for the logs to contain anything useful.

**Comment by erickyun** [comment]
> Compare to VSFilter

MPC-HC screenshot: https://imgur.com/a/NtCil8m

> System used?

OS: Windows 10
CPU: 64Bit Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz

> Show the ASS code

[[CR] World Trigger 3rd Season - 5 [1080p]_Subtitles01.ENG.zip](https://github.com/libass/libass/files/7635201/CR.World.Trigger.3rd.Season.-.5.1080p._Subtitles01.ENG.zip)

> Include the font

[[CR] World Trigger 3rd Season - 5 [1080p]_Attachments.zip](https://github.com/libass/libass/files/7635210/CR.World.Trigger.3rd.Season.-.5.1080p._Attachments.zip)

> Log


EDİT:
it seems that arialbd.ttf font was missing but it's weird cuz v0.33.0 was working fine without that font?
but I'm closing this issue anyway cuz the problem seems with including the font solved thank you for your response. 👍
