### ISSUE TITLE
[Feature request v5] FSCZ

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#572]
FSCZ would be usefull to do some 3d letter.

Here is an example where it could be really usefull: https://streamable.com/ujlbxc

Thank you

**Comment by TheOneric** [comment]
I'm assuming you want to add letter thickness; `\fscz` as “scaling” in z-direction (before rotation) isn't a good way to do this, as the current (default) thickness is 0, which will stay zero no matter by how many percent it is scaled.
If 3D-letters were added the letter thickness in z-direction would need to be its own property. However, this is not enough to get useful or good-looking 3D-letters, we'd also need at least:
  * letter material (this can have quite a lot of variables; we can probably ignore anisotropic materials, but since letters can be partially transparent we probably can't ignore transmission behaviour)
  * lightning position(s) (& lightning colour?, only isotropic point lights or directed light and emitting surfaces...)
`\fscz` could then act on the thickness-property and 3D-Events would best be their own Event-Type distinct from regular (2D surfaces in a 3D-space) Events.

This would require a lot of work and would be very costly to render *(if no GPU-acceleration is available)*. Tbh, I doubt this is worthwhile to add, at least not to ASS or as a 1.0-feature *(5.0?)* for a potential ASS-successor. Nonetheless, I added a note about it to the ASSv5 entry in the wiki and if ASSv5/ASSv2/SSAv5/… ever becomes a reality, we'll see if this can or makes sense to be included.
