### ISSUE TITLE
DirectWrite fontselect apparently disagreeing with VSFilter on certain font

### ISSUE THREAD

**Issue by rcombs** [libass/libass#576]
This came up in Ristellise/AegisubDC#40. The issue there appears to be due to the wrong font being used on Windows (this doesn't happen for me on macOS as long as I have the font installed). Aegisub disables attached fonts in libass for some reason, so this is a font provider issue; in `test.c`, this works fine even with the font not installed.

That fork of Aegisub doesn't replace our directwrite provider, so this one's on us. They've tested and seen the same behavior on libass 5733e1c and 66dba8d.

**Comment by Ristellise** [comment]
> That fork of Aegisub doesn't replace our directwrite provider, so this one's on us.

To be more exact. Any version higher than 9213 (Inclusive of said version) does not override Directwrite provider.

**Comment by astiob** [comment]
The screenshots _look_ like they have the same font though. And whatever font is selected, the two lines both use the same font. Are you sure this is a font selection issue?

**Comment by rcombs** [comment]
Ah, just tested locally on 5733e1c and was able to repro, so yeah, this is actually unrelated and just happens to have been fixed between then and master; using the wrong font just happens to produce similar-looking symptoms (and I'm not used to arabic text enough to distinguish fonts at a glance). @Ristellise you can just go ahead and update your libass to resolve this.

**Comment by astiob** [comment]
Ah, thanks! Turns out it was fixed by d170d89.

This is a pretty interesting effect that I hadn’t thought of when discussing that commit or writing the commit message. Here, the black line (unlike the pink line) contains U+202B, which is absent from the main font and is (in old libass) looked up in a fallback font. It is _found_ in the fallback font, but presumably the fallback font has bigger metrics, causing the whole line’s metrics to be adjusted and the `\pos` alignment point to drift off.
