### ISSUE TITLE
[Feature Request] support for margin-top and margin-bottom in style

### ISSUE THREAD

**Issue by Masaiki** [libass/libass#599]
I'm working on editing style in "xysubfilter with libass", and I found that margin-top and margin-bottom of style properties have been implemented by VSFilter in both mpc-be and mpc-hc and xy-VSFilter, which could be edited in the property page, read in an ASS file or from a mkv stream while libass doesn't 
this may be a part of  "script type 4.00++".

**Comment by TheOneric** [comment]
Yes, this is part of v4++ *(see #461)*. Do you have any genuine v4++ files which were/are distributed and contain `Format:` lines?
Since libass parses Format lines, we would ideally want to know the cannonical in-document names of the fields. For the margins `MarginT` and `MarginB` seem plausible, but a confirmation would be neat and v4++ also added another new field.

**Comment by Masaiki** [comment]
i have no idea about this.

**Comment by TheOneric** [comment]
Do you have any real-world v4++ files *(even without `Format:` lines)*? Or did this came up as a result of poking the VSFilter code?
Even without a ormat:` line, real-world samples could indicate how the "relativeTo" field is used and help us decide whether to follow xy-VSF in ignoring it or trying to emulate whatever guliverkli does.
If you have such samples it would be great if you could share them in #461, where further progress for v4++ will be tracked.
