### ISSUE TITLE
How to load the non-utf-8 ass subtitles

### ISSUE THREAD

**Issue by hooke007** [libass/libass#614]
Using mpv to load the utf-16/gb2312_80 the ass subtitle, it failed to load and showed the message below.

![Snipaste_2022-04-20_09-49-11](https://user-images.githubusercontent.com/41094733/164189606-28989b52-3ac0-42b2-a0c9-b7e9f3e6a5b8.jpg)

**Comment by TheOneric** [comment]
For reference, libass takes a ` char *codepage` in the `ass_read_file`, `ass_read_memory` and `ass_read_styles` functions *(i.e. API for external subtitle sources)*. If set to something other than `NULL` and libass was compiled with iconv support, the passed in data will be converted from `codepage` to UTF-8 by libass. The API-functions for muxed subtitle data, do not have a `codepage` parameter, as subtitles muxed into Matroska are already required to be UTF-8.

Regarding mpv, the third function is always used with `NULL` as `codepage`, and the other tow aren't used at all. I assume mpv uses ffmpeg to mux external subtitles into the stream. Your issue is likely not with libass, but mpv or one of its dependencies.  

mpv's manual documents a `--sub-codepage=<codepage>` option and suggests uchardet can be used to autodetect the encoding. If your file plays correctly with `--sub-codepage` set explicitly, the problem might be uchardet misdetecting the encoding or your build of mpv does not support uchardet. If it still doesn't work, it might be an issue with ffmpeg not recognising the file as ASS. Or it’s an mpv specific issue.
After testing the `--sub-codepage` option, best ask on [libera.chat/#mpv](https://web.libera.chat/#mpv) where to file an issue.

**Comment by astiob** [comment]
mpv doesn’t use libass’s file reading functionality. It loads external subtitles via FFmpeg. At any rate, this seems to be a question about mpv, which will indeed get better answers in mpv’s IRC channel or tracker.
