### ISSUE TITLE
Rendering: changing video resolution changes \org results

### ISSUE THREAD

**Issue by tormento** [libass/libass#621]
### Screenshots

With MPV (latest version):
![image](https://user-images.githubusercontent.com/2351785/167495935-f4a257cf-5476-47f7-82b5-e3f5dcdf0f89.png)

With MPC-HC or KODI (both latest version):
![MPC-HC](https://user-images.githubusercontent.com/2351785/167493896-40e98303-83f1-4ccc-8553-c7cf7336d5cc.jpg)
I

### Description of the issue

I have remuxed some softsub anime that I have from 720p to 1080p.

The video raws are frame by frame identical.

As you can see, the rotation has gone to hell.

### libass version

The one included in MPC-HC, last version

### ASS Sample

https://krakenfiles.com/view/7zTdD0fCma/file.html

@ 5:55

### Special Fonts

I uploaded or linked to the required font

### System Information

Windows 11 x64

**Comment by rcombs** [comment]
This is the same behavior as in VSFilter; remuxing on video of a different resolution is not supported by the ASS format. You need to adjust your typesetting accordingly.

**Comment by tormento** [comment]
Sorry to reopen but with VSFilter it works ok, at least with MPC-HC and Kodi.

**Comment by TheOneric** [comment]
To expand a bit on rcombs answer:
MPC-HC’s internal subtitle render is known to deviate in multiple ways from other ASS renderers breaking existing softsubs. If it happened to keep the look of the rotation after remuxing without breaking anything else in the file, you just got lucky *(or the subtitles were authored for MPC-HC’s ISR only, in which case the subs should not be rendered with anything but MPC-HC ISR)*.
Instead of the internal renderer, you can use [XySubFilter](https://github.com/Cyberbeing/xy-VSFilter/releases/tag/3.1.0.752)  or [xy-VSFilter](https://github.com/Cyberbeing/xy-VSFilter/releases/tag/3.0.0.306) with MPC-HC to get results matching "standard" ASS compatible with existing softsubs.

Also, Kodi uses libass by default afaik and the latest version "Matrix-19.4" should match the mpv rendering (xbmc#21040).

---

For future reference:
> **libass version**: The one included in MPC-HC, last version

The version info should always correspond to the provided screenshot, which you claimed is from mpv. Considering clsid's MPC_HC can use libass but doesn't by default, maybe this is just a typo.
Either way, *“\<some player\>, last version”* is not sufficient to know which libass version is being used. If there's a log, include it as it will likely contain an exact libass version. Without concrete version info, as the template tells you, we will at least need all three of the following: “**precise** information on your player, its version **and** where you got the player binary from”.

**Comment by tormento** [comment]
@TheOneric thanks for your explanation.

There are the software versions that I used to do screenshots.

mpv-x86_64-20220508-git-3458651.7z @ mpv.io
mpv.net-5.9.0.0-beta.zip @github.com/stax76
MPC-HC.1.9.21.19.x64.zip @github.com/clsid2
XySubFilter_with_libass_20220124.zip @github.com/Masaiki
kodi-19.4-Matrix-x64.exe @mirrors.kodi.tv
kodi-19.4-Matrix for Android TV @Play Store

Original, untouched 720p source on MPV (or whatever else player)
![Original_720p](https://user-images.githubusercontent.com/2351785/167594660-375d9824-87a2-40a5-996d-6590ecf5df3e.jpg)

1080p source, 720p ass on MPC-HC
![MPC-HC](https://user-images.githubusercontent.com/2351785/167594854-efc776e8-e73d-40b9-91a1-36664510fb4b.jpg)

1080p source, 720p ass on MPC-HC with XYSubFilter
![MPC-HC_XYSub](https://user-images.githubusercontent.com/2351785/167594978-87505c3d-0704-432a-ab2c-f21aaaea42fe.jpg)

1080p source, 720p ass on MPV
![MPV](https://user-images.githubusercontent.com/2351785/167595072-910d057a-923f-4259-8f21-93cc56b83826.jpg)

1080p source, 720p ass on MPV.NET
![MPV_NET](https://user-images.githubusercontent.com/2351785/167595144-e5983420-b30c-4d3a-908c-09370a7c5a2d.jpg)

1080p source, 720p ass on Kodi for Windows
![Kodi](https://user-images.githubusercontent.com/2351785/167595227-e0011766-ef25-4c77-abcb-511bf52ec495.jpg)

1080p source, 720p ass on Kodi for Android TV (photo)
![Kodi_TV](https://user-images.githubusercontent.com/2351785/167597326-5243745b-9687-4a7a-8696-fad1e62df693.jpg)

If you need other information, please ask.

**Comment by TheOneric** [comment]
> These are the software versions that I used to do screenshots.

Thanks, except for Android TV Kodi the results are all as expected. You probably should report the difference between the platforms to Kodi developers at https://github.com/xbmc/xbmc/issues. To avoid confusion about which rendering is the correct one, it’s probably better to use this sample instead of your incorrectly remuxed subs: [ass-storage-size_issue.zip](https://github.com/libass/libass/files/8664377/ass-storage-size_issue.zip)

> XySubFilter_with_libass_20220124.zip @github.com/Masaiki

As the name suggests, you are not actually using XySubFilter, but libass via a wrapper enabling applications supporting XySubFilter's interface (but not directly libass) to use libass. In this case though, using [actual XySubFilter](https://github.com/Cyberbeing/xy-VSFilter/releases/tag/3.1.0.752) will yield the same result.

**Comment by tormento** [comment]
@TheOneric thanks for your explanation.

There is no way for libass to render an ass subtitle "properly" (even if "wrong") despite resolution change, while keeping same AR?

Some "switches" inside the ass itself?

What makes me wonder is why VS seems resolution indipendent and not libass.

**Comment by tormento** [comment]
@TheOneric and a "on the fly" \org conversion is impossible, I guess.

At the end of the day, it's that part that causes problems.
