### ISSUE TITLE
Can I change line space when multi lines(use \N)?

### ISSUE THREAD

**Issue by yinjiaoyuan** [libass/libass#625]
Can I change line space when multi lines(use \N)? Change it little or large. Thanks.

**Comment by astiob** [comment]
You can make it larger with some tricks, but not smaller.

The easiest is to insert an empty line between each pair of lines. An empty line’s height is always exactly half of its `\fs`. For example, if you have

```
A quick\Nbrown fox\Njumped over\Nthe lazy dog.
```

and you want to add 10 extra pixels of line spacing, you could do:

```
A quick\N{\fs20}\N{\r}brown fox\N{\fs20}\N{\r}jumped over\N{\fs20}\N{\r}the lazy dog.
```

A different option is to start every line except the first with a vector drawing like this: `{\p1}m 0 0 n 0 123{\p0}` But the number you’d need here depends on the font’s OS/2 ascent height. Specifically, it should be `font's usWinAscent + extra spacing you want to add`.

**Comment by yinjiaoyuan** [comment]
Thanks! I want to change it smaller. I use libass with freetype in centos7.

**Comment by TheOneric** [comment]
If you are an API user rather than a subtitle author and this is about on-the-fly generated ASS purely internal to your program, then you can use `ass_set_line_spacing` to reduce the line spacing via negative values (in pixels).
For subtitle authors there is no way to reduce the spacing, only various ways to increase it.
