### ISSUE TITLE
Rendering: Karaoke mode: Word parts only highlighted with the next word in some cases

### ISSUE THREAD

**Issue by EmanuelLoos** [libass/libass#638]
### Screenshots

![example](https://user-images.githubusercontent.com/29912739/185408010-bb95568f-0070-4f86-af06-996f07ee9cbe.png)

![example-vp9.webm](https://user-images.githubusercontent.com/29912739/185406633-605f36a0-cfd6-418c-997c-a9d150af4ece.webm)

### Description of the issue

In karaoke mode, when only the last part of a word is underlined, this part is not highlighted in the primary colour with the non-underlined part but highlighted with the next word.

This also is the case when the font is changed for only a part of a word.

### libass version

0.16.0-1

### ASS Sample

```
{\k162}hodie{\i1\fnPurisa}que{\i0\r} {\k118}{\board1\c&HFF9920&\fnOpenDyslexic}cael{\b1\u1}um{\b0\u0\r} {\k24}{\fnBerenika}est{\r} {\k156}{\board1\c&HFF9920&\fnOpenDyslexic}candid{\b1\u1}um{\b0\u0\r}
```

### Special Fonts

The issue doesn't depend on a specific font

### System Information

OS: Devuan GNU/Linux testing
CPU architecture: amd64

**Comment by TheOneric** [comment]
While this isn't intuitive behaviour, xy-VSFilter (tested: v3.0.0.306) behaves the same way by apparently using any following run split as a karaoke delimiter rather than only the next karaoke tag. The same is true for VSfilterMod, specifically whatever version was bundled with plorkyeran’s Aegisub r8942 build, indicating this likely goes back to the original guliverkli(2)-VSFilter *(which I'm unable to test directly)*.
Thus, no matter how odd it may seem, this is required behaviour for compatibility with existing files and other renderers.

**Comment by EmanuelLoos** [comment]
Do you know of any workaround?

**Comment by astiob** [comment]
For \k and \ko, try simply adding \k0 (or respectively \ko0) in each of the intermediate override tag blocks.

**Comment by astiob** [comment]
No, wait, that's just the same as what you have now, isn't it.What you need to do is replace the *first* \k of the karaoke word by \k0 and move your actual meaningful \k tag into the *last* override block of that same word. (You could probably drop the \k0 in VSFilter and current libass, but I think old libass may behave differently if you do. Plus including it should make it clear to anyone later editing your file that some strange shenanigans are involved.)Or if you prefer, you can trivially replace all your \k by \t that instantly change \1c.
