### ISSUE TITLE
Allow both text and border to be blurred

### ISSUE THREAD

**Issue by FuzzyWuzzyBMP** [libass/libass#656]
[Currently](https://aeg-dev.github.io/AegiSite/docs/3.2/ass_tags/#:~:text=Blur%20edges) text itself cannot be blurred if it has a border. So one has to choose between pleasingly soft but (depending on video frame) potentially illegible text:
```
sub-border-size=2.5
sub-blur=1.0
```
![image](https://user-images.githubusercontent.com/13451773/197871954-884dc272-2a53-4be9-934e-44deebabaa6e.png)
Or legible but harshly sharp text:
```
sub-border-size=0
sub-blur=1.0
```
![image](https://user-images.githubusercontent.com/13451773/197872027-4cc626d0-ccf1-476a-954c-a3538d3c794f.png)
(Examples rendered with mpv player)

I propose that text and border be given separate options for blurring, or that the blur option applies to both.

An [alternative](https://github.com/mpv-player/mpv/issues/10784#issuecomment-1290994661) was given, to render subs at video resolution with `blend-subtitles=video`. This often incidentally helps, but is not sufficient. The resolution of the video stream does not necessarily equal the resolution of the video content. I.e. a high-definition video that is slightly out of focus, or where the subject of the video has a soft appearance. And while this is subjective, I find that even if both video and subject are sharp, slightly blurry subtitles are more pleasant.

**Comment by TheOneric** [comment]
Am I correct to assume your motivation is about user overrides exposed by players and not authoring ASS subs yourself?
Also do you have `sub-ass-override=force`, `=scale` or `=strip` set (or the deprecated `no-sub-ass` or `no-ass`)? If not your example mpv configs will only affect converted, i.e. non-ASS, subs. Is this your intention?

**Comment by FuzzyWuzzyBMP** [comment]
> your motivation is about user overrides exposed by players and not authoring ASS subs yourself?

Correct. I had not considered authoring subs - that could be a viable solution for myself (assuming ASS supports what I have in mind), but not for the great majority of users. I am sure they would also prefer softer-appearing subtitles - they just don't know it yet :)

I do have `sub-ass-override=strip` set, but the example I gave uses SRT subs, so I omitted that part of the configuration. It is my intention to enable such blurring for all subtitles: SRT, ASS, and whatever else is in use. I was under the impression that libass is used to render both SRT and ASS subs - but I am by no means certain.

And if I may expand a little on this preference for blurry subs: It is not blurryness per se that is desirable, but the 'natural' appearance it approximates. Crisp, clear, clean subtitles may be very legible and convenient, but they are like a fence made of sterile brushed aluminum plates, where a moss-covered stone or wood fence would look much nicer, despite being harder to distinguish. Older films chanced upon this - they may not have intended their subtitles to be grainy and out of focus, but they were better for it. Applying a simple blur goes a long way towards capturing that feeling of naturalness.

**Comment by TheOneric** [comment]
> I was under the impression that libass is used to render both SRT and ASS subs - but I am by no means certain.

libass is an ASS and SSA renderer. Some players such as mpv convert other subtitle formats to ASS during playback and use libass to render those converted subs. We have a limited selection of additional functionality to help with that, but it isn't our core concern.

> assuming ASS supports what I have in mind

If you want to achieve a visual appearance similar to as if border and text were blurred together you can for example use multiple layers. One consisting of only border and one consisting of only text and apply `\blur` to both of them.
From top to bottom, here are examples for 1) no blur, 2) only border being blurred 3) blurring both text and border using two layers:
![illustration](https://user-images.githubusercontent.com/1668471/198853985-28e451c2-a9c3-4da8-9ca6-0025d40b1f5e.png)


Given that there are already viable approaches to this in ASS and adding new override tags requires coordination among and implementations in all major ASS renderers and even if done well will come with some transition woes until new renderer versions are widely available, I do not think it is a good idea or worth it to do so. *(If any other maintainer wants to do that though, feel free to reopen and pursue this.)*

Besides, for your usecase there are also other options not requiring any format changes.
You using `sub-ass-override=strip` tells me you're not watching ASS subs containing typesets as those get destroyed by this setting. This makes it even simpler.

 1) Use an mpv (lua or js) script to duplicate all (converted and stripped) text subtitle events. Keep one on the default layer, make the actual text transparent (`1a&HFF`) and add blur. Move the other one one layer up and make everything but the actual text transparent and add blur. You could e.g.:

 2) If mpv allows running shaders on only the subtitle layer: run a blurring shader on the subtitle layer.

 3) Ask mpv, if they want to allow specifying arbitrary subtitle canvas sizes rather than just actual rendering resolution and native video resolution. This would allow you to choose a resolution smaller than video res.

**Comment by astiob** [comment]
> make the actual text transparent (`1a&HFF`)

This isn’t very good: it cuts out the text from the shapes before applying blur, causing the text–border boundary to be effectively blurred twice and hence too thin/transparent (plus it may exhibit a subpixel gap even before the blur). Assuming you’re using fully opaque `PrimaryColour` for the text, this doesn’t match ASS’s standard border blur, and you can do better.

If you know that the blur radius is small relative to the border width, you can just give the bottom layer the same `\1c` as your `OutlineColour` (and ensure your `PrimaryColour` and `SecondaryColour` are [both fully opaque](https://github.com/libass/libass/blob/4eb5c6dcff48628772568a7a185fbb1b0e57c014/libass/ass_render.c#L2465-L2467), or add `\1a0\2a0` to make them so), so that it looks like a solid-colour widened block with some blur on the outside.

If not, you need to move the line and apply shadow (`\shad`, `\xshad` or `\yshad`) such that the _shadow_ ends up in the desired position of the text. Usually, one moves the non-shadow completely off-screen and ensures that the `PrimaryColour` is [anything _but_](https://github.com/libass/libass/blob/4eb5c6dcff48628772568a7a185fbb1b0e57c014/libass/ass_render.c#L2458) fully transparent (or adds `\1a0` to make it so). But to avoid having to know the screen size, another option (if I’m not forgetting how karaoke tags work) is to make `SecondaryColour` and `OutlineColour` fully transparent (`\2aFF\3aFF`) and [to add](https://github.com/libass/libass/blob/4eb5c6dcff48628772568a7a185fbb1b0e57c014/libass/ass_render.c#L2456-L2457) `\K0` or `\ko0`—this should allow the non-shadow to remain on-screen and just make it invisible. In any case, do note that the end result may look good but will not be exactly the same as rasterizing the non-blurred subtitles into a PNG and blurring that PNG, as each layer is still getting blurred separately. Blurring multiple things at once is completely impossible in ASS and in libass.

Now, if you want to make a generic script, you’ll presumably want it to work when multiple events are on screen simultaneously, so to move the non-shadow, you can’t use `\pos`; instead, you can use `MarginV` offset from your main style’s `MarginV` by a constant. Then again, I have no idea what API such an mpv script would have available, so this may or may not be possible. I certainly remember margins not being exposed in OSD API before, but I have no idea whether this is the same API or whether they’ve been added in the meantime.

> assuming ASS supports what I have in mind

It does not, which is why you had to open this issue ;-) If it did, this would most likely be purely an mpv issue of providing a configuration option to activate this. And this is the same reason that we’re not eager to add this.

> I am sure [the majority of users] would also prefer softer-appearing subtitles - they just don't know it yet :)

For what it’s worth, the widely voiced opinion throughout these ten or so years has been the opposite: that’s why `blend-subtitles=video` isn’t the default, even though the default is actually known to break some complex ASS subtitles.
