### ISSUE TITLE
Feature request: separate outline and background

### ISSUE THREAD

**Issue by j77h** [libass/libass#657]
It would be very useful to be able to render subtitles with 
a semi-transparent background AND a solid outline.
ASS v4 makes you choose one or the other. 
Hopefully ASS v5 will allow both, each with its own color, alpha, and width.

It would also look better if the background could extend 
further horizontally beyond the ends of the text lines.
Currently there is more background 'margin' above and below the text than at the sides.

**Comment by TheOneric** [comment]
It isn't fully clear what you mean with “background”. From the supposed limitations I'm guessing you probably mean BorderStyle=3, but could you clarify and describe what your usecase is?: Are you authoring ASS subs for distribution, using player settings to adjust the appearance of (non-ASS) subtitles, developing some application generating transient ASS to render custom things, ...?

I have no idea what the second paragraph is about. Please elaborate.

Also:
> ASS v4

There is no “ASS v4”. The only thing corresponding to a `v4` would be version 4 of SSA, which is also supported by libass. ASS refers to itself as `v4+`/`v4.00+`.

**Comment by j77h** [comment]
> There is no “ASS v4”.

I meant v4+

> It isn't fully clear what you mean with “background”. 

Sorry, I didn't imagine that it might have more than one possible meaning. :)

> I'm guessing you probably mean BorderStyle=3

Yes, "BorderStyle=3" is how we make a background.

This is exactly what I'm asking for improvement of:
outline and background each require a different value of BorderStyle,
so it's not possible to have character outline within a background.

I've seen output from other apps in which this is possible,
and noted that subtitles can be easier to see when they have 
BOTH semi-transparent background AND thin solid outline.

> could you clarify and describe what your usecase is?

I provide technical help for a number of people who translate subtitles.
Sometimes we burn subs on a video using ffmpeg+libass.
Most of the time they use ASS in VisualSubSync while translating.

I'm preparing to write a Qt6/Python app 
that will render ASS subtitles via libass on video in mpv.
Its purpose is to make it easier to review and edit ASS subtitles,
as 'non-technical' users don't like editing ASS files directly.
(Also VisualSubSync is rather complex for translation reviewers 
who work only with text, not timing, and it does not run on macOS.)

Having Qt itself render subtitles over the video 
seemed difficult or impossible last time I checked,
and I'm sufficiently familiar with ASS that it's easy for me.

> I don't understand what the second paragraph is referring to.

I'll re-write it as separate issue.

**Comment by TheOneric** [comment]
> I provide technical help for a number of people who translate subtitles.
> Sometimes we burn subs on a video using ffmpeg+libass.

Do the subs always end up as hardsubs or do they sometimes remain softsubs getting distributed as ASS?

If it always ends up as hardsubs and all tools involved use libass, `BorderStyle=4` may suit your needs. It replaces the shadow layer with a box around the whole event, see [here](https://github.com/libass/libass/wiki/Libass'-ASS-Extensions#borderstyle4) for details and an example image.
`BorderStyle=4` is not "standard" ASS though, but a libass-specific extension mostly intended for hardsub and on-the-fly converted subs. As such, it also isn't as stable as VSF-compatible features and sometimes behaviour may be tweaked a bit as mention in the wiki.

If the goal is to distribute the result as softsub ASS, then I'm afraid there's no out-of-the-box solution available. Same if you want to box each line individually, rather than the whole event like `BorderStyle=4` does.
You could however, use a layer behind the subtitles to add your own background. For example a transparent vector drawing can be added to emulate `BorderStyle=4`. Or to get “`BorderStyle=3` but with independent colour and alpha”, duplicate the Event, with `BorderStyle=1` in the front but in the back layer use `BorderStyle=3` and disable shadow, adjust `\(x|y)bord` and set all colours and transparencies to the one desired for your background. You'll need to also adjust any existing inline tags affecting those values. The latter will give something like this:
![borderstyle3_in_background_layer](https://user-images.githubusercontent.com/1668471/199084819-c13e1864-f937-47e4-89ff-5a041ffb6f72.png)


If your writing your own editing software anyway *(or by writing an Aegisub script, see below)*, you could automate the addition of a background layer.

> Most of the time they use ASS in VisualSubSync while translating.
> [...] (Also VisualSubSync is rather complex for translation reviewers
> who work only with text, not timing, and it does not run on macOS.)

From looking at VisualSubSync's wiki and source repo, it looks like all development stopped in 2013 and it doesn't appear to use libass, but a custom VSFilter fork *(not sure if it includes required API/ABI changes or if it can be swapped for a standard VSFilter)*. Thus any changes/extensions in libass or (perhaps) even standard VSFilters cannot be used in VSS.
Did you/those you help consider switching to e.g. (a maintained fork of) Aegisub? While it doesn't help with the complex interface, it does work on most Desktop platforms and can use libass to render subtitles. *(E.g. [wangqr/Aegisub](https://github.com/wangqr/Aegisub), [arch1t3cht/Aegisub](https://github.com/arch1t3cht/Aegisub) or [TypesettingTools/Aegisub](https://github.com/TypesettingTools/Aegisub) with the latter being supposed to eventually be moved to Aegisub/Aegisub once some things are settled.)*

**Comment by astiob** [comment]
Do note that semitransparent BorderStyle 3 (that is, standard ASS) background exhibits overlap between lines, as seen in the screenshot above. This happens always, and the only way to avoid it is by manually breaking lines (as opposed to automatic wrapping), putting them into separate `Dialogue` events and applying `\clip(x,y,x,y)` with explicitly calculated coordinates to each event. Similarly, you may want to apply `\clip(x,y,x,y)` if you use explicit vector drawings to ensure they look good at any rendering resolution. Of course, once you’re splitting lines manually, you can also adjust line spacing if you wish, and in particular, you could move the lines wider apart so the backgrounds don’t overlap (unless the user zooms out a lot…).

---

> I don't understand what the second paragraph is referring to.

It depends on the font at least somewhat, but with many fonts (or maybe my experience has just been with unfortunately chosen fonts) a box border with `\bordX` (or `\shadX` for BorderStyle 4) feels like it’s a lot narrower on the left and right than on the top and bottom. Like, the picture in your last comment looks decent, but it probably required `\xbord(a whole lot more than ybord)` to look this decent, and that’s precisely what OP would like to happen automatically.

**Comment by j77h** [comment]
Thanks to both of you for the excellent suggestions.

BorderStyle 4 looks like what I wanted.

My request was for a feature in a future version of LibASS, 
as we don't happen to need it right now, but it's good
to see that the feature exists already.

Currently most of our work is for YouTube, and I provide ASS styles
that mimic the appearance of YT subs in Sans-Serif at 200% font size.
This allows translators to know that their text will fit in the space,
without having to watch the character count in VisualSubSync.
(Character count is a bit silly when characters are not fixed-width.)
They have BorderStyle 3, at 50% transparent, and we don't 
worry about the overlap because it's not there on YouTube.

If \bordX or \shadX extends the background sideways, that will help,
though I prefer to use settings only in Styles if possible, 
to keep the text-edit area free from styling codes.

Btw, YT adds a no-break-space at the start and end of each line 
to make their background wide enough at the sides.
(You can see it in a browser's inspector, if you can find the captions ;)
_ _ _ _ _

I considered Aegisub for translators in 2007, but in 2008 found 
VisualSubSync, and realized it would be much easier for them.
Even so, we had to show most of them how to use it (via TeamViewer).

Because of VisualSubSync's age, and lack of other suitable apps (IMO),
I've been thinking of making a Qt/Python app (I can't do C/C++) 
that controls an instance of mpv on which the subs are displayed,
while providing an uncluttered text-editing area in a Qt window.
I'm pretty sure mpv (or ffmpeg in its backend) 
is keeping pace with libass development.

If we ever make subs to be viewed on PC as soft subs,
we would advise people to use SMPlayer or [iina](https://github.com/iina/iina).
They both use mpv as their backend.

**Comment by TheOneric** [comment]
> BorderStyle 4 looks like what I wanted.

I'm assuming this means this can be closed then?

> If we ever make subs to be viewed on PC as soft subs,
> we would advise people to use SMPlayer or [iina](https://github.com/iina/iina).
> They both use mpv as their backend.

As alluded to before, extensions not intended for softsubs aren't guaranteed to be fully stable. So if you ever want to release ASS softsubs, you may want to (re)consider converting to standard ASS and making a final QA pass against VSFilter, which will also protect you from accidentally relying on a libass bug.
