### ISSUE TITLE
mpv's OSD doesn't find any fonts

### ISSUE THREAD

**Issue by lavara123** [libass/libass#658]
[osd/libass] Glyph 0x34 not found, selecting one more font for (sans, 400, 0)

![Ekran görüntüsü_2022-10-31_14-19-31](https://user-images.githubusercontent.com/12005386/198996292-2c7e0afe-e25d-450b-95e2-b91eeb06dcb4.png)

**Comment by TheOneric** [comment]
All log messages shown are about the OSD not actual subtitles. Make sure there's a font with sufficient Unicode coverage available to the OSD and sub renderer *(in this case it seems like no font at all is available)*.

In general we need more info to properly help, like a proper full log, version of libass used, how it is configured, what system it runs on, etc. This case seems likely to be due to a misconfiguration in mpv though and not a libass issue. If after investigating your mpv setup and configuartion you still think this is a libass issue, provide more info. Or if you solved your issue, please close this.

**Comment by lavara123** [comment]
> All log messages shown are about the OSD not actual subtitles. Make sure there's a font with sufficient Unicode coverage available to the OSD and sub renderer _(in this case it seems like no font at all is available)_.
> 
> In general we need more info to properly help, like a proper full log, version of libass used, how it is configured, what system it runs on, etc. This case seems likely to be due to a misconfiguration in mpv though and not a libass issue. If after investigating your mpv setup and configuartion you still think this is a libass issue, provide more info. Or if you solved your issue, please close this.

I installed the **ttf-dejavu** package and it was fine. Weird
