### ISSUE TITLE
Where *is* The Documentation?

### ISSUE THREAD

**Issue by j77h** [libass/libass#659]
In the notes for Release 0.16.0 you wrote 
"The documentation has been expanded 
and multiple errors in it have been fixed. 
It may be worthwhile to reread the documentation ..."
but you don't give a link to it.

In the main README.md there's no link to it,
although there are links to some very old incorrect documents.

None of the titles in the wiki looks like it's 
"The Documentation" for the current version.
Is ASS v4.1 current? Or is it past or future?

A week ago I asked a question, 
to which the answer was "use BorderStyle=4".
Today I discovered that it's been around since 2017!
I produced hours of documentary subtitles in 2019, 
with libass via ffmpeg, and really wanted something like BorderStyle=4,
but at the time, I had documentation only from moodub and Aegisub,
and wasn't aware that I needed to search for ***Lib***ass documentation.

Until today, I had no idea that newer better documentation exists.
And I'm still not sure where it is!

Just guessing now :
It looks like we have to open several pages in the wiki
and hope that we'll find there what we need to know.
Haven't seen any sign of a document elsewhere...

Please put up a main central document 
for **current** LibASS, and ASS styles (not VSfilter)
-- a complete replacement for moodub and Aegisub docs --
where google searches (for just "ASS documentation") will find it,
and hopefully soon give it higher rank than Aegisub.
It could contain links to specialized docs such as those in the wiki,
but it needs to make it clear which docs have current information,
which are old, and which are for planning future features.

Or at least, in the main readme, put a link to 
the main doc in the wiki for *current* ASS usage.

Many open-source projects have something on readthedocs,
or at least a comprehensive main readme on github,
so it's puzzling that libass's documentation seems to be hiding.

**Comment by astiob** [comment]
The documentation for _libass,_ a C library, is in its C header files:
https://github.com/libass/libass/blob/master/libass/ass.h
https://github.com/libass/libass/blob/master/libass/ass_types.h
Admittedly, an HTML version could be generated from this and put on the Web for ease of access, but this isn’t what you seem to be looking for anyway.

There is no comprehensive documentation for ASS, and libass does not _define_ ASS. VSFilter _is_ the definition of ASS, and any libass extensions are not “current ASS”; they’re just libass extensions. We try to document them on https://github.com/libass/libass/wiki/Libass'-ASS-Extensions, but they’re subject to change. Beyond this, libass just tries to emulate VSFilter as closely as possible, specifically guliverkli2 and xy-VSFilter as a DirectShow filter.

Better documentation for ASS itself would be useful, but it would be a significant new undertaking. I do think one could improve on Aegisub’s docs, although the potential for comprehensiveness is limited by the fact nobody actually knows fully how ASS (that is, VSFilter) behaves and we learn new things all the time. As of now, Aegisub docs are probably still the best place if you’re looking for just one place.

**Comment by j77h** [comment]
Thanks astiob, now I know where all the documentation is.  ;)

In case it wasn't clear,
my main point for the longer term was

> a complete replacement for moodub and Aegisub docs --
where google searches (for just "ASS documentation") will find it,
and hopefully soon give it higher rank than Aegisub.

because your extensions were not mentioned by Aegisub, 
and I didn't come across them when searching 3-4 years ago.

Right now www.aegisub.org times out, and 
so does your link to docs.aegisub.org/latest/ASS_Tags/,
while devel.aegisub.org redirects back to github.com/Aegisub/Aegisub,
where I cannot find that kind of documentation.

It's no problem for me, as I have copies of everything 
that I got from moodub and Aegisub about 10 years ago.

Is it time for you to take control of ASS now?
Make a final VSfilter-compatible release,
proclaim ASS v 4.5, and move ahead independently now,
rather than waiting until you've finished planning ASS v5...?

**Comment by TheOneric** [comment]
> Today I discovered that it's been around since 2017!

`BorderStyle=4` has been around since libass 0.12.0 *(as mentioned in its release notes)*, so 2014 actually. 2017 (0.13.7) was when adjusting padding via `\(x|y)shad` became possible.

> because your extensions were not mentioned by Aegisub

Aegisub’s main purposes is authoring (more or less) portable softsub ASS, so naturally any unstable renderer-specific extensions have not much reason to be in its documentation.
An analogy: You also wouldn't expect a publication claiming to teach the basics of C99 to necessarily mention `tcc` having a `-b` compiler flag to insert run-time memory bound checking. If you want to know about `tcc`’s bells and whistles you should read `tcc`’s docs.

> Make a final VSfilter-compatible release

No.
Imagine libpng decided to from now on only parse and care about a new "upgraded" PNG format which yields better compression but isn't quite compatible with the origin
al PNG format. Suddenly, all your existing images could either no longer be opened, or be opened but display corrupted. People would understandably be not happy, as this is a bad idea only causing unnecessary trouble.

One day there might be a new subtitle format (or format revision) which is at least as powerful as ASS but well-defined and quirk-free, but creating such a format without repeating ASS’ mistakes in a different form requires enormous work and time, so best don't hold your breath.
