### ISSUE TITLE
Incorrect border scaling in the x direction when cropping or resizing the video to a different aspect ratio

### ISSUE THREAD

**Issue by llyyr** [libass/libass#689]
This issue is reproducible in mpv with any video filter that changes the video dimensions, such as `--vf=crop=w=500:h=1000` for a 16:9 video. I can provide samples if needed.

It's a regression from https://github.com/libass/libass/commit/f08f8ea522d20dd9985544c636e45e4984a0d743

Before that commit: 
![image](https://user-images.githubusercontent.com/6298234/230707861-5b581d63-5553-4f81-a909-f88e33adc1f8.png)

After that commit: 
![image](https://user-images.githubusercontent.com/6298234/230707876-58eeb939-4c4b-4ce4-80e4-92a781a48621.png)

I don't have access to any video player that uses vsfilter, so I can't compare if the behavior is the same or not.

**Comment by TheOneric** [comment]
This is correct and intended behaviour for `PlayResX: 1920` subs on a 500px display width video and we confirmed on IRC it also correctly affects all other `PlayResX`-sensitive features.

For pan-and-scan cropping scenarios, libass provides `ass_set_margins` to keep the sub appearance unchanged and (attempt to)  position subs optimally. mpv already uses this in its own pan-and-scan and runtime zoom features afaik.
However, you are not using mpv’s builtin cropping features, but inserting a ffmpeg cropping filter early in the chain so mpv (by design) acts as if the original video were 500px wide and not a 1920px-wdith video cropped to 500px.

To get your desired result you must either use one of mpv’s smart cropping methods already setting libass’ API margins, or set fitting API margins yourself. If the latter isn't possible yet or none of the existing smarter cropping methods fit your need, this is a feature request for mpv. There is nothing libass can do about this by itself and the required functionality already exists.

Should it turn out there are problems even with correct API margins, please file a new issue with a fully functional ASS sample, video excerpt and all required fonts.

**Comment by llyyr** [comment]
In addition to my comment from #690, a proposed solution could be libass offering a toggle to enable/disable PlayResX-sensitive scaling? mpv could then turn it off at runtime, or offer a toggle for the user to choose.

**Comment by astiob** [comment]
Subtitles, in general, don’t support hard pre-cropping at all. As you can see in the pictures you’ve provided, the subtitles aren’t getting cropped at all, but rather the layout is redone from scratch within the 500 px width that you retain in the video. If this is what you want, you should accordingly set `PlayResX: 500`, e. g. via a user override if nothing else. If the subtitles were to contain anything more complicated than plain text (position anchors, clips, rotations…), it would be completely distorted by this kind of cropping regardless of the commit you quote.

**Comment by llyyr** [comment]
I accept that it would be completely distorted, but at least the plain text would still be fine, which it was on 0.16.0. I don't crop a video and somehow magically expect libass to render everything correctly, but it should at least not break what used to not be broken.

I don't know who desires vector drawing, outlines, shadows, and font spacing to be scaled in the x-axis, or why this is desired except vsfilter did this so we have to do it too. Even if there is a very good reason, I don't know if that reason is good enough to break things that worked. A way to toggle scaling in the x-axis for these features would be sufficient, mpv could bind it to a key or just offer a command line flag similar to `--sub-ass-vsfilter-scaling-compat` or something.

**Comment by astiob** [comment]
It _was_ broken, though. The original commit contains plenty of links to issue reports that were fixed.

**Comment by astiob** [comment]
It _was_ broken, though. The original commit contains a link to an issue report that it fixed (you can dive deeper by following more links). And that was a real, out-in-the-wild subtitle file that we failed to render at stock settings, in a stock setup, with no weird crop filters involved. And as detailed in the commit message, while fixing this, we discovered our handling of anamorphic video was broken as well, and this change was an integral part of fixing it.

(Reposting because my wording the first time was so strong it was a lie, sorry.)

**Comment by TheOneric** [comment]
Moving @llyyr’s recent [comment from #690](https://github.com/libass/libass/issues/690#issuecomment-1502429117) over here, since it’s only about cropping:
> I want to crop videos to take screenshots while the basic plaintext subtitles (and toptitles with {\anX}) are visible fully and rendered in the same way as if the video wasn't cropped at all, just with different linebreaks to fit on the screen.
>
> Panscan doesn't work for this because the subtitles might not be in the frame at all depending on the region I'm cropping. Just inserting a crop filter used to work because the actual font rendering, and effects related to it (borders, outline, font spacing) weren't affected by the scaling at all. It's fine if actual typesetting is broken, I don't expect it to not be broken when I'm cropping the video in ways it isn't supposed to be.
>
> I don't know if this is that niche of an use case, a lot of people I know take screenshots this way and they probably just don't know the right place to report it.
>
> If libass can't expose a toggle for x-axis scaling for borders and shadows, then I'm left with very few workarounds to preserve the behavior I desire from it. Maybe just staying on 0.16.0, or manually setting PlayResX, MarginL, MarginR when cropping...

**Comment by TheOneric** [comment]
> Just inserting a crop filter used to work because the actual font rendering, and effects related to it (borders, outline, font spacing) weren't affected by the scaling at all.

It never really worked well this way. Your subtitles apparently just happened to be simple enough to not run into problems resulting from cropping without API margins.
Duck-taping some partial x-scaling override together or sticking to an old, unsupported libass version with memory bugs, does *nothing* to address those problems. And there long exists an intended way to deal with cropping which solves your problem in both old and new versions of libass.

> If libass can't expose a toggle for x-axis scaling for borders and shadows, then I'm left with very few workarounds

No need for workarounds. A proper solution exists (and has been mentioned several times already).

> Panscan doesn't work for this because the subtitles might not be in the frame at all depending on the region I'm cropping.

Non-positioned, dialogue-like events will always be in frame with API-margins. You probably didn't configure mpv to use API margins with native ASS, see `sub-ass-force-margins`. I forgot mpv doesn't let native ASS subs use margins by default so I didn't mention it until now, sorry. (But tbf you never mentioned dialogue getting cut of with panscan before, only screenshots not getting cropped to the visible area.)
The only possible remaining issue, is SSA and `v4+`-ASS not natively distinguishing between dialogue and typesets; in rare cases libass guess about what events are typesets may be off, but any other method will face this problem too.

---

One final time, here is how to correctly deal with cropping such that typical dialogue stays unchanged in frame and (most) typesetting sticks to the same video area as without cropping:

**The _only_ solution to get your desired proper rendering with cropping is enabling and using `ass_set_margins`.**
Everything else suffers from a lack of information and will fall apart on complex subs or other deviations from its expected scenario. It is plain *impossible* for libass to handle cropping well without getting API margins from the player.

Thus either **a)** use one of mpv’s inbuilt cropping features which already sets API margins, **b)** file a feature request *with mpv* to improve one of those methods if they don't fit your needs already or **c)** file a feature request *with mpv* to allow you to set your own API margin values and continue to use ffmpeg’s `crop` filter.
