### ISSUE TITLE
Incorrect border scaling for srt subs

### ISSUE THREAD

**Issue by llyyr** [libass/libass#690]
A regression between 0.16.0 and 0.17.0.

0.16.0: 
![image](https://user-images.githubusercontent.com/6298234/230709227-345c3fa2-6f45-4394-a8a7-eebaf945dc92.png)

0.17.0: 
![image](https://user-images.githubusercontent.com/6298234/230709239-2f02c1f0-ad5b-4608-acb6-1f37b1948358.png)

# To reproduce

`printf %s\n 1 "00:00:00,000 --> 99:00:00,000" "test sub" > test.srt`

`mpv [video file] --sub-file=test.srt`

**Comment by TheOneric** [comment]
As written before on IRC, libass is an **ASS** and **SSA** renderer and never parses or otherwise deals with SRT itself. If a converter produces ASS not matching its desired rendering, this is an issue with the converter not libass. You already identified this converters problem on IRC: it sets `PlayRes{X,Y}` without regard to the video’s display aspect ratio.

We already have some API-toggable features to which can be enabled with ont-the-fly conversions to assist with some particularly hard to convert jobs, but *a)* this is not our main foucs and *b)* the existing API already contains everything needed to workaround known-broken converters like this (keeping `PlayResY` and adjusting `PlayResX` to match the video’s *display* aspect ratio). If applying such a workaround though, be careful to not overwrite intentional `PlayRes{X,Y}` values.

**Comment by llyyr** [comment]
The issue here is that libass decided that it needs to replicate buggy behavior from vsfilter that it didn't for the last decade, breaking everything in the ecosystem that relies on it in the process.

Outlines, shadows etc. didn't used to rely on the PlayRes to be scaled properly, you still could get the desired rendering with 0.16.0 or with a patch reverting the commit that breaks it.

There's nothing a converter could do here because when converting srt -> ass, the playres isn't always known, so it shouldn't rely on it.

**Comment by astiob** [comment]
This isn’t even buggy behaviour; this behaviour is actually much more intuitive than what libass did before. `PlayResX` exists to be used.

Quite frankly, ASS is not the universal catch-all format that everyone converting subtitles wants it to be; it has its own specifics (even before diving into VSFilter bugs), and it’s not always trivial or even possible to convert other formats to ASS—it has never been. Converters have relied on undocumented and unstable libass behaviour instead of even attempting to rely on the underlying format, so you can hardly blame libass.

That said, we do try to keep compatibility where possible: for example, we detect old FFmpeg-converted files and switch up some defaults to better match what libass used to do back then. @TheOneric Might it be feasible to do the same for x-scaling, or would it break FFmpeg ASS-to-ASS conversions? If by any chance it inserts the FFmpeg version header in every file it produces, then I don’t think this is possible without breaking ASS-to-ASS conversions. (Or are those broken anyway due to the existing FFmpeg compatibility checks? I forget what our exact logic is.)

I do agree it would, in principle, be good to have a way to specify aspect-ratio-independent sizes. But that’s a bigger format change, and it’s not obvious how it could coexist with things such as 2D anchor points.

We could certainly add an `ASS_Feature` for just toggling border/shadow x-scaling, which e. g. mpv could set for converted subtitles. It wouldn’t help if you tried to convert SRT to ASS with FFmpeg and save it in a file, though.

**Comment by llyyr** [comment]
> PlayResX exists to be used.

Why is it only used for certain features then? Why is it that my border has different scaling than the text itself? I could understand if the text scaled with PlayResX as well, but it doesn't. I don't know what's intuitive about text and borders/shadows having different scaling.

> Quite frankly, ASS is not the universal catch-all format that everyone converting subtitles wants it to be; it has its own specifics (even before diving into VSFilter bugs), and it’s not always trivial or even possible to convert other formats to ASS—it has never been. Converters have relied on undocumented and unstable libass behaviour instead of even attempting to rely on the underlying format, so you can hardly blame libass.

I'm not asking it to be an universal format, the issue here is present with a conversion so barebones that you could generate the source file with a single `printf`. There's nothing present here except plain text.

> We could certainly add an ASS_Feature for just toggling border/shadow x-scaling, which e. g. mpv could set for converted subtitles. It wouldn’t help if you tried to convert SRT to ASS with FFmpeg and save it in a file, though.

I think this would be sufficient, video players convert srt -> ass internally so they would be able to toggle it by themselves when needed. And the user could toggle it with a compatibility flag if needed.

**Comment by astiob** [comment]
> Why is it only used for certain features then?

It _was_ only used for certain features, and that’s what you’re asking us to bring back: e. g. positions, clips, margins, but not the things listed in https://github.com/libass/libass/issues/171#issuecomment-629902664. Now, it is used for _every x-axis feature there is._

Font size is the odd one out, indeed, and it’s most definitely a pain point, but this is because it’s a single parameter whose visual effect isn’t single-dimensional. In fonts, size can affect the letter form, and you can’t scale a single number along two axes simultaneously; you have to pick one. And font size is usually some form of height, and in particular in ASS, it is synonymous with line height (subject to small rounding error), so the y axis is chosen for scaling it. Now, current libass at default settings doesn’t actually use variable font size at all and instead stretches a fixed-size font variably along each axis, so it could in theory apply both scales to font size at the same time, so _this_ is the VSFilter bug if you will, and it therefore has a compatibility toggle: mpv’s `ass-vsfilter-aspect-compat` option. Our implementation might potentially change in the future to one where libass actually selects the appropriate font size, though, to better match VSFilter’s positioning [#21, #618] (and maybe letter form as a bonus if we’re lucky), at which point one of the axes would still have to be the dominant one, even if we were to emulate independent scaling along both axes. And even in current libass, you can explicitly enable font hinting, which again means font size is a single-number parameter that actually matters.

> I'm not asking it to be an universal format, the issue here is present with a conversion so barebones that you could generate the source file with a single `printf`. There's nothing present here except plain text.

But ASS _is not a plain-text format._ And it never was. All this shows is that a single `printf` is not enough to convert something to ASS—and it never was: one needs to handle override tags, line breaks, you name it.

> I think this would be sufficient, video players convert srt -> ass internally so they would be able to toggle it by themselves when needed.

I’m not too opposed to this idea, but I do want to point out again that players have the video’s width anyway, so they can already just set `PlayResX` for such converted subtitles, which would ensure the output looks correct in all versions of libass, old and new alike.

> Font spacing should probably be a part of this too though

Could you elaborate? What font spacing are we talking about here?

**Comment by llyyr** [comment]
I'm talking about the {\fsp} tag.

> I do want to point out again that players have the video’s width anyway, so they can already just set PlayResX for such converted subtitles

That's true, but you kind of need the flag to fix it in the scenario where a crop filter is inserted anyway, so it would handle both. I guess it would be a discussion for mpv's side of things if they should set PlayResX or use the toggle in the case of srt conversion, but that can be left for the implementation on mpv's side.

**Comment by llyyr** [comment]
This is a slight tangent, but why does libass pursue vsfilter to the extend of even replicating its bugs and inconsistencies? I don't know if anything uses vsfilter or a fork of it anymore, even Aegisub, which is primarily used to create ASS files uses libass. People have for the last decade targeted correct rendering with libass, not vsfilter, so from a user's perspective, it would make more sense for libass to stick to what it has been doing rather than please the minority. Even if the argument is that there are old subtitles that target vsfilter, there are surely more subtitles written in the last decade that target libass. And it would be perfectly acceptable to me if I had to toggle a flag in my video player to correctly render old subtitles, rather than have to toggle a flag to correctly render relatively newer subtitles.

**Comment by astiob** [comment]
> you kind of need the flag to fix it in the scenario where a crop filter is inserted anyway

This assumes the initial subtitles look the same with or without the flag. If they don’t, you need an additional correction factor, which a simple `ASS_Feature` can’t provide. Personally, I think the behaviour you’re showing in pictures in #689 is exactly what I would desire from the crop filter: if I ever wanted to use it in lieu of mpv’s pan & scan, it would be to fix a letterboxed video for subtitles that were authored for a different video stream. But of course, the more power to the user, the better.

> This is a slight tangent, but why does libass pursue vsfilter to the extend of even replicating its bugs and inconsistencies? […] People have for the last decade targeted correct rendering with libass, not vsfilter

[citation needed]

Even if we assume for the sake of argument that this is true, people still have plenty of older subtitle files that they just want to work correctly. We keep getting reports about incompatibilities, too. Fresh new files, too: e. g. #634 was about one.

Also, libass’s rendering behaviour is in constant flux and has never been stable, making targeting libass somewhat meaningless. Our stance has nearly always been that we’re aiming for VSFilter compatibility, so if you make a file that plays in VSFilter, libass will adjust to match if it has to.

> I don't know if anything uses vsfilter or a fork of it anymore, even Aegisub, which is primarily used to create ASS files uses libass.

Aegisub absolutely does still use xy-VSFilter on Windows. libass is also provided as an option. So is VSFilterMod, which hopefully nobody ever uses for softsubs.

> there are surely more subtitles written in the last decade that target libass. And it would be perfectly acceptable to me if I had to toggle a flag in my video player to correctly render old subtitles, rather than have to toggle a flag to correctly render relatively newer subtitles.

I actually agree with what I think is your overall point, with one small but important adjustment: I want my player to handle _most_ (not necessarily more recent) files correctly by default and have toggles to handle the minority. But just as you assume that newer = more = targeting libass, other people have other assumptions, so I’d like some supporting data we could reliably base decisions on. Personally, I don’t believe that newer = targeting libass in general, but I do think some particular VSFilter misfeatures that we’ve recently begun emulating are likely unused and we regressed by adding them. We’ve been discussing this internally for a while and trying to set up some kind of large-scale subtitle statistics database, but we’re not yet at a point where we can actually extract useful data out of it. Without such data, the only settlement we’ve been able to come to has been that we stick to emulating guliverkli2/xy-VSFilter faithfully.

If you do have a particular feature in mind where you can show we’re breaking more cases than we’re fixing, I’d genuinely love to see the evidence and discuss toggling the default. Our main interest really is in straightforward native-ASS playback, though.

In our internal discussions, a recurring point has been that the arithmetic should not allow high-quality manually-crafted subtitles to be outmatched by a spam of nearly-identical, automatically-generated streams such as when robotized groups release multi-resolution rips of third-party subtitles without even checking them. Personally, I’d rather just focus on something like “number of impressions” as the metric, but we also have #589 for potentially handling individual high-profile offenders via heuristics.

**Comment by TheOneric** [comment]
> There's nothing a converter could do here because when converting srt -> ass, the playres isn't always known, so it shouldn't rely on it.

It’s simple, if there isn’t enough information to correctly convert one format into the other, then just **ᴅᴏ ɴᴏᴛ ᴄᴏɴᴠᴇʀᴛ**. Nothing is gained by covnverting a standalone SRT file to an incorrect ASS file.

>  if the text scaled with PlayResX as well, but it doesn't

Additionally set `LayoutRes{X,Y}` and it will.


>  Converters have relied on undocumented and unstable libass behaviour instead of even attempting to rely on the underlying format, so you can hardly blame libass.

And that’s not even all; ffmpeg continues to also use a `\\` escape which does not and never did exist in libass or any ASS renderer afaik. Presumably no one ever tested it.


>  @TheOneric Might it be feasible to do the same [ffmpeg-detection] for x-scaling, or would it break FFmpeg ASS-to-ASS conversions? If by any chance it inserts the FFmpeg version header in every file it produces, then I don’t think this is possible without breaking ASS-to-ASS conversions. (Or are those broken anyway due to the existing FFmpeg compatibility checks? I forget what our exact logic is.)

From a quick test, at least `ffmpeg` cli appears to just copy subtitle data as is for SSA/ASS→ ASS/SSA.
We apply the same alternative SBAS default to all custom format line files and only match ffmpeg-generated files prior to them including SBAS. Matching is done by checking the signature comment (committed simultaneously with standard format lines), ensuring there’s only a single style named `Default` and encountered headers exactly matching pre-SBAS ffmpeg. *(Making it unlikely for complex ASS files to break even with a ffmpeg signature)*.

Regarding `PlayRes{X,Y}` ffmpeg does _not_ always use a fixed value, `ff_ass_subtitle_header_full` takes arbitrary values for them *(it’s even listed in `detect_legacy_conv_subs` comment). SRT’s decoder currently just uses fixed-3:4-`PlayRes{X,Y}` `ff_ass_subtitle_header_default`.
I just now noticed `libavcodec/libaribb24.c` uses it’s own copy of a pre-SBAS ASS header and chooses between two different `16:9` `PlayRes{X,Y}` values.
It’s possible decoders using custom resolutions might not be happy with our previous buggy x-scaling, or perhaps also be unhappy with our current scaling and rather expect (once again without actually checking what actually happens) letterboxing.

When we added the SBAS-workaround for known-broken old ffmpeg, we simultaneously made sure to fix future ffmpeg versions. If we actually add further special cases for known-broken converts, imho we absolutely should require also fixing the relevant converter.
All such special-casing based on magic comments(!) or fallible heuristics already makes ASS even less predictable, but doing so when even up-to-date ASS generators _rely_ on those makes it doubly bad.


> We could certainly add an ASS_Feature for just toggling border/shadow x-scaling, which e. g. mpv could set for converted subtitles.

I’m not sure why just borders and shadows are singled out and what kind of existing files is presumed to expect such behaviour.

**Comment by llyyr** [comment]
> Nothing is gained by covnverting a standalone SRT file to an incorrect ASS file.

This *incorrect* ASS file is rendered correctly on every version of libass from 2009 up until 0.17.0, which made those files incorrect for the first time in over a decade.

> I’m not sure why just borders and shadows are singled out and what kind of existing files is presumed to expect such behaviour.

Any srt converted to ass expects such behavior as shown in this issue, as well as any video player that supports cropping or changing the aspect ratio of the video. Borders, shadows and fsp should match the actual text rendered on the screen instead of scaling with the PlayRes.

I don't know the specifics of what ffmpeg or libass does, but I want my borders and shadows to match the actual text when when using a srt file in mpv, and the same for a native ass file when cropping the video in mpv. For the former, I could make the change in mpv to make it set the PlayResX to match the video aspect ratio but it would still remain broken in other video players using libass. For the latter, I don't know what change mpv can make besides me writing my own Lua script or something to watch whenever a crop or scale filter is inserted and calculating the new the PlayRes every time. I don't even know if that would work when the video is paused because mpv would have to re-render the subtitles which it doesn't when the playback is paused iirc. And another problem with any workarounds on mpv's side is that it has to render correctly for versions older than 0.17.0 as well as newer.

If there are actionable things mpv could do to make at least the dialogue text look like it is supposed to, then sure. But I don't know if there is a nice way to do it besides libass offering a way to allow the user to switch back to the old behavior.

**Comment by astiob** [comment]
> but it would still remain broken in other video players using libass

You seem to assume that all players use libass to render SRT subtitles and that all players convert them in the same way. This is not true. For example, I believe VLC doesn’t use libass for SRT at all, which is quite fair because libass isn’t an SRT renderer (as much as a lot of SRT in practice uses ASS override tags and expects them to be handled by VSFilter with all its quirks—but last I checked, FFmpeg stripped them out anyway for some reason, so mpv isn’t better in this regard).

Even if many players use FFmpeg to convert SRT to ASS on the fly, we sincerely think _FFmpeg’s_ converter should be fixed, not mpv’s. To be fair, I don’t know how easy this is: I wouldn’t be surprised if FFmpeg’s current architecture doesn’t allow the subtitle decoder to know the video resolution in the same file; but this information does exist and could technically be made available for this purpose.

> And another problem with any workarounds on mpv's side is that it has to render correctly for versions older than 0.17.0 as well as newer.

If PlayResX/PlayResY aspect ratio matches video aspect ratio, you’ll get identical border scaling in versions older and newer than 0.17.0. Older versions just ignore it for this purpose, so you can’t _break_ them by setting it to the right value.

And in the case of SRT-to-ASS conversions saved to a file and redistributed, having the right PlayResX will also make the border look right in VSFilter. Interoperability is the ultimate holy grail, and fixing FFmpeg’s converter to produce appropriate PlayResX is the only way to achieve it in any case.

> This _incorrect_ ASS file is rendered correctly on every version of libass from 2009 up until 0.17.0, which made those files incorrect for the first time in over a decade.

And it never rendered “correctly” in any non-libass renderer. It would be great if we could say that a file is correct if it renders as expected in _any one_ renderer, but we’d need some kind of mechanism to distinguish between files that target different renderers (and we’d need all renderers to support all the various modes). Unfortunately, there is no such mechanism. The best libass can do—and does—is heuristically try to guess what renderer a file is targeting, but even this can’t make a file more “correct” in my book if it uses implementation details that clearly violate the intention behind the ASS grammar, as I believe is the case here. This grammar is indeed a poor fit for plain-text softsubs, but this just goes to show that ASS not only suffers from poor implementation but also wasn’t designed for softsubs in the first place.

As I’m sure you know, libass has, over the years, rendered all sorts of things differently from other renderers or not at all. And indeed still does, but to a lesser extent with every passing year. We’re continuously making improvements for interoperability with other renderers (namely, VSFilter flavours). And yes, every such change breaks, for the first time, some files that were authored targeting libass. On the other hand, this makes it progressively easier to make a new file that actually displays the same way on any computer, in any player. This is why we say “targeting libass” isn’t something you should do in the first place: libass is a moving, unstable target. If we ever do introduce a stable, frozen set of behaviour for new files to target (and there _has_ been some talk of doing this), we’ll similarly have to continue supporting it forever, including our own quirks and bugs, just like we try to emulate VSFilter’s quirks and bugs currently.

> and the same for a native ass file when cropping the video in mpv

I continue to believe that this already works correctly. You can use mpv’s pan and scan to actually crop the output, or if you know what you’re doing, you can use the crop video filter and get exactly what it says on the tin for native ASS: full subtitles laid out on cropped video as if it were the video stream the subtitle stream was authored for. ASS subtitles are _always_ authored for particular video content, and the biggest video change you can expect to get away with before you have to adjust the ASS is to rescale the video to a different (possibly anamorphic) resolution provided you set LayoutResX/Y—and even this is a very recent addition.

You seem to have a very peculiar use case that happened to work well for you with some files previously but never did work in the general case in the first place. I can’t agree that this qualifies for the clear-cut “works correctly” vs “works incorrectly” distinction that you’re making it sound like. If anything, from my viewpoint, the new behaviour makes more sense, as your entire subtitles are compressed into the new window width, so if this isn’t what you want, maybe this just isn’t the right tool for the job. Now that I think about it, the fact that the font isn’t getting compressed may actually be a bug in mpv with respect to `vsfilter-aspect-compat` and `vf=crop`.

By the way, it’s hard to see what/why you’re even trying to achieve with this kind of cropping or why other people might want to do the same, so as much as I try to relate emotionally and want to help look for better alternatives, I’m not sure I can truly achieve this.

**Comment by TheOneric** [comment]
> (as much as a lot of SRT in practice uses ASS override tags and expects them to be handled by VSFilter with all its quirks—but last I checked, FFmpeg stripped them out anyway for some reason, so mpv isn’t better in this regard)

FFmpeg’s text sub decoder had an AVOption `"keep_ass_markup"` accessible via public API controlling whether to strip ASS markup or keep it ever since the decoder was added in 2012. The default is indeed to strip and it seems like mpv and FFmpeg’s `subtitle` and `ass` video filter do not expose a way to change it.

> I wouldn’t be surprised if FFmpeg’s current architecture doesn’t allow the subtitle decoder to know the video resolution in the same file; but this information does exist and could technically be made available for this purpose.

I know little about FFmpeg API and internal architecture, but even if the sub decoder doesn't (currently) automatically know the related video stream(s)’s sizes, it could still take them in via `AVOption`s. Filters do know the video resolution and this information is already used in the `subtitles` and `ass` filter for `set_storage_size`. (`AVFilterLink` also has `sample_aspect_ratio` which is currently unused in subtitle filters.)

**Comment by TheOneric** [comment]
Revised my previous post, SRT does not actually use FFmpeg’s text decoder, it has its own. Here’s what was added:

But SRT doesn't use the `text` decoder, but it’s own subrip decoder. This decoder in turn calls a common `ff_htmlmarkup_to_ass` function shared with (at least) SAMI and , which does then strip `{…}`-blocks. If this stripping is desired for SAMI, I guess `ff_htmlmarkup_to_ass` could be modified to take a `keep_ass_markup` parameter which SRT can set to true.
Interestingly, SRT events can sometimes also contain positioning data and FFmpeg’s decoder just assumes it’s referring to a `720 × 480` NTSC DVD frame and currently scaling to  to `ff_ass_subtitle_header_default`’s fixed `PlayRes*`.
