### ISSUE TITLE
Performance regression results in severe framedrops for typesetted subtitles

### ISSUE THREAD

**Issue by dokur0chan** [libass/libass#698]
### libass version & media player

- mpv version `0.35.0-533-g1f683401`
- Source of the mpv binary [mpv-x86_64-v3-20230715-git-1f68340](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230715/mpv-x86_64-v3-20230715-git-1f68340.7z)

shinchiro's Windows builds clone libass directly from the master branch. [Source](https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/libass.cmake)

### Regression behavior
The commit that causes the performance regression is likely [1a599b1](https://github.com/libass/libass/commit/1a599b1db748dfc07df98cd37d8603edb87da2fd) as documented in this pull request #693.
Windows builds that were created after this commit **(May 11, 2023)** suffer from the performance regression. Windows builds that were created before this commit do not suffer from the performance regression. The latest Windows build that this can be demonstrated on is [mpv-x86_64-v3-20230507-git-a1580b6](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230507-git-a1580b6.7z/download), which was created on May 7th. Due to the nature of the issue, it is likely not build or OS related, and can be presumably reproduced in different ways.

1. mpv-x86_64-v3-20230507-git-a1580b6 **(May 7, 2023)**

![20230507-git-a1580b6](https://github.com/libass/libass/assets/139610756/8359aea8-52c6-4fa7-94b9-52fb2bed536b)

2. mpv-x86_64-v3-20230514-git-9e716d6 **(May 14, 2023)**

![20230514-git-9e716d6](https://github.com/libass/libass/assets/139610756/820505b0-3e7b-4eb3-84ff-c09fa7c1fc46)

3. mpv-x86_64-v3-20230715-git-1f68340 **(Current mpv build)**

![20230715-git-1f68340](https://github.com/libass/libass/assets/139610756/5b2b88fc-5893-4ee3-a1bc-5b1169e9d46e)

All comparisons were done with `--no-config --fs --keep-open=always`. Dropped frame amount is more or less consistent, and is not affected by any combination of: `--vo=` `--hwdec=` `--gpu-api=` `--vd-lavc-dr=` `--blend-subtitles=`

### Sample file
https://files.catbox.moe/5ve34a.mkv

**Comment by TheOneric** [comment]
If mpv were to reset style overrides each frame even if they didn't change, yeah this commit could lead to perf regressions.

Interestingly though, I actually observe *better* perf after 1a599b1db748dfc07df98cd37d8603edb87da2fd. I am however also using an older mpv (`0.35.1`) instead of git master. At least a simple greps for changes containing `ass_set_selective_style_override` or `mp_ass_configure` doesn't change anything betwenn 0.25.0 and current master, but this does ofc not cover all possibilities.
```
mpv 0.35.1
gcc 12.2.0
./configure --enable-asm --enable-compare --enable-fuzz \
  CFLAGS="-O2 -g -ftree-vectorize -fvect-cost-model=dynamic -flto=auto" \
  LDFLAGS="-flto=auto"

2023.05.11: 1a599b1db748dfc07df98cd37d8603edb87da2fd
    --no-config 0
    user-conf   5

2023.04.04: 32dea3434dbd85f9fb2700b6863c1bd92f00b86f
    --no-config 24-27
    user-conf   27-29
```

Before we try to dig deeper, could you check different builds of libass with the same mpv build(setup) to confirm this is actually connected to libass and not a change in mpv, some dependency or the build tools?
If you already have a build setup, keeping the mpv binary the same and ust switching the dynamic libass lib would be easiest. If not, [MSYS2](https://www.msys2.org/) and [mpv-build](https://github.com/mpv-player/mpv-build) is probably helpful. You can select a specific libass commit by running `./use-libass-custom <commit-hash>` before rebuilding and after the initial setup. The relevant commit hashes are listed above in my measurements.
If you are not comfortable building mpv, do you know someone else who observed this regression and is willing to build mpv?

**Comment by llyyr** [comment]
> Interestingly though, I actually observe better perf after https://github.com/libass/libass/commit/1a599b1db748dfc07df98cd37d8603edb87da2fd.

This has not been my experience. I did some testing with libass-master and without that commit using mpv (both master and 0.35.1) with the following profile and no other configs set.
```
[bench]
audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
opengl-swapinterval=0
osd-msg1="FPS: ${estimated-display-fps}"
```

(although I did try both vo=gpu and vo=gpu-next, the performance is within 2-3fps of each other)

I isolated the part of the subtitles that cause the frame drops into a file here, and modified the timestamps for easier benchmarking [out.txt](https://github.com/libass/libass/files/12061432/out.txt) (the ext has to be txt due to github limitations, change it to .ass)

Then ran invoked mpv like this: `mpv --profile=bench --sub-file=out.ass [h264 video]`

To establish a baseline, I get heavily fluctuating 350-500 fps with very basic (srt conversion) subtitles on the same video with libass 32dea3434dbd85f9fb2700b6863c1bd92f00b86f, and 300-450 fps with libass master with the same subtitles.

On mpv master:
With libass master, I get 40 fps on vo=gpu, 38fps on vo=gpu-next
With libass 32dea3434dbd85f9fb2700b6863c1bd92f00b86f or libass 0.17.1, I get 85-90 fps on both vo=gpu and vo=gpu-next.

And I also get roughly similar results with mpv 0.35.1.

That commit definitely causes huge performance penalty, however it's also worth mentioning that this particular sign/typesetting is particularly evil because libass is particularly slow even without that commit. My assumption would be that libass has always been slow with this particular type of sign, and this commit just made that particular case worse

**Comment by Dudemanguy** [comment]
>If mpv were to reset style overrides each frame even if they didn't change

Yeah this is what's currently being done. I'm not too familiar with that area of mpv but that's one pretty obvious optimization we could make. I see the same kind of behavior that llyyr reported so this commit definitely slows down mpv *alot*, but if we are misusing the API then it's our fault. There's possibly some other things we are doing unconditionally on every frame that we don't have to do.

**Comment by TheOneric** [comment]
Thanks both you!

With the FPS benchmark, I too can reproduce lower (`~5.5×`) perf with mpv after 1a599b1db748dfc07df98cd37d8603edb87da2fd. At the same time, the dropped frame numbers from before remain reproducible and are better *with* this libass commit. *(I’m really curious what weird cache/scheduling/... interactions leads to this dropping fewer frames, but am too busy to spend time at this. If anyone knows, please let me know.)*

In any case it is pretty clear that  the libass part by itself now performs worse in mpv. And with the confirmation mpv does indeed reset overrides each frame the cause is also nailed down. 

mpv just not resetting overrides if there wasn't a change would be ideal and the cleanest solution. In theory *(if it turns out many relied on cheap resets)* we could copy and cache the last override and early exit `ass_set_selective_style_override` if there wasn't a change. This will add some additional overhead though and to avoid this mpv might still want to skip resetting every frame.

At first glance *(checking mplayer, ffmpeg, VLC, Kodi, gstreamer assrender, AviSynth and VapourSynth assrender)*. Kodi appears to be the only other user of `ass_set_selective_style_override` and its invocation appears to be [already limited to changes](https://github.com/xbmc/xbmc/blob/80c3f85913d1a432518544d26ef66c204fad40d3/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp#L274-L277).

@rcombs do you think it makes sense to check for changes in `ass_set_selective_style_override`, or are you aware of any other users?

**Comment by rcombs** [comment]
I think the caller is basically always in a better position to know whether a change has occurred than we are.

**Comment by TheOneric** [comment]
Well then, seems like (for now) there’s nothing to do here then and mpv, the only known affected API-user, is already being patched *(thanks Dudemanguy!)*. In any event thanks for the report and help looking into it.

**Comment by Dudemanguy** [comment]
@TheOneric: Thank you for exactly identifying the problem in literally the first sentence!

**Comment by dokur0chan** [comment]
Can confirm that I don't experience frame drops anymore with the latest Windows mpv build. Thanks everyone.
