### ISSUE TITLE
move feature

### ISSUE THREAD

**Issue by eddilara** [libass/libass#703]
it would be really nice to be able to move a clip or iclip or a drawing across the screen

**Comment by astiob** [comment]
You _can_ move drawings—using the usual `\move` tag (or the usual `\t(\shad)`, `\t(\frz)` hacks).

But you can’t currently move clips, yes.

**Comment by eddilara** [comment]
would be very handy to be able to move clips so you don't have to make a new clip for each line

**Comment by TheOneric** [comment]
> would be very handy to be able to move clips so you don't have to make a new clip for each line

as this would constitute a change to the ASS format, it is very unlikely to be added to the current iteration. Instead I added a note about this to the [ASSv5 wiki page](https://github.com/libass/libass/wiki/ASS-v5.0). If a new format revision ever comes to fruition, there the note will actually be found and can be taken into consideration.

Since how to move drawings was already answered, I believe everything is addressed?
