### ISSUE TITLE
Significant perf drop for specific, lower(!) resolution

### ISSUE THREAD

**Issue by TheOneric** [libass/libass#709]
Originally reported in https://github.com/mpv-player/mpv/issues/11612 *(but trying to recreate this with mpv itself may be flaky, use our own `profile` instead with the provided small patch)*.

Tested on 5c15c883a4783641f7e71a6a1f440209965eb64f

For a specific blur-heavy sample (storage size `1920×1080`) it was found that rendering at `scale=0.90` (`≈1728×972`) performs *much* better than rendering at the *smaller* `scale=0.87` (`≈1670×940`). With our own `profile` tool I can reproduce this and the rendering time for the lower resolution is about `×2.5` as much as for the higher resolution.

This is counter-intuitive and with the difference being so large may hint at some oversight in our blur code. It does not seem to depend on compiler flags or compiler itself. Nor does it seem to depend on the bundled fonts. *(I used x86_64 assembly in all tested builds though)*

Looking at flamegraphs
**scale=0.87:**
![fg_0 87](https://github.com/libass/libass/assets/1668471/6f75e8c6-6b3b-4562-9f35-fea4a5a27be4)
**scale=0.90:**
![fg_0 90](https://github.com/libass/libass/assets/1668471/5f2ee9fe-491a-43f9-a8dd-dd333b9a720e)

either case spends most of its time in `ass_synth_blur` but for `scale=0.90` the relative amount spend in it and `ass_copy_bitmap` increases notably. In absolute numbers `perf`’s cycle counter for the latter is about twice as high as for the former case roughly matching the `×2.5` increase from `profile` time. Otherwise nothing jumps out to me.

Here’s the [ASS sample](https://github.com/libass/libass/files/12774763/sample.txt), the [original video clip](https://github.com/mpv-player/mpv/files/11300649/video-sample.zip) with fonts etc and the raw `profile` timings from my machine for various compiler flags and with(out) bundled fonts: [perftimes_709.tar.gz](https://github.com/libass/libass/files/12774760/perftimes_709.tar.gz).

Profile Patch to recreate the resolutions and scaling from the original issue:
```diff
diff --git a/profile/profile.c b/profile/profile.c
index 28b818d..68111ac 100644
--- a/profile/profile.c
+++ b/profile/profile.c
@@ -58,14 +58,15 @@ static void init(int frame_w, int frame_h)
     }
 
     ass_set_storage_size(ass_renderer, frame_w, frame_h);
-    ass_set_frame_size(ass_renderer, frame_w, frame_h);
+    const double SCALE = 0.90;
+    ass_set_frame_size(ass_renderer, frame_w * SCALE, frame_h * SCALE);
     ass_set_fonts(ass_renderer, NULL, "Sans", 1, NULL, 1);
 }
 
 int main(int argc, char *argv[])
 {
-    const int frame_w = 1280;
-    const int frame_h = 720;
+    const int frame_w = 1920;
+    const int frame_h = 1080;
 
     if (argc < 5) {
         printf("usage: %s <subtitle file> <start time> <fps> <end time>\n",
```

**Comment by rcombs** [comment]
I see the same on macOS on arm64; data below with call tree inverted:
<img width="1472" alt="image" src="https://github.com/libass/libass/assets/819638/807fdb29-797e-4a12-b066-8104ea268215">
<img width="1470" alt="image" src="https://github.com/libass/libass/assets/819638/42a8f44b-0b4b-4b27-af8a-02c923f0a6da">

The 87% case has `ass_gaussian_blur` get called about 3x as often as in the 90% case. This appears to be due to a difference in hit rate on the composite cache (probably due to dumb luck on subpixel alignment in the 90% case); if I set the composite cache size to near-zero (effectively disabling it), the blur call counts become nearly equal, and the performance evens out as well (with the 90% case being very slightly faster).

So, not actually related to blur (beyond how that's where we pay the largest composite generation cost), and I'm not sure we can accurately call it a bug at all.

**Comment by MrSmile** [comment]
Yes, looks like with `SUBPIXEL_ORDER 2` performance is much more consistent. There's optimization for case of uniform parallel motion, but it breaks if there's even minuscule animated scale or rotation. It should be theoretically possible to optimize even that case, but it would be really cumbersome and invasive system.
