### ISSUE TITLE
Rendering: Unable to render some bitmap style fonts

### ISSUE THREAD

**Issue by SweetSub** [libass/libass#710]
### Screenshots

Incorrect Rendering:
- I set SourceHanSansSC-Medium to be the default fallback font.
```
mpv v0.36.0-455-ge9690727 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Oct  1 2023 00:59:14
libplacebo version: v6.338.0-16-gcb6be98-dirty
FFmpeg version: N-112248-g145db38f9
FFmpeg library versions:
   libavutil       58.27.100
   libavcodec      60.27.100
   libavformat     60.13.100
   libswscale      7.4.100
   libavfilter     9.11.100
   libswresample   4.11.100
```

![image](https://github.com/libass/libass/assets/85199982/0fd87b62-daab-45da-89e1-1b521c6fa33d)

Expected Rendering:
```
MPC-BE 
  version 1.6.4 
  git 2022.09.07 - bdba5042a 
  built-in subtitle renderer
```
![image](https://github.com/libass/libass/assets/85199982/6de6720b-9fe2-4154-9f0d-4675be8a7056)

### Description of the issue

When I am working with some pixel style font, libass does not render the pixel style font and fallbacks to default.
However, the font shows correct preview in Windows and is rendered correctly in vsfilter based subtitle renderer.

The font I'm working with: https://github.com/TakWolf/fusion-pixel-font
The exact font: [fusion-pixel-12px-monospaced-zh_hans.zip](https://github.com/libass/libass/files/12825589/fusion-pixel-12px-monospaced-zh_hans.zip)

### libass version

https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20231001-git-e969072.7z/download

### ASS Sample

[Script Info]
; Script generated by Aegisub 9530-cibuilds-79a0655eb
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[Aegisub Project Garbage]
Video File: ?dummy:23.976000:40000:1920:1080:47:163:254:
Video AR Value: 1.777778

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Fusion Pixel 12px Monospaced zh,120,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:30.00,Default,,0,0,0,,ABC abc 示例文字 あいうえお

### Special Fonts

I uploaded or linked to the required font

### System Information

MPV version:
[mpv-x86_64-20231001-git-e969072.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20231001-git-e969072.7z/download)

System Information:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2022/‎10/‎15
OS build	22621.2283
Experience	Windows Feature Experience Pack 1000.22662.1000.0
```

**Comment by moi15moi** [comment]
The family name of the font is: ``fusion pixel 12px monospaced zh_hans``
The name in the style name is ``Fusion Pixel 12px Monospaced zh``

This is propably related to the issue #459

**Comment by TheOneric** [comment]
Yup, this seems like the fontname length issue from #459.
Thanks for checking this @moi15moi (Btw, also thanks for all the other font selection behaviour investigations. While unfortunately  nobody had time yet to implement your findings, they are much appreciated!)

@SweetSub In general, if you want fonts to work consistently with GDI(VSFilter) and modern font tooling, you should (among other things) use names <=31 characters *(e.g. fontforge even shows a warning about this)*. Since the font you’re using appears to be open-source, you might want to consider building a version with a shorter name or making upstream aware of the issue with GDI.
For libass specifically, we still want to emulate the truncation anyway for the sake of VSFilter-compatibility. Thus even without changes in the font, it should eventually work. But this might take a while.
