### ISSUE TITLE
Rendering: libass doesn't set a default name for the style when it is empty

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#714]
### Screenshots

vsfilter
![image](https://github.com/libass/libass/assets/80980684/df447caf-d1c4-43eb-a777-a956ae52147f)

libass 0.16.0
![image](https://github.com/libass/libass/assets/80980684/9ae2df6c-aef1-4189-b331-0ebf2f22c505)

### Description of the issue

When the a style name is empty, vsfilter set it to ``Default``.
See [STS.cpp at line 2094](https://sourceforge.net/p/guliverkli2/code/HEAD/tree/src/subtitles/STS.cpp#l2094)

### libass version

0.16.0

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9214, Daydream Cafe Edition [Shinon]
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 640
PlayResY: 480

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: ,Verdana,35,&H000000FF,&H000000FF,&H002C2C2C,&H00000000,-1,0,0,0,100,100,0,0,1,2.5,0,2,0,0,72,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,Test
```

### Special Fonts

The issue doesn't depend on a specific font

**Comment by astiob** [comment]
Good catch, thanks! It seems that this may have been intended from the earliest days of libass but has never quite worked:

https://github.com/libass/libass/blob/e64390522d9501a2c7e6a51c31a5b2a1f3a35cd1/libass/ass.c#L720-L721

(These lines have stayed untouched since the very first libass commit in MPlayer, e. g. see https://github.com/sherpya/MPlayer/commit/4af5c772ffb0a10c4a1f6ea95c379afe6383f4bb.)

Of course, this condition only actually triggers if there’s no `Name` column at all (when libass violates VSFilter compatibility by honouring the `Format`) or if a memory allocation has failed—but not if the string is empty. And if the allocation has failed, we probably want to drop the style (if not more) rather than rename it to `Normal`!
