### ISSUE TITLE
How to handle auto wrap when burn chinese subtitle with ffmpeg

### ISSUE THREAD

**Issue by iorilu** [libass/libass#715]
> wrap_unicode
> Break lines according to the Unicode Line Breaking Algorithm. Availability requires at least libass release 0.17.0 (or LIBASS_VERSION 0x01600010), and libass must have been built with libunibreak.
> 
> The option is enabled by default except for native ASS.

above is copied from ffmpeg document, [https://ffmpeg.org/ffmpeg-filters.html]( https://ffmpeg.org/ffmpeg-filters.html)

but when  I try to use it  , it says 
`Error applying option 'wrap_unicode' to filter 'subtitles': Option not found
Error reinitializing filters!
Failed to inject frame into filter network: Option not found`

I am not sure , for now this option is available through ffmpeg downloaded executables ? i am not building ffmpeg from source ,  
how can I use this option , as I need to make chinese auto wrap when burning it to videos. thanks

the command i run is below 
`
ffmpeg -y -i "short1.mp4" -vf "subtitles=short1.srt:wrap_unicode=1:force_style='BackColour=&H80000000,BorderStyle=1,Fontsize=10'" -crf 1 -c:a copy "output1.mp4"
`

**Comment by rcombs** [comment]
This is a question about ffmpeg, not about libass. I'd suggest either building ffmpeg locally or requesting an update from whoever you're getting your builds from.

**Comment by ganlvtech** [comment]
If you are using [BtbN's FFmpeg static builds](https://github.com/BtbN/FFmpeg-Builds), these builds are not compiled with [libunibreak](https://github.com/adah1972/libunibreak).

This pull request is waiting for merge https://github.com/BtbN/FFmpeg-Builds/pull/569.

[Gyan's ffmpeg static builds](https://www.gyan.dev/ffmpeg/builds/) have already been fixed in https://github.com/GyanD/codexffmpeg/issues/124
