### ISSUE TITLE
Rendering: Drawing without m isn't rendered by VSFilter

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#719]
### Screenshots

VSFilter
![image](https://github.com/libass/libass/assets/80980684/1a0147a3-3d0f-4edf-80ee-6ca1ae02f5e2)

Libass 0.16.0
![image](https://github.com/libass/libass/assets/80980684/5213539b-e737-4397-b44e-ebf516f7acd7)

### Description of the issue

VSFilter doesn't render at all the drawing

### libass version

0.16.0

### Is it a regression?

No

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9643-cibuilds-c61f149a3
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\p1\pos(323,63)}l 394 159.75 1009.75 159.75 1009.75 159.75 1009.75 159.75 1007.5 101.25 1007.5
```

### Special Fonts

The issue doesn't depend on a specific font

### Additional info

I am not sure, but I think VSFilter doesn't show the drawing due to this [if statement](https://sourceforge.net/p/guliverkli2/code/HEAD/tree/src/subtitles/RTS.cpp#l468)

libass doesn't seems to reproduce this behaviour when it parse the string drawing [here](https://github.com/libass/libass/blob/c047dd2ea16f73abb4f448e6db3637158c1226d0/libass/ass_drawing.c#L46-L122) (i'm not 100% sure)

This may be connected to #629

**Comment by astiob** [comment]
I’m surprised that we render this.

**Comment by arch1t3cht** [comment]
`point` is initialized to `{0, 0}` at the start of `drawing_tokenize`:
https://github.com/libass/libass/blob/c047dd2ea16f73abb4f448e6db3637158c1226d0/libass/ass_drawing.c#L50-L59
So if the drawing starts with a `b` or `l` a point `{0, 0}` is just implicitly inserted.

I'm actually surprised this hasn't been reported before. I knew about this for a while and have seen other fansubbers talking about it too (found at least two occurrences when searching logs right now, though it turns out that neither of these mentions clarified that this only happens on libass). In fact it's quite likely that some scripts might rely on this behavior.

One more interesting note: I've mostly seen this behavior phrased as "there is always an implicit m 0 0 at the start" (including by myself until I investigated this example), but that is not completely true: Adding an `m 0 0` at the start here changes the positioning, because now `{0, 0}` is an explicitly listed point and thus changes the bounding box, which changes alignment.
