### ISSUE TITLE
Rendering: English glyph for Segoe UI Variable Display is wrong from yesterday

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [libass/libass#730]
### Screenshots

20240121
https://github.com/shinchiro/mpv-winbuild-cmake/actions/runs/7597580712
![屏幕截图 2024-01-22 215450](https://github.com/libass/libass/assets/50797982/dde95a0c-70be-4e9f-a1f4-13951de42be0)
20240122
https://github.com/shinchiro/mpv-winbuild-cmake/actions/runs/7604644763
![屏幕截图 2024-01-22 215355](https://github.com/libass/libass/assets/50797982/d6da8a34-d1f3-463a-beb4-15d95ac8fb98)

### Description of the issue

I use mpv player from above links with `osd-font=Segoe UI Variable Display` in mpv.conf

fonts file: https://aka.ms/SegoeUIVariable

### libass version

I'm not pertty sure

### Special Fonts

I uploaded or linked to the required font

**Comment by astiob** [comment]
@natural-harmonia-gropius By the way: the font you saw until yesterday probably wasn’t actually <i>Segoe UI Variable Display,</i> either. If I’m not mistaken, it should have been Segoe UI Variable’s default preset, which, again if I’m not mistaken, corresponds to <i>Segoe UI Variable Text.</i>

---

Fellow libass maintainers, FYI: I’ve just confirmed that DirectWrite’s GDI interop does indeed find and return variable font presets:

```
GetFontFromFontFace:
family: [Segoe UI Variable Display]
fullname: [Segoe UI Variable Display Bold]
postscript name: [Segoe-UI-Variable-Display-Bold]
```

So technically #683 did regress this particular use case on Windows, but it was for good cause, and this wasn’t intentional in the first place, because we don’t support named variable font presets in `ass_coretext`, `ass_fontconfig` or embedded fonts.

This will eventually un-regress when #386 is fixed and full support for named variable font presets is added to libass across all font providers.
