### ISSUE TITLE
Consider adding SHSTK support

### ISSUE THREAD

**Issue by loqs** [libass/libass#742]
libass lacks SHSTK support under linux as it does not annotate assembly files for ELF CET properties. If stack frames are not changed then I believe adding support can be achieved by updating x86inc.asm to a version including [c7cf926c08661e754f411722a035c3fefde313ab](https://code.videolan.org/videolan/x86inc.asm/-/commit/c7cf926c08661e754f411722a035c3fefde313ab).

**Comment by rcombs** [comment]
SHSTK/CET requires:
> 11th Generation Intel Core processor family based on Tiger Lake microarchitecture, 4th generation Intel® Xeon® Scalable Processor Family based on Sapphire Rapids microarchitecture.

Does anyone have a system they can test this with?

A PR to update x86inc would be welcome, but I'd want to make sure we don't have any odd edge cases where this would break.

**Comment by Gramner** [comment]
On Linux CET support is quite new and still a bit of a mess. You currently need at least kernel 6.6 combined with glibc 2.39 with `glibc.cpu.hwcaps=SHSTK` added to the `GLIBC_TUNABLES` environment variable. On Windows it supposedly works on recent versions of Windows 11. Appropriate compiler/linker flags may or may not be needed depending on the system configuration.

On the CPU side it should be supported since Tiger Lake on Intel and since Zen 3 on AMD.

**Comment by astiob** [comment]
> and since Zen 3 on AMD.

FWIW I have one of these (if there isn’t a more fine-grained criterion of eligibility), with Windows 11 and WSL, but I have no idea how any of this should be configured or tested.

**Comment by loqs** [comment]
Here is a link to the [discussion](https://github.com/libjpeg-turbo/libjpeg-turbo/pull/350#issuecomment-1961368789) on adding .note.gnu.property to libjpeg-turbo (which I believe is all that updating x86inc.asm would achieve) covering what impact such a change would have on both supported and unsupported platforms. I can test SHSTK support under linux if that helps. If you want support for the BTI half of CET then I would suggest reaching out to OpenBSD as they already have a patch for that https://github.com/openbsd/ports/commit/9bf73bbc54ab36306fda8d1956b5f749fa82e901 (linux does not support userspace BTI so I am unable to test that.)
