### ISSUE TITLE
[DirectWrite] Does not select the right font when 2 fonts have similar attributes

### ISSUE THREAD

**Issue by moi15moi** [libass/libass#744]
### Screenshots

VSFilter
![image](https://github.com/libass/libass/assets/80980684/f8043f40-dda9-431c-8d25-860f8f20f888)
Libass
![image](https://github.com/libass/libass/assets/80980684/2d866f0b-2e1e-4d9a-97b2-701f5a121c74)

### Description of the issue

VSFilter pick up ``SFProDisplay-BoldItalic.ttf``, but libass doesn't find it. You can download the fonts [here](https://github.com/libass/libass/files/14813372/Fonts.zip).

### Step to reproduce (it is very important to respect the order)
1. Install ``SFProDisplay-Bold.ttf``.
2. Install ``SFProDisplay-BoldItalic.ttf``.
3. Select the font by it's fullname (``SF Pro Display Bold Italic``).

Since I am on Windows Desktop, libass call [EnumFontFamiliesW](https://github.com/libass/libass/blob/master/libass/ass_directwrite.c#L900-L901). When libass [CreateFontIndirectW](https://github.com/libass/libass/blob/e51781341493e0312f0c7fee66372f0365f7b962/libass/ass_directwrite.c#L729), it directly use the logfont that the callback give. BUT, the only difference between ``SFProDisplay-Bold.ttf`` and ``SFProDisplay-BoldItalic.ttf`` in the ENUMLOGFONTEXW is ENUMLOGFONTEXW.elfFullName. ENUMLOGFONTEXW.elfLogFont is exactly the same between the 2 fonts ! This is why it pick up ``SFProDisplay-Bold.ttf``, NOT ``SFProDisplay-BoldItalic.ttf``.

### Possible solution
A possible solution is to replace the ``lfFaceName`` with the ``elfFullName`` of the ENUMLOGFONTEXW.

### libass version

9f4e6afeec54c0d240a9b8377f27e6c5b7c2bde0

### Is it a regression?

No

### ASS Sample

```
[Script Info]
; Script generated by Aegisub 9744-Rework-Windows-FontCollector-17a3f487f
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,{\fnSF Pro Display Bold Italic}Test
```

### Special Fonts

I uploaded or linked to the required font

### System Information

OS: Windows 10 version 10.0.19045.4170

**Comment by astiob** [comment]
Yet another reason to migrate away from `EnumFontFamilies` to direct calls for each font request :-( I’ve been wanting to do that for quite a while, but it requires a (desirable) larger rewrite of our fontselect, so I haven’t found the energy to actually do it.

I think this happens because we call `CreateFontIndirect` with the `LOGFONT` returned by `EnumFontFamilies`, which has only one font name—and it’s apparently the _family_ name, seeing as `EnumFontFamilies` returns a [separate field](https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-enumlogfontexw) for the full name. And the family name, of course, is the same for both of these fonts, as are all the other parameters contained within `LOGFONT`, as you point out:

```
EnumFontFamiliesW:
family: [SF Pro Display] fullname: [SF Pro Display Bold] style: [Bold] charset: [0] weight: [700] ntmFlags: [0x40] FontType: [4] (TrueType)
family: [SF Pro Display] fullname: [SF Pro Display Bold Italic] style: [Bold Italic] charset: [0] weight: [700] ntmFlags: [0x40] FontType: [4] (TrueType)
```

**Comment by astiob** [comment]
> A possible solution is to replace the `lfFaceName` with the `elfFullName` of the ENUMLOGFONTEXW.

Oh. This sounds interesting. But this is only allowed for TrueType-outline fonts, not for CFF-outline ones. SF Pro Display is indeed a TrueType-outline font (although other affected Apple fonts may not be), but the problem is that our callback can’t know which kind of outlines the font has until it has actually obtained the font!

**Comment by moi15moi** [comment]
> > A possible solution is to replace the `lfFaceName` with the `elfFullName` of the ENUMLOGFONTEXW.
> 
> Oh. This sounds interesting. But this is only allowed for TrueType-outline fonts, not for CFF-outline ones. SF Pro Display is indeed a TrueType-outline font (although other affected Apple fonts may not be), but the problem is that our callback can’t know which kind of outlines the font has until it has actually obtained the font!

Why do you say that? ``elfFullName`` represent the postscript name for CFF-outline ones (yes this is a terrible name, but it is GDI...)

**Comment by astiob** [comment]
Hang on, derp. CFF-outline fonts just return their PostScript name in the `elfFullName` field. That’s what causes the difference in the first place. So yeah, we should be able to do that!
