### ISSUE TITLE
Is there a perspective value for rotates in libass?

### ISSUE THREAD

**Issue by weizhenye** [libass/libass#805]
In CSS, [perspective](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective) determines the distance between the z=0 plane and the user.

When I implemented rotates in [ASS.js](https://github.com/weizhenye/ASS), I got wrong result without perspective, and after some test, I found `perspective(314px)` is almost same as libass.

`{\pos(371,214)\frz338.403\frx42\fry30\org(187,65)}Some more rotation tricks, this time in 3D and with a different origin`

| libass | ASS.js without perspective | ASS.js with perspective(314px) |
| - | - | - |
| <img width="200" alt="libass" src="https://github.com/user-attachments/assets/98187e53-1118-4648-b8e6-9db14631126b"> | <img width="200" alt="ASS.js without perspective" src="https://github.com/user-attachments/assets/df1ca451-131d-4fe6-8f26-3374a5ea993a"> | <img width="200" alt="ASS.js with perspective(314px)" src="https://github.com/user-attachments/assets/406d6cbb-e3c6-4e8d-86fb-b55896751559"> |

I'm curious what's the accurate value of perspective, but I don't find the value in libass source code.

It seems 314 ≈ 100π, is it caused by some algorithm?

**Comment by TheOneric** [comment]
ASS’ 3D transformation matrix depends on the [layout resolution](https://github.com/libass/libass/wiki/ASS-File-Format-Guide#layoutresx-and-layoutresy) *(which in general is different from _both_ `PlayRes` and render frame resolution)*. If no `LayoutRes*` headers are set, for historical reasons this defaults to the _storage_ size of the video subs are paired with, i.e. the native video resolution _before_ anamorphic desqueezing.

Relevant parts of the code: [`calc_transform_matrix`](https://github.com/libass/libass/blame/c131a95c443f894bd95a05dfa3d0a8dc67a22d5e/libass/ass_render.c#L1323-L1370) and [`init_font_scale`](https://github.com/libass/libass/blame/c131a95c443f894bd95a05dfa3d0a8dc67a22d5e/libass/ass_render.c#L1032)

**Comment by arch1t3cht** [comment]
Additionally, in LayoutRes units the distance of the rendering plane from the origin is `312.5`, which is `10^4 / 2^5`

**Comment by weizhenye** [comment]
Wow, after [nearly 9 years](https://github.com/weizhenye/ASS/commit/27a022c3cd499d9610c8727b63426a97530fcc10#diff-ed8b5e784300d640befcd7b1f87c2bbeeaa6c32c11f7a6b033ff7db4b868091fR441), I finally learn the magic, thank you very much!

But now I have many more questions...

I'm not familiar with C, I see [20000](https://github.com/libass/libass/blob/c131a95c443f894bd95a05dfa3d0a8dc67a22d5e/libass/ass_render.c#L1359) here, is `dist` this line means perspective? So 312.5 is `2 * 10^4 / 2^6`, but is `20000` still a magic number? And what is the `2^6` means?

---

LayoutRes is new to me, and I'm not sure some terms' meaning.

Does `video storage resolution` means dimensions? Using any video player, set size to `1x` with default aspect ratio, the display size is `video storage resolution`, right?

<img width="459" alt="image" src="https://github.com/user-attachments/assets/01493f68-7d47-4b6b-b134-8e8e9ca2313d">

---

If video resolution is 640x360 and PlayRes is 640x360, `\fs40\bord4` looks like 40px height and 4px border, when set video size to 2x in player, everything ASS renders will be 2x, `\fs40\bord4` looks like 80px height and 8px border.
If video resolution is 1280x720 and PlayRes is 640x360 with `ScaledBorderAndShadow: no`, `\fs40\bord4` looks like 80px height and 4px border.

PlayRes 640x360 in video 1280x720 and 640x360 will render different results, so LayoutRes is introduced, if LayoutRes is 640x360, `\fs40\bord4` looks like:
* video 640x360: 40px height and 4px border
* video 1280x720: 80px height and 8px border

Is above right?

**Comment by astiob** [comment]
> I'm not familiar with C, I see [20000](https://github.com/libass/libass/blob/c131a95c443f894bd95a05dfa3d0a8dc67a22d5e/libass/ass_render.c#L1359) here, is `dist` this line means perspective? So 312.5 is `2 * 10^4 / 2^6`, but is `20000` still a magic number? And what is the `2^6` means?

`dist` is the distance from the camera point to the screen plane, onto which the entire 3D space is projected using a perspective projection. It is a magic constant that originates [in guliverkli](https://sourceforge.net/p/guliverkli/code/HEAD/tree/trunk/guliverkli/src/subtitles/RTS.cpp#l177) and equals 20000 layout-resolution subpixels, or 20000/64 = 312.5 layout-resolution pixels, because guliverkli’s (and also every other VSFilter’s and libass’s) subpixel precision is 6 fixed-point fractional bits, or 2<sup>6</sup>=64 subpixels per pixel (“2^6”).

> LayoutRes is new to me, and I'm not sure some terms' meaning.

See https://github.com/libass/libass/discussions/734#discussioncomment-8506576

Anything not mentioned there is scaled directly from PlayResX to target display area width (for horizontal positions and dimensions) or from PlayResY to target display area height (for vertical positions and dimensions).

When layout resolution isn’t specified in ASS headers, the video stream’s width and height (as decoded before any rescaling to fit the user’s display; 1920×1080 in your picture) are used as the layout resolution. So in older discussions, you may find layout resolution referred to as “video storage resolution”, but nowadays it’s merely the default/fallback and ASS headers can override it.

> If video resolution is 640x360 and PlayRes is 640x360, `\fs40\bord4` looks like 40px height and 4px border, when set video size to 2x in player, everything ASS renders will be 2x, `\fs40\bord4` looks like 80px height and 8px border.

Correct.

> If video resolution is 1280x720 and PlayRes is 640x360 with `ScaledBorderAndShadow: no`, `\fs40\bord4` looks like 80px height and 4px border.

Correct, assuming the player is set to 1× video size.

> if LayoutRes is 640x360, `\fs40\bord4` looks like:
>     * video 640x360: 40px height and 4px border
>     * video 1280x720: 80px height and 8px border

Correct. In this case, everything is scaled as though the video were 640×360.
