### ISSUE TITLE
Rendering: Incorrect rendering Arabic language

### ISSUE THREAD

**Issue by AhmedSamir899** [libass/libass#809]
### Screenshots

expected result:

![image](https://github.com/user-attachments/assets/6d9103f1-a223-470a-847b-9539c1494429)

actual result:

![image](https://github.com/user-attachments/assets/ca6ac3be-b17d-45d3-b4b7-c4d705837ffe)

### Description of the issue

when using Arabic font, it shows strange output 

### libass version

0.17.2 

### Is it a regression?

no i tried old versions and they have the same problem 

### Special Fonts

I uploaded or linked to the required font

### System Information

windows 11 23h2
Ryzen 4800h
Gtx 1650 

### Log

there is no log i use mpc hc

### Additional info

This is subtitle link : https://dl.subdl.com/subtitle/3393901-8317065

And this is for fonts : https://top4top.io/downloadf-31238s2v21-rar.html

**Comment by moi15moi** [comment]
Your screenshot seems to correspond to the file ``[Rhythm] Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san - 03.ass`` at 38 seconds.
The line you are referring to as problematic is line 3059, which contains the text ``دائمًا وأبدًا، لن ترى الجانب الآخر من مشاعري حتمًا``. It uses the following style:
```
Style: OP-AR,هشام الشرق طبيعي,70,&H00FFFFFF,&H000000FF,&H002C2C2A,&H7F404040,-1,0,0,0,100,100,0,0,1,3.5,0,2,30,30,15,1
```
So, libass will try to find the font named ``هشام الشرق طبيعي``, but none of the fonts you shared correspond to it.
If you have muxed the font you have provided to the mkv, it is strange that it render tofu box because all of them has the glyph to render the requested text (``دائمًا وأبدًا، لن ترى الجانب الآخر من مشاعري حتمًا``).

To help you, we need more information.
1. Are the fonts you provided are muxed to your mkv file?
2. Are you sure you are using libass with mpc hc? In general, it use VSFilter to render .ass subtitle.

**Comment by NBruderman** [comment]
There is an issue on MPC-HC that got closed on the same topic https://github.com/clsid2/mpc-hc/issues/2954
Also, for the 2nd point, libass is widely being used as the subtitle renderer in MPC-HC, as it got implemented, and works really well. If you're using k-lite, libass is the default option for ass rendering in MPC-HC

**Comment by NBruderman** [comment]
> There is an issue on MPC-HC that got closed on the same topic https://github.com/clsid2/mpc-hc/issues/2954

> Also, for the 2nd point, libass is widely being used as the subtitle renderer in MPC-HC, as it got implemented, and works really well. If you're using k-lite, libass is the default option for ass rendering in MPC-HC

**Comment by TheOneric** [comment]
When unpacking the font rar archive i get a warning `Hayah.ttf`is incomplete. Testing with all other fonts preloaded as if muxed
```sh
mpv --sub-font-provider=none \
    --sub-fonts-dir="$PWD"/fonts \
    -sub-file \[Rhythm\]\ Tokidoki\ Bosotto\ Russia-go\ de\ Dereru\ Tonari\ no\ Alya-san\ -\ 03.ass \
     ../videofiles/long_1080p.mkv \
     --start=37 --end=40 \
     -v -v 2>&1 | grep 'sub/ass'
```

Doesn’t show anything, not even TOFU boxes and
```
[sub/ass] fontselect: failed to find any fallback with glyph 0x0 for font: (Elegante ESP, 700, 0)
[sub/ass] fontselect: failed to find any fallback with glyph 0x0 for font: (هشام الشرق طبيعي, 700, 0)
```

Using `fontconfig` font provider fallbacks are selected for both and rendered normally. Unless `Hayah.ttf` happened to be one of the missing fonts this seems about right and the necessary fonts just aren’t muxed. *(Not sure otoh if no fallback being selected with `none` is expected or not)*

Potentially DirectWrite can’t find a fallback for `هشام الشرق طبيعي` though and ends up with TOFU?

**Comment by AhmedSamir899** [comment]
Are the fonts you provided muxed to your mkv file?
I installed all fonts on my pc and still get the same result and I'm using libass with mpc hc

**Comment by NBruderman** [comment]
There is an issue on MPC-HC that got closed on the same topic https://github.com/clsid2/mpc-hc/issues/2954
Also, for the 2nd point, libass is widely being used as the subtitle renderer in MPC-HC, as it got implemented, and works really well. If you're using k-lite, libass is the default option for ass rendering in MPC-HC

Thats not muxing though. Mux them to the video, make sure the font name is actually the correct one, and after that see if the problem still persists

**Comment by AhmedSamir899** [comment]
the problem still persists after muxing 

![new](https://github.com/user-attachments/assets/6920d3f2-7366-42e1-8ea7-646c60e1a3a7)

![image](https://github.com/user-attachments/assets/f5e0ede7-c4cf-43d6-9368-1429f0717420)

**Comment by AhmedSamir899** [comment]
when muxing video with fonts and changing font to any English font name it works fine but with any Arabic it shows TOFU boxes

**Comment by astiob** [comment]
As far as I understand the earlier messages, the font archive you shared in the original report does not, in fact, contain the font named in the subtitles, so it makes no difference whether you have the fonts from the archive (installed or muxed) or not. When you say you’ve installed “all fonts”, do you mean you actually do have this font from a separate source? If so, can you upload it here?

**Comment by astiob** [comment]
> there is no log i use mpc hc

@clsid2 Is there any way to get the libass log in MPC-HC?

---

I haven’t been able to reproduce this in any of the following ways:

* `{\fn[Arabic name]}[Arabic text]` in mpv without installing the provided fonts
* the provided ASS in mpv without installing the provided fonts
* the provided ASS in MPC-HC, with or without libass, without installing the provided fonts
* the provided ASS in MPC-HC with libass, with the provided fonts and ASS alike attached to the MKV

So I suspect this issue is somehow related to the particular set of fonts that are installed on your computer.

Oddly enough, the screenshots show that some glyphs are located above and below others like diacritical marks, so it seems as though Arabic shaping is actually happening but the glyphs are missing.

My best guess is that one of your system fonts is buggy and half-supports Arabic, declaring support for it and having Arabic shaping information but actually lacking any Arabic glyphs. None of the attached fonts have the name specified in the ASS, so libass asks the system for another font that supports Arabic and gets back this buggy font.

**Comment by astiob** [comment]
You can try downloading mpv and opening the affected video file in it.

If you run mpv standalone, press <kbd>\`</kbd> (the backtick; in common English keyboard layouts, it’s the key to the left of <kbd>1</kbd> and above <kbd>Tab</kbd>) to show the log. If you run mpv from a terminal (command prompt), you’ll see the log in that terminal.

Play the file until the tofu boxes appear. Most likely, you’ll see something like this in the log:

```
[sub/ass] fontselect: Using default font family: (هشام الشرق طبيعي, 700, 0) -> Arial-BoldMT, 0, Arial-BoldMT
```

but in your case, some other name will take the place of `Arial-BoldMT`. This will tell you which font libass is trying to use. Then, you can find that font on your system and use other software to check how well it actually supports Arabic.
