### ISSUE TITLE
Rendering: stretched borders with larger aspected ratios

### ISSUE THREAD

**Issue by omgold** [libass/libass#815]
### Screenshots

![high](https://github.com/user-attachments/assets/a9279ca5-a82d-4a22-8870-95e069df7c1a)
![wide](https://github.com/user-attachments/assets/1d8d034b-a582-4171-85c5-ecfadec1f223)
![screenshot-20240812-153135](https://github.com/user-attachments/assets/723d98d5-c7e1-4b5b-8cf2-5adb3d213a20)

### Description of the issue

I find that when rendering with `ScaledBorderAndShadow: yes` the outline width and shadow offset are different in x/y directions, depending on the image aspect ratio. It is okay, when the PlayResX/PlayResY aspect ratio matches the image aspect ratio, but when there is a large mismatch the borders become unexpectedly stretched. See first 2 images. 

These were generated with the `test` utility coming with libass:

```
./test high.png test.ass 0 1000 3000
./test wide.png test.ass 0 3000 1000
```

The last one is what I get with Windows media player.

Digging into the code, the way I understand things now is that `border_scale_x` should be set to `screen_scale_y` instead of `screen_scale_x` as the font size in both directions also only depends on `screen_scale_y`.

This fixes it for me:

```
--- libass/ass_render.c.orig	2024-08-12 15:42:09.677151209 +0200
+++ libass/ass_render.c	2024-08-12 15:11:40.231486957 +0200
@@ -1048,7 +1048,7 @@
     state->blur_scale_x = font_scr_w / layout_res.x;
     state->blur_scale_y = font_scr_h / layout_res.y;
     if (render_priv->track->ScaledBorderAndShadow) {
-        state->border_scale_x = state->screen_scale_x;
+        state->border_scale_x = state->screen_scale_y;
         state->border_scale_y = state->screen_scale_y;
     } else {
         state->border_scale_x = state->blur_scale_x;
```

### libass version

0.17.3

### ASS Sample

```
[Script Info]
ScriptType: v4.00+
PlayResX: 200
PlayResY: 200
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,Hello
```

### Special Fonts

The issue doesn't depend on a specific font

### System Information

Arch Linux

**Comment by astiob** [comment]
This is intentional. This is how borders work in every version of VSFilter, the reference implementation of ASS.

> The last one is what I get with Windows media player.

The last screenshot does not seem to show a different picture aspect ratio at all: I see a normal-aspect picture surrounded by black margins. If you actually let your media player (e. g. MPC-HC) stretch the picture, ASS borders will be stretched too.

**Comment by omgold** [comment]
> The last screenshot does not seem to show a different picture aspect ratio at all: I see a normal-aspect picture surrounded by black margins. If you actually let your media player (e. g. MPC-HC) stretch the picture, ASS borders will be stretched too.

The screenshot is not of the full window, just of the area around the subtitle. The aspect ratio of the video is also 1000x3000, like the high image. If I play exactly the same video in mpv (which uses libass) I get stretching like above.

Not sure what you mean by letting the media player stretch the picture.

**Comment by astiob** [comment]
Thanks for the detailed report (including digging into the code), though!

One thing that isn’t clear is how exactly you obtained your Windows screenshot and what overall you did to compare libass to other renderers; if you can explain that in more detail, we can try to work out together why you saw a difference, although it likely won’t change the outcome.

Also, do you have a deeper real-world motivation behind this?

At any rate, feel free to add more comments even while the issue is marked ‘closed’.

**Comment by astiob** [comment]
> The screenshot is not of the full window, just of the area around the subtitle. The aspect ratio of the video is also 1000x3000, like the high image.

What codec/filter setup are you using for this test? Even your text isn’t stretched, but it should be.

Here’s a test file with 1000×3000 video (all green) and the ASS you posted above: 
[test-815.zip](https://github.com/user-attachments/files/16588061/test-815.zip)

Here’s a full screenshot of what I get using xy-VSFilter as a DirectShow filter (DirectVobSub), which should be what’s used by Windows Media Player:
![A screenshot shows the text “Hello” stretched very wide. The border is stretched together with the text.](https://github.com/user-attachments/assets/5eed9589-7852-4cf4-a7b2-45f035e672ee)

Here’s a full screenshot of what I get using XySubFilter, MPC-HC’s internal VSFilter, and indeed mpv:
![A screenshot shows the text “Hello” stretched very wide. The border is stretched together with the text.](https://github.com/user-attachments/assets/a2467b5d-e22f-46ae-a1c6-e5e9bf5a65cf)

**Comment by astiob** [comment]
> Even your text isn’t stretched, but it should be.

Sorry! Disregard this and the earlier pictures. I got confused by my own tools. I created the video file from a pre-existing one, and the display aspect ratio got carried over when I resampled the pixels.

Fixed video file: [test-815.zip](https://github.com/user-attachments/files/16588336/test-815.zip)

Fixed screenshots:

DirectVobSub:
![A stretched border is visible.](https://github.com/user-attachments/assets/7d29f5ac-40f8-4640-8650-a15d7235795f)

XySubFilter etc.:
![A stretched border is visible.](https://github.com/user-attachments/assets/bc1630ff-24dd-4c75-a094-0b2a7e7bb636)

**Comment by omgold** [comment]
I see. Your latest video looks indeed the same for me with mpc-hc, but with Windows Media Player it is okay:

![screenshot-20240813-075157](https://github.com/user-attachments/assets/02390476-eaab-4320-a1c2-8837de9f764c)

In any case, it seems to I have to accept that the problem is not with libass, but with the ASS format itself (No idea in which case that behavior would be actually useful).

> Also, do you have a deeper real-world motivation behind this?

Actually I have. 

I first found the issue in kdenlive. What is does is to create an srt subtitle and passes it to ffmpeg which bakes it into the video using the subtitles avfilter.

What ffmpeg does internally is to convert the srt to ass and lets libass render it. The problem seems to be, that the conversion from srt to ass uses an independent code path (you can call ffmpeg to just do the conversion and nothing else, which creates the same behavior). I assume as srt doesn't provide info about the video resolution, in the ass, PlayResX/Y will just be set to some default. Don't see a way to change that in ffmpeg. And likely it would be hard to make ffmpeg use correct PlayRes automatically.

The only workaround I know of is to call ffmpeg to just convert the srt file to an ass file, then edit the PlayRes inside the ass by hand, then call ffmpeg again to bake the subtitles into the video.

Unnecessary to say that that it wouldn't be easy at all to make kdenlive doing that.

**Comment by TheOneric** [comment]
> No idea in which case that behavior would be actually useful

To give some background: almost everything is scaled relative to its respective `PlayRes` dimension. ASS is designed for typesetting and typesets generally not portable between two videos of different aspect ratio regardless of which dimension is used for scaling, so `PlayRes` and video aspect ration needing to match (or manually correct one dimenaion) isn’t an issue for native ASS subs and each dimension being scaled independently is just the most straightforward and matches the intuition of `ScaledBorderAndShadow: yes`.

In case of anamorphic video it can actually be desirable to set `PlayRes` and `LayoutRes` to values matching the video’s _display_ aspect ratio rather than it’s _storage_ aspect ratio. Thus when rendering subs for hardsubbing in storage resolution border and other features appear squeezed, but will have the same visual size at display time.
