### ISSUE TITLE
Prevent overlapped areas between opaque boxes from darkening

### ISSUE THREAD

**Issue by lowkey-heonyoung** [libass/libass#821]
I'm having trouble darkening the areas where opaque boxes overlap.

I know that it can be solved by inserting new line(\n) into middle sentence. But I'm finding the way of solve it by only manipulating color.

Can anyone help me to solve it?

---

**Screenshot**
![opaque box overllaping](https://github.com/user-attachments/assets/8659c94d-15cb-4215-8eea-f536f45d1745)

**ASS**
```
[Script Info]
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
ScaledBorderAndShadow: yes
YCbCr Matrix: None
WrapStyle: 0
Collisions: Reverse

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Title,Pretendard ExtraBold,28,&H00ffffff,&H00ffffff,&H00000000,&H00000000,0,0,0,0,100,100,,,1,0.5,1.0,2,10,10,118,
Style: Subtitle,Pretendard ExtraBold,22,&H00ffffff,&H00ffffff,&H00000000,&Hff000000,0,0,0,0,100,100,,,1,,,2,10,10,40,
Style: Subtitle-box,Pretendard ExtraBold,22,&Hb3000000,&Hb3000000,&Hb3000000,&Hff000000,0,0,0,0,100,100,,,3,1.7,,2,10,10,40,

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 11,0:00:53.91,0:00:56.91,Title,,0,0,0,,{\blur10}흥미진진한 뱀파이어 이야기
Dialogue: 1,0:00:53.91,0:01:06.45,Subtitle,,0,0,0,,{\blur0}진짜 {\blur0}신났네 {\blur0}신났네 {\blur0}목이 {\blur0}벌렸어요 {\blur0}나 {\blur0}아직 {\blur0}한 {\blur0}번도 {\blur0}안 {\blur0}벌렸어 {\blur0}잠시만요 {\blur0}뱀파이어로서 {\blur0}싱가포르 {\blur0}보기한테 {\blur0}뱀파이어로서
Dialogue: 0,0:00:53.91,0:01:06.45,Subtitle-box,,0,0,0,,진짜 신났네 신났네 목이 벌렸어요 나 아직 한 번도 안 벌렸어 잠시만요 뱀파이어로서 싱가포르 보기한테 뱀파이어로서
```

**Comment by TheOneric** [comment]
There is no way to avoid this in standard ASS as it is intended behaviour. You’ll have to either reduce the border size until no parts overlap, or manually break lines and add spacing *(i.e. empty lines with a fitting font size)* as appropriate.

However, if you’re dealing with on-the-fly generated, transient subtitles which only exist within your application and will never be distributed or saved to disk, you may be interested in using the non-standard [`BorderStyle=4`](https://github.com/libass/libass/wiki/Libass%27-ASS-Extensions#borderstyle4) instead to simplify things.

**Comment by astiob** [comment]
This probably isn’t what you want, but just in case: of course, you can also avoid the darkening by making the box fully opaque in the first place:

```diff
-Style: Subtitle-box,Pretendard ExtraBold,22,&Hb3000000,&Hb3000000,&Hb3000000,&Hff000000,0,0,0,0,100,100,,,3,1.7,,2,10,10,40,
+Style: Subtitle-box,Pretendard ExtraBold,22,&Hb3000000,&Hb3000000,&H00909090,&Hff000000,0,0,0,0,100,100,,,3,1.7,,2,10,10,40,
```

By the way, your sample gains nothing from having `Subtitle` and `Subtitle-box` in separate lines. This should look the same:

```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Title,Pretendard ExtraBold,28,&H00ffffff,&H00ffffff,&H00000000,&H00000000,0,0,0,0,100,100,,,1,0.5,1.0,2,10,10,118,
Style: Subtitle,Pretendard ExtraBold,22,&H00ffffff,&H00ffffff,&Hb3000000,&Hff000000,0,0,0,0,100,100,,,3,1.7,,2,10,10,40,

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 11,0:00:53.91,0:00:56.91,Title,,0,0,0,,{\blur10}흥미진진한 뱀파이어 이야기
Dialogue: 0,0:00:53.91,0:01:06.45,Subtitle,,0,0,0,,진짜 신났네 신났네 목이 벌렸어요 나 아직 한 번도 안 벌렸어 잠시만요 뱀파이어로서 싱가포르 보기한테 뱀파이어로서
```

---

>  You’ll have to either reduce the border size until no parts overlap

This is barely possible. Any nonzero vertical border produces an overlap, while zero border removes the box. You can try setting `{\ybord0}` to keep the horizontally expanding box but remove the vertical component, but it may very well look bad because the box is too close to the letters, and furthermore there may still be a subpixel overlap depending on the rendering resolution and font size.

If you had predetermined line break points, you could split the event into one event per line, relying on automatic event placement to space the lines apart just enough to avoid the overlaps. Off the top of my head, this should work as long as you also set the border size to an integer, but again, rendering at other resolutions will reintroduce a subpixel gap (unless the scaling factor is also an integer).

The way I solved this when I did have predetermined line breaks was to not only split the events but also compute and add `\clip(0,topy,max,bottomy)` to each event such that the coordinates were integers halfway between every pair of lines.
