### ISSUE TITLE
coretext: failed to load system fonts on macOS 15

### ISSUE THREAD

**Issue by m154k1** [libass/libass#840]
### libass version

6a759836e5e76bb7b69b0ac244eea76b0d290512

### Is it a regression?

Yes

### ASS Sample

mpv OSD/OSC

### Special Fonts

The issue doesn't depend on a specific font

### System Information

macOS 15.0, Xcode 16.0

### Log and Stacktrace

```
[osd/libass] fontselect: failed to find any fallback with glyph 0x0 for font: (sans-serif, 400, 0)
[osd/libass] fontselect: failed to find any fallback with glyph 0x0 for font: (Menlo, 400, 0)
```

### Additional info

Since https://github.com/libass/libass/commit/6a759836e5e76bb7b69b0ac244eea76b0d290512 libass fails to load any system font on macOS 15. E.g. mpv throws log messages about missing fonts and doesn't render OSD at all.
Previous commit (https://github.com/libass/libass/commit/25e34fc07572de54a676cd1b41f786443b01cc76) works fine.

**Comment by astiob** [comment]
Apparently, the old availability macros are now [guarded](https://github.com/alexey-lysiuk/macos-sdk/blob/cee99e5c64d8e62362331d3f6d911559ba56555d/MacOSX15.0.sdk/usr/include/AvailabilityVersions.h#L339C1-L339C88) with `#if (!defined(_POSIX_C_SOURCE) && !defined(_XOPEN_SOURCE)) || defined(_DARWIN_C_SOURCE)`.

Are you using Meson to build? Does an Autoconf/Automake build work?

For some reason, our Meson build defines `_POSIX_C_SOURCE`. Our Autotools build doesn’t, as far as I can tell. This discrepancy isn’t good. cc @TheOneric

We can, of course, add `#define _DARWIN_C_SOURCE` to `ass_coretext.c`, but in any case any Autotools/Meson difference may come back to bite us.

**Comment by TheOneric** [comment]
> For some reason, our Meson build defines _POSIX_C_SOURCE. Our Autotools build doesn’t, as far as I can tell. This discrepancy isn’t good.

In Autotools builds we always used GNU-C99 *(or GNU-C90 previously)* and set `-D_GNU_SOURCE`, which afaik enables all interfaces enabled by POSIX and more. Sometimes semantics of some interface may differ a bit *(e.g. `getopt`)*, though I don’t think this affects anything we use. I’m not sure how affected interfaces behave if both `_GNU_SOURCE` and `_POSIX_C_SOURCE` are defined.

While meson was added after some discussion we settled on using the POSIX define instead since this encompassed all optional interfaces we used at the time and uhh.. some platforms potentially not recognising the GNU define while knowing about the more widespread POSIX define? Not sure anymore and finding anything in GH’s display of the PR discussion is a chore...

Our hard baseline is ISO-C99, so the idea was to eventually move Autotols to ISO-C and POSIX too, but this stalled since GNU enables a few more neat things and we added or are planning to add more optional usages of non-POSIX GNU interfaces, e.g. `strchrnul` in #772

CI was supposed to catch any discrepancies between the two defines, but clearly this didn't work out :\

**Comment by astiob** [comment]
Shall we change meson.build to `_GNU_SOURCE`? We could even add both. (See also [Autoconf’s `AC_USE_SYSTEM_EXTENSIONS`](https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/C-and-Posix-Variants.html), which includes both of these and a whole bunch more.) But I do think they should be the same in both build systems that we ship to users. If we want to use CI to detect whether we’re using more APIs than we’d ideally like, we can override the defines in our CI, but shipping different ones seems like asking for trouble.

**Comment by m154k1** [comment]
> Are you using Meson to build? Does an Autoconf/Automake build work?

Yeah, I'm using Meson. You're right, building with Autotools does work.

**Comment by TheOneric** [comment]
> Shall we change meson.build to _GNU_SOURCE? We could even add both.

yeah, setting both flags in all builds is probably the way to go now. I remain a bit concerned about semantic changes caused by GNU messing with the logic, but this already was a concern the entire time.
*(For reference: i once ran into a POSIX and GNU `getopt` difference which lead to a perfectly valid and reasonable way of parsing arguments until they’re exhausted in POSIX to become an infinite loop with glibc’s GNU semantics)*

A "POSIX but not any GNU" CI test env would be good; perhaps macOS already is this? Same for "pure ISO-C99 only"

**Comment by m154k1** [comment]
> We can, of course, add `#define _DARWIN_C_SOURCE` to `ass_coretext.c`, but in any case any Autotools/Meson difference may come back to bite us.

Yep, that also works. I think I'll use `-Dc_args='-D_DARWIN_C_SOURCE'` for now.
