### ISSUE TITLE
Fonts with right-angled edges will be rendered with rounded corners after using the bord tag

### ISSUE THREAD

**Issue by chenyangxx** [libass/libass#858]
[1890-Bangers-Regular.ttf.zip](https://github.com/user-attachments/files/18259181/1890-Bangers-Regular.ttf.zip)

This is the stroke effect we want, right angle：
<img width="279" alt="image" src="https://github.com/user-attachments/assets/43afb1f7-1e20-43b9-acac-c627189ea2a1" />

This is the effect achieved using the ass \bord tag：
<img width="233" alt="image" src="https://github.com/user-attachments/assets/c46f30ff-1ca2-423e-96f8-2d23f65075fd" />

As far as I understand, fonts with right-angled edges should have a right-angled stroke applied when adding a stroke, but apparently libass seems to have done some smoothing inside. Is there any way to keep the original right-angled stroke of the font?
I provided a right-angled edge font at the beginning, please take a look at the problem

**Comment by rcombs** [comment]
This is the expected behavior of stroke in the ASS format (and it's generally the method that most reliably avoids producing edge-case artifacts, like the odd shape of the top-right corner of the "Y" in your first image, or whatever's going on beneath the "VI").

If you'd like to typeset an effect using a different stroke algorithm, you can pre-generate the curves in a vector editor and use the drawing feature, though note you'll probably want to clean up the edges manually, since stroke algorithms that produce sharp corners like you want almost always produce unwanted output with at least some glyph shapes.

**Comment by arch1t3cht** [comment]
If you're using Aegisub, you can use the Offsetting tool from the script Shapery (installable from dependencycontrol) to convert your text into a drawing and stroke that with a method of your choice.
