### ISSUE TITLE
Implement fast floating-point(?) Gaussian blur using SIMD

### ISSUE THREAD

**Issue by rcombs** [libass/libass#9]
Use xy-vsfilter's SSE2 implementation and Intel's AVX implementation when applicable. Write a NEON implementation for ARM, and possibly an SSE4-or-such implementation (but probably not :|). Probably can wait until after #5 is done.

**Comment by astiob** [comment]
Huhh, this is rightfully closed because the thing in the issue title has been done, but the comments went off a tangent and are a goldmine.

I should probably repost those pictures I apparently posted. I do have them, but there’s _a lot_ and I don’t remember how I organized them when I uploaded them.

Anyway, libass’s and xy-VSFilter’s blur parameters are actually different? I sure didn’t remember that, and I do remember making it a point to preserve libass’s parameters when merging MrSmile’s blur. So the output looks different… yet oddly similar at the same time, because we also clip the kernels differently 🤯
